### ISSUE TITLE
Test Suite aborts on NoSuchMethodError

### ISSUE THREAD

**Issue by thomg** [scalatest/scalatest#1001]
I just upgraded our complete codebase to use 3.0.0 and after fixing all the deprecations, I still see tests sporadically abort with this message. This seems to happen in Jenkins more than local builds, though I'm still trying to nail down the pattern (if there is one).

Of course, when it happens on Jenkins, we don't always notice, because of Issue #297 which doesn't seem to actually be fixed.

```
Cause: java.lang.NoSuchMethodError: org.scalatest.FunSpecLike$ItWord.apply(Ljava/lang/String;Lscala/collection/Seq;Lscala/Function0;)V
at com.truefit.utils.misc.MessageBundleSpec$$anonfun$checkAllPropertiesExist$1.apply(MessageBundleSpec.scala:128)
at com.truefit.utils.misc.MessageBundleSpec$$anonfun$checkAllPropertiesExist$1.apply(MessageBundleSpec.scala:126)
at scala.collection.Iterator$class.foreach(Iterator.scala:727)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
at com.truefit.utils.misc.MessageBundleSpec$class.checkAllPropertiesExist(MessageBundleSpec.scala:126)
at com.truefit.consumer.model.LocalePropertySpec.checkAllPropertiesExist(LocalePropertySpec.scala:8)at com.truefit.consumer.model.LocalePropertySpec$$anonfun$1.apply$mcV$sp(LocalePropertySpec.scala:10)
at org.scalatest.SuperEngine.registerNestedBranch(Engine.scala:595)
...
```

**Comment by jamespercy** [comment]
I'm getting the same here. Definitely a lot more on our Jenkins builds

**Comment by thomg** [comment]
This turned out to be user error. We had a test suite that depended on code in another repo and I hadn't pushed the version update to that repo, yet. Getting both repos (and therefore code artifacts) on 3.0.0 fixed the problem.

**Comment by bvenners** [comment]
Hey, sometimes when you ignore an issue it just goes away! Sorry for the delay in looking into this. Just haven't been able to catch up yet. Glad to hear you got it working.

**Comment by jamespercy** [comment]
The fix for me was a bit different. The scala gradle plugin gets the zinc classpaths mixed up.

adding 
```
            if (it.name == "zinc") {
                force 'org.scala-lang:scala-library:2.10.5'
            } 
```
to 
```
configurations.all {
        resolutionStrategy {
```

fixed the issue
