### ISSUE TITLE
Add 'org.scalatest.compatible' to Export-Packages of MANIFEST.MF

### ISSUE THREAD

**Issue by michael-smith** [scalatest/scalatest#1003]
Without the export of this package, it causes some problems with OSGi BND tools that know the bundle requires use of this package but does not export it.

**Comment by cheeseng** [comment]
hi @michael-smith this is fixed in the just released 3.0.1, can you give it a try?

**Comment by michael-smith** [comment]
Yes, I'm sorry I never actually noticed this notification. It works now, thanks.
