### ISSUE TITLE
Line wrapping of "should be" assertion makes it noop

### ISSUE THREAD

**Issue by savulchik** [scalatest/scalatest#1015]
A colleague of mine discovered that wrapping a line with "should be" assertion yields a successful outcome in the following test:
```scala
class FooBarTest extends FlatSpec with Matchers {
  it should "fail" in {
    "foo" should be
      "bar"
  }
} 
```
It seems like the line wrapping makes the supposed assertion to be two distinct expressions:
- `"foo".should(be): ResultOfBeWordForAny[String]`
- `"bar": String`

instead of `"foo".should(be.apply("bar")): Assertion`

`"org.scalatest" % "scalatest_2.11" % "3.0.1"`

**Comment by bvenners** [comment]
Yes, thats unfortunately a feature. It is something users need to learn and watch out for. It is in general possible to get Scala to infer a semicolon where you don't want one, and so you would normally leave an operator dangling at the end of a line break. In the future we'll probably rename FlatSpec to AnyFlatSpec, and although there the "feature" would persist, in the new FunSpec, the result type of a test would be Assertion and the above code would not compile.
