### ISSUE TITLE
TableDrivenPropertyChecks doesn't run with singleton list

### ISSUE THREAD

**Issue by dmyersturnbull** [scalatest/scalatest#1019]
#### never prints anything

```scala
	property("huh") {
		forAll(Table("111")) { (s: String) => {
			println(s)
			s should equal ("000")
		}}
	}
```

#### prints and fails test

```scala
	property("huh") {
		forAll(Table("111", "000")) { (s: String) => {
			println(s)
			s should equal ("000")
		}}
	}
```

**Comment by bvenners** [comment]
The first item given to a Table is the names of the columns. So in Table("111") you've named the lone column ("111") and given it no values. The forAll does do the right thing in that case, which is succeed. The universal quantifier is supposed to do that when there's no elements.

I think the second one does not fail the test, but succeeds as it should. Here you've named your column "111" again, but given one element, "000". So the assertion succeeds:

scala> forAll(Table("111", "000")) { (s: String) =>
     |   println(s)
     |   s should equal ("000")
     | }
000
res0: org.scalatest.compatible.Assertion = Succeeded

You don't need the extra set of curly braces after the => by the way.

At least it does on a branch I'm working on which is where I tried it, but I don't think that should have changed. Please give that a try. I'll close this. We can reopen if there's really a bug.
