### ISSUE TITLE
TripleEquals not working

### ISSUE THREAD

**Issue by ryan-williams** [scalatest/scalatest#1036]
I'm trying to reproduce the type-safe `should ===` example from [the docs](http://www.scalatest.org/user_guide/using_matchers#checkingEqualityWithMatchers) on Scalatest 3.0.0:

```scala
scala> import org.scalactic.TypeCheckedTripleEquals._
import org.scalactic.TypeCheckedTripleEquals._

scala> import org.scalatest.Matchers._
import org.scalatest.Matchers._

scala> Some(2) should === (2)
org.scalatest.exceptions.TestFailedException: Some(2) did not equal 2
  at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
  at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
  ... 42 elided
```

The code compiles and fails at runtime, instead of at compile-time like it's supposed to.

Am I doing something wrong or is `===`'s type-safety-checking broken?

**Comment by bvenners** [comment]
Matchers has a default anything goes equality policy that is overriding the one you imported above it. You need to either import Matchers first, or just mix in TypeCheckedTripleEquals after Matchers.

```scala
scala> import org.scalatest.Matchers._
import org.scalatest.Matchers._

scala> import org.scalactic.TypeCheckedTripleEquals._
import org.scalactic.TypeCheckedTripleEquals._

scala>  Some(2) should === (2)
<console>:27: error: types Some[Int] and Int do not adhere to the type constraint selected for the === and !== operators; the missing implicit parameter is of type org.scalactic.CanEqual[Some[Int],Int]
        Some(2) should === (2)
                ^
```

**Comment by ryan-williams** [comment]
Ah, I see, I'd mixed up the order vs. the example in the docs, thanks!

**Comment by rethab** [comment]
Is there any way to make this less error-prone? It is so easy to get it wrong, because both ways compile.

Perhaps a new matcher, like `shouldBeEq` that enforces both sides to have the same type without relying on the user to get the implicits right?

**Comment by bvenners** [comment]
@rethab I think that for Scala 3 we will try to hook into multiversal equality by default.

**Comment by rethab** [comment]
That sounds great, thanks @bvenners
