### ISSUE TITLE
No stacktraces when using PropSpec

### ISSUE THREAD

**Issue by aishfenton** [scalatest/scalatest#1046]
When Property checks fail there (doesn't appear) to be anyway get the stacktrace of that failure.

Normally in Scalacheck you'd set the verbosity level to address that, but I can't find anyway to do that in Scalatest (the Prop Configuration class doesn't include that as a field). 

Am I missing something? Or is this an option that needs to be added. Regardless, I'd suggest that the default should be to show a short stacktrace.

```scala
class TestSpec extends PropSpec with GeneratorDrivenPropertyChecks with Matchers {

  val genInts = Gen.containerOf[Array, Int] { Gen.chooseNum(Int.MinValue, Int.MaxValue) }

  property("Out of bounds") { 
    forAll(genInts) { posArr => posArr(100) }  
  }
}
```

```
[info] - Out of bounds *** FAILED ***
[info]   ArrayIndexOutOfBoundsException was thrown during property evaluation.
[info]     Message: 100
[info]     Occurred when passed generated values (
[info]       arg0 = Array()
[info]     )
```

NB: In the example I gave above it's  trivial to figure out where the IndexOutOfBounds is happening, but in a normal case it could be from deep within a method you're calling. In which case a stack trace is needed to figure out where it's failing.

**Comment by aishfenton** [comment]
Although strangely enough, when I run the same test through IntelliJ it does give the stacktrace. I suppose because it uses a custom Reporter?

**Comment by bvenners** [comment]
It could be that your stack trace config setting is set to none. That is the default. You can get short stack traces with -oS and full stack traces with -oF. For test-only, for example:

> test-only *TestSpec -- -oS

**Comment by aishfenton** [comment]
Yes that solved it... sorry that was obvious, I swear I'd already tried that.
