### ISSUE TITLE
Installation Instruction Error on scalatest.org

### ISSUE THREAD

**Issue by mingsterism** [scalatest/scalatest#1065]
On the page http://www.scalatest.org/install 
the command should be `addSbtPlugin("com.artima.supersafe" % "sbtplugin" % "1.1.1")` instead of 
`addSbtPlugin("com.artima.supersafe" % "sbtplugin" % "1.1.0")`

**Comment by salvob41** [comment]
this depends on your scala version! 
The last version of Scala 2.11 (that is 2.11.8 ) works perfectly fine with 1.1.0 

If you are using Scala 2.12 none of them works properly as shown in #1089

**Comment by bvenners** [comment]
We have updated the site to the latest version of supersafe, 1.1.2, which should work with almost all versions of 2.10 and any version of 2.11 and 2.12.
