### ISSUE TITLE
SuperSafe Community Edition Scala compiler plugin doesn't work with Scala 2.12

### ISSUE THREAD

**Issue by salvob41** [scalatest/scalatest#1089]
In a sbt project using Scala version 2.12.1 
using the command in `plugins.sbt` : 
`addSbtPlugin("com.artima.supersafe" % "sbtplugin" % "1.1.0")`
the plugin failed to be imported and the following is shown
```
                        SBT project import
			[warn] 	[FAILED     ] com.artima.supersafe#supersafe_2.11.8;1.1.2!supersafe_2.11.8.jar(src):  (0ms)
			[warn] ==== local: tried
			[warn]   /Users/salvob/.ivy2/local/com.artima.supersafe/supersafe_2.11.8/1.1.2/srcs/supersafe_2.11.8-sources.jar
			[warn] ==== public: tried
			[warn]   https://repo1.maven.org/maven2/com/artima/supersafe/supersafe_2.11.8/1.1.2/supersafe_2.11.8-1.1.2-sources.jar
			[warn] ==== Artima Maven Repository: tried
			[warn]   http://repo.artima.com/releases/com/artima/supersafe/supersafe_2.11.8/1.1.2/supersafe_2.11.8-1.1.2-sources.jar
			[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
			[warn] 	::              FAILED DOWNLOADS            ::
			[warn] 	:: ^ see resolution messages for details  ^ ::
			[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
			[warn] 	:: com.artima.supersafe#supersafe_2.11.8;1.1.2!supersafe_2.11.8.jar(src)
			[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
			```

**Comment by cheeseng** [comment]
Hi,

SuperSafe community edition does not come with source, I wonder if you have
withSource enabled?

Chee Seng

**Comment by salvob41** [comment]
Hello @cheeseng ,

That made me think too, but I didn't explicitly add `withSources()` .  The command `addSbtPlugin("com.artima.supersafe" % "sbtplugin" % "1.1.0")` is the only line in `plugins.sbt` file.

In fact, if I change the scala version (e.g. `scalaVersion := "2.11.8"`) in my `build.sbt`, it works correctly. Are you able to reproduce the issue in a sbt project of yours?

**Comment by cheeseng** [comment]
@salvob41 I couldn't reproduce, but for Scala 2.12.1 I think you should use 1.1.2: 

addSbtPlugin("com.artima.supersafe" % "sbtplugin" % "1.1.2")

can you try to see if that works for you?

**Comment by salvob41** [comment]
@cheeseng , that was it. So you should check in the release repo website the `supersafe_`_scala_version_ and see what is the supersafe version (that is 1.1.2 for scala version 2.12.1 ) and use that as version artifact in `sbtPlugin`.

Thank you, 
Closing this issue
