### ISSUE TITLE
Broken link in "Using ScalaTest with sbt" user guide

### ISSUE THREAD

**Issue by futtetennista** [scalatest/scalatest#1131]
In the [Using ScalaTest with sbt](http://www.scalatest.org/user_guide/using_scalatest_with_sbt) section **Include and Exclude Tests with Tags** the link to the [documentation for Suite](http://www.artima.com/docs-scalatest-3.0.0/index.html#org.scalatest.Suite) is broken.

**Comment by plinlor** [comment]
PR submited:  https://github.com/scalatest/scalatest-website/pull/80

**Comment by bvenners** [comment]
PR merged
