### ISSUE TITLE
All links to scaladocs for Scalactic classes are broken in the user guides (scalatest/scalactic)

### ISSUE THREAD

**Issue by agemooij** [scalatest/scalatest#1136]
All user guide links to for instance `Equality` and `Explicitly` point towards the scaladocs for scalatest while they should be pointing to the scaladocs for scalactic. This is even true for the links in the user guide for Scalactic itself.

References:

- http://www.scalactic.org/user_guide/CustomEquality (first link to `Equality`)
- http://www.scalatest.org/user_guide/using_matchers#checkingEqualityWithMatchers

There are many more of these. As far as I could see, all references to scaladocs for Scalactic classes are broken.

**Comment by plinlor** [comment]
Fixed these for both websites via the following PRs:

https://github.com/scalatest/scalatest-website/pull/84
https://github.com/scalatest/scalactic-website/pull/10

**Comment by bvenners** [comment]
Merged into master.
