### ISSUE TITLE
Version 3.0.2 for Scala 2.10 includes bytecode compiled for Java 8

### ISSUE THREAD

**Issue by nrinaudo** [scalatest/scalatest#1141]
Running `javap` against some classes found in the scalatest 3.0.2 JAR compiled for Scala 2.10, we find a major version of `52` - Java 8. This is obviously a problem when trying to run scalatest on, say, Java 7.

The issue appears quite specific:
* *scala* code is compiled against Java 6 (`javap` on `org/scalatest/Doc$.class` yields a major version of 50)
* *java* code is compiled against java 8 (`javap` on `org/scalatest/DoNotDiscover.class` yields a major version of 52)

**Comment by cheeseng** [comment]
@nrinaudo Yes it was my mistake that on my machine that I launched sbt using java 6 but had JAVA_HOME pointed to java 8, and in our build we're reading JAVA_HOME env var and set it as javaHome: 

https://github.com/scalatest/scalatest/blob/3.0.x/project/scalatest.scala#L65

We think that's the reason why scala code was compiled with java 6 but java code was with java 8.

I am going to start to publish a 3.0.3 now to fix this, I am sorry for the inconvenient caused.

**Comment by nrinaudo** [comment]
No problem - I identified the issue quickly because the same thing happened to me at *least* twice :)

Thanks for the quick turnaround!

**Comment by cheeseng** [comment]
@nrinaudo 3.0.3 published, feel free to close this issue once you verify that it fixes the problem you described  :)

**Comment by nrinaudo** [comment]
Confirmed, the problem is gone. Thansk!
