### ISSUE TITLE
Supersafe Support for 2.12.2/2.11.11

### ISSUE THREAD

**Issue by agarbutt** [scalatest/scalatest#1143]
Thanks for the hard work.

Any word on a release of the super safe plugin for the recent Scala releases?

Let me know if this issue should be logged in a more preferred location.

**Comment by cheeseng** [comment]
@agarbutt SuperSafe 1.1.2 built for Scala 2.11.11 and Scala 2.12.2 has been released, please close this issue after you verify they worked for you.

**Comment by agarbutt** [comment]
Thank you for publishing the release!!!  Works well so far.  Sorry for the late reply.
