### ISSUE TITLE
release scalatest_sjs0.6_2.13.0-M1

### ISSUE THREAD

**Issue by xuwei-k** [scalatest/scalatest#1152]

**Comment by darkfrog26** [comment]
I just ran into this myself.  I see that there's a JVM release of it but not a JS release.

**Comment by cheeseng** [comment]
@xuwei-k @darkfrog26 Unfortunately we'll need to wait until ScalaCheck release first: 

https://github.com/rickynils/scalacheck/issues/330

**Comment by xuwei-k** [comment]
scalacheck_sjs0.6_2.13.0-M1 released
https://oss.sonatype.org/content/repositories/releases/org/scalacheck/scalacheck_sjs0.6_2.13.0-M1/

**Comment by gmethvin** [comment]
@cheeseng It would be nice to have a release for this soon.

**Comment by cheeseng** [comment]
@gmethvin @xuwei-k sorry got tied up with other works, will attempt to release it today.

**Comment by cheeseng** [comment]
@gmethvin @xuwei-k @darkfrog26 fyi I just released 3.0.3 for JS built for Scala 2.13.0-M1, please kindly close this issue after you test and it works for you, thanks!  :)

**Comment by xuwei-k** [comment]
thanks!
