### ISSUE TITLE
Scalatest does not work in latest versions of Scala.js

### ISSUE THREAD

**Issue by nartamonov** [scalatest/scalatest#1164]
Even very simple tests (see [demo repository](https://github.com/nartamonov/scalatest-inlining-bug)) can't be optimized by ScalaJS optimizer:

```
frontend > test
[info] Compiling 1 Scala source to C:\Temp\scalatest-bug\target\scala-2.12\test-classes...
[info] Fast optimizing C:\Temp\scalatest-bug\target\scala-2.12\frontend-test-fastopt.js
[trace] Stack trace suppressed: run last test:fastOptJS for the full output.
[error] (test:fastOptJS) org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$OptimizeException: The Scala.js optimizer crashed while optimizing jl_Character$.charTypes$lzycompute__p1__AB: java.lang.StackOverflowError
[error] Methods attempted to inline:
[error] Total time: 10 s, completed 06.06.2017 17:37:13
```

Tried with Scala.js 0.6.16 and Scala.js 0.6.17. 

Tried with Scalatest 3.0.0 and latest 3.0.3.

Scala 2.12.1

JDK 1.8.0_71 32bit

Windows 7 SP1

SBT 0.13.13

**Comment by nartamonov** [comment]
Solved issue by manually increasing stack size with `-Xss4m`. May be we should document it somewhere. I have not seen this issue in the past. Perhaps it occures with Win32 JDK only.

**Comment by dneades** [comment]
For the record, I have just encountered this same exception with a non-test compile, using a 64-bit JDK 1.8.0_131 on Windows 10 CU. The `-Xss4m` fix suggested by @nartamonov solved the problem.

**Comment by bbarker** [comment]
I also had this problem, but I wasn't using scalatest. The odd thing was, I'm pretty sure the day before it was working with no known changes in either my environment or in the source. I switched from one branch of my project to another, then back to the original branch, at which point I noticed the problem, and wasn't able to get it to go away until I added ` -J-Xss4m ` to my  my `.sbtopts` as suggested by @dneades .

**Comment by bbarker** [comment]
I also had this problem, but I wasn't using scalatest (cc @sjrd) . The odd thing was, I'm pretty sure the day before it was working with no known changes in either my environment or in the source. I switched from one branch of my project to another, then back to the original branch, at which point I noticed the problem, and wasn't able to get it to go away until I added ` -J-Xss4m ` to my  my `.sbtopts` as suggested by @dneades .

Using the following plugins with `crossScalaVersions in ThisBuild := Seq("2.12.1", "2.11.8")` on [Ubuntu 16.04 + some nixpkgs in a container](https://github.com/CornellCAC/docker-nix-intellij) also running on Ubuntu 16.04 (too much info?) and `sbt.version=0.13.11` :

```
addSbtPlugin("io.get-coursier"   % "sbt-coursier" % "1.0.0-RC12")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "1.0.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "1.1")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"  % "0.6.18")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalajs-bundler" % "0.5.0")
```
