### ISSUE TITLE
Matching wrapped exceptions with scalatest intercept

### ISSUE THREAD

**Issue by pranaydoshi** [scalatest/scalatest#1177]
Is it possible with scalatest to match a wrapped exception using intercept? I can't find any usages online.

**Comment by bvenners** [comment]
The answer is that you can intercept the outer exception, and then inspect the cause. Something like:

val intercepted = intercept[OuterExceptionType] { ... }
assert(intercepted.cause.isInstanceOf[InnerExceptionType])

In the future, please ask questions like this on the scalatest-users mailing, as this is a support question not an issue.
