### ISSUE TITLE
Support scala.js 1.0.0-M1

### ISSUE THREAD

**Issue by cquiroz** [scalatest/scalatest#1178]
it would be good to add support for 1.0.0 milestone. I cannot publish my own open source due to my dependency on scaltest

**Comment by cheeseng** [comment]
@cquiroz I tried a quick build but unfortunately it turns out it is more involving, e.g. runNow execution context is now removed and scala.scalajs.js.annotation.JSExportDescendentClasses is no more there too, here's my branch: 

https://github.com/cheeseng/scalatest/tree/experiment-scala-js-1.0.0-M1

It's quite a project to do, unfortunately.

**Comment by cquiroz** [comment]
Thanks, I can try to follow up based on your branch

**Comment by sjrd** [comment]
For `@JSExportDescendantClasses`, consult the release notes of Scala.js 0.6.15: https://www.scala-js.org/news/2017/03/21/announcing-scalajs-0.6.15/#jsexportdescendentclasses-and-jsexportdescendentobjects-are-deprecated-without-direct-replacement
It should be easy to migrate to the new system.

For `runNow`, one dirty quick way of dealing with the suppression is to copy-paste [its source from 0.6.x](https://github.com/scala-js/scala-js/blob/0.6.x/library/src/main/scala/scala/scalajs/concurrent/RunNowExcecutionContext.scala) into your codebase.

Note that these changes can also be applied to the "main" branch that compiles to 0.6.x. In general, 1.0.0-M1 should be close to a subset of 0.6.18, so making things work in 1.0.0-M1 does not break the 0.6.x build.

**Comment by marcospereira** [comment]
This is probably not relevant anymore since scala.js 1.0.0 was released, and also, support for 1.0.0-RC2 was already published. See https://github.com/scalatest/scalatest/pull/1742.

**Comment by cquiroz** [comment]
We can close this
