### ISSUE TITLE
PosInt.apply and wartremover

### ISSUE THREAD

**Issue by fommil** [scalatest/scalatest#1181]
the macro in `PosInt.apply` is using `Option.get` (I assume safely), but wartremover doesn't trust that it is safe usage. Solution is to add this annotation (no dependencies)

```
  @SuppressWarnings(Array("org.wartremover.warts.OptionPartial"))
```

**Comment by bvenners** [comment]
@fommil actually we have changed this already. In 3.1.x, we don't call .get on Option, we do:

PosInt.ensuringValid(value.splice)

**Comment by fommil** [comment]
Sorry I should have closed this... wartremover should allow ignoring expanded macros.
