### ISSUE TITLE
publish for 2.13.0-M2, plz?

### ISSUE THREAD

**Issue by SethTisue** [scalatest/scalatest#1189]
prerequisite, though: https://github.com/rickynils/scalacheck/issues/349

**Comment by bvenners** [comment]
Sure. We'll get it out once we have ScalaCheck.

**Comment by cheeseng** [comment]
@SethTisue @bvenners I was thinking to do this today but unfortunately blocked by: 

https://github.com/rickynils/scalacheck/issues/349

Feel free to ping us again once ScalaCheck build is available, we would like to get it out asap too, sorry for the inconvenience caused.

**Comment by limansky** [comment]
I've created pull request rickynils/scalacheck#353

**Comment by xuwei-k** [comment]
scalacheck for Scala 2.13.0-M2 released

- https://oss.sonatype.org/content/repositories/releases/org/scalacheck/scalacheck_2.13.0-M2/
- https://oss.sonatype.org/content/repositories/releases/org/scalacheck/scalacheck_sjs0.6_2.13.0-M2/

**Comment by cheeseng** [comment]
@xuwei-k Thanks for notifying, I'll attempt a release today.

**Comment by limansky** [comment]
@cheeseng Any news on this issue?

**Comment by SethTisue** [comment]
hate to be a pest, but.... ping?

**Comment by cheeseng** [comment]
Hi @SethTisue @limansky @xuwei-k @marcospereira , sorry for the delay, I have published 3.0.4 for Scala 2.13.0-M2.

**Comment by SethTisue** [comment]
@cheeseng thank you! I've added it to the 2.13.0-M2 libraries page, and mentioned it in the 2.13.0-M2 thread on contributors.scala-lang.org, and I'm working on using it to publish genjavadoc for 2.13.0-M2
