### ISSUE TITLE
Remove dependency on deprecated pegdown to generate html reports.

### ISSUE THREAD

**Issue by girishsubramanyam** [scalatest/scalatest#1201]
Scalatest has a dependency on pegdown to generate html reports. Given that pegdown is deprecated, can we start supporting flexmark-java ?

https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/tools/HtmlReporter.scala#L35

**Comment by fancywriter** [comment]
https://github.com/scalatest/scalatest/pull/1229 is green now
