### ISSUE TITLE
Please make a list of enhancements/bug fixes/deprecations for 3.1.x

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest#1218]
Hi Chee Seng,

Please take a look through the commits in the 3.1.x branch and draft a list of enhancements, bug fixes, and deprecations for the release notes. Please separate out lists for ScalaTest and Scalactic. Can just paste them in here and Peter can start from that when creating the release notes.

Thanks.

Bill

**Comment by cheeseng** [comment]
This is an expanding list while I going through the commits: 

Enhancements: 
- Enhanced WebBrowser's isInputField method to handle element has attribute 'type' value returns null as 'text' type.
- Enhanced WebBrowser's value_= method to execute javascript to set value when the driver being used is JavascriptExecutor.

**Comment by cheeseng** [comment]
@bvenners @plinlor I completed the list, thanks.

**Comment by cheeseng** [comment]
Indeed, I forgot to separate them into scalactic and scalatest, I'll do that now.

**Comment by cheeseng** [comment]
@bvenners @plinlor I am done now, thanks!

**Comment by bvenners** [comment]
Closing this one. Next step is this ticket:

https://github.com/scalatest/scalatest-website/issues/85

**Comment by plinlor** [comment]
@cheeseng could you please clarify wording on the following two items (the rest look good):

Enhanced WebBrowser's isInputField method to handle element has attribute 'type' value returns null as 'text' type.

Fixed macro-based assertion that has problem when used directly with package name without mixin in/import the trait.

**Comment by cheeseng** [comment]
@plinlor 

For: 
Enhanced WebBrowser's isInputField method to handle element has attribute 'type' value returns null as 'text' type.

The new behavior will treat input element that returns null when getType is called as text input element.

For: 
Fixed macro-based assertion that has problem when used directly with package name without mixin in/import the trait.

Before this fix, the following will not work: 

org.scalatest.Assertions.assert(a1 === a3)

The user will need to mix in Assertions into their class and use: 

assert(a1 === a3)

After the fix both of the cases will be working.

**Comment by cheeseng** [comment]
@bvenners @plinlor Indeed I would propose the bug fix of the macro assertion to be cherry-picked into 3.0.x and released together as 3.0.5, and it should go into release note for 3.0.5 as patch/point release where bug fixes should be.

**Comment by plinlor** [comment]
Tweaked the 3.1.0 release notes file per Chee Seng's clarifications above, in branch feature-add-3.1.0-releasenotes of ScalaTest.  Closing this issue for now.
