### ISSUE TITLE
Compiler errors under 2.10.6 when merging PR 1214 commits into 3.1.x

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest#1221]
Hi Chee Seng,

When I tried merging in the following branch of PR1214 cherry picks into 3.1.x:

https://github.com/scalatest/scalatest/tree/feature-cherry-pick-PR1214-commits-into-3.1.x

And tried compiling under 2.10.6, I get these compiler errors:

$ sbt ++2.10.6 clean scalactic-test/test
...
[info] Compiling 55 Scala sources to /Users/bv/nobkp/delus/st-crisp-clean-fallish-air/scalactic/target/scala-2.10/classes...
[error] /Users/bv/nobkp/delus/st-crisp-clean-fallish-air/scalactic/src/main/scala/org/scalactic/anyvals/NonEmptyArray.scala:1547: type mismatch;
[error]  found   : scala.collection.mutable.IndexedSeq[L]
[error]  required: Array[L]
[error]     (new NonEmptyArray(unzipped._1), new NonEmptyArray(unzipped._2))
[error]                                 ^
[error] /Users/bv/nobkp/delus/st-crisp-clean-fallish-air/scalactic/src/main/scala/org/scalactic/anyvals/NonEmptyArray.scala:1547: type mismatch;
[error]  found   : scala.collection.mutable.IndexedSeq[R]
[error]  required: Array[R]
[error]     (new NonEmptyArray(unzipped._1), new NonEmptyArray(unzipped._2))
[error]                                                                 ^
[error] /Users/bv/nobkp/delus/st-crisp-clean-fallish-air/scalactic/src/main/scala/org/scalactic/anyvals/NonEmptyArray.scala:1561: type mismatch;
[error]  found   : scala.collection.mutable.IndexedSeq[L]
[error]  required: Array[L]
[error]     (new NonEmptyArray(unzipped._1), new NonEmptyArray(unzipped._2), new NonEmptyArray(unzipped._3))
[error]                                 ^
[error] /Users/bv/nobkp/delus/st-crisp-clean-fallish-air/scalactic/src/main/scala/org/scalactic/anyvals/NonEmptyArray.scala:1561: type mismatch;
[error]  found   : scala.collection.mutable.IndexedSeq[M]
[error]  required: Array[M]
[error]     (new NonEmptyArray(unzipped._1), new NonEmptyArray(unzipped._2), new NonEmptyArray(unzipped._3))
[error]                                                                 ^
[error] /Users/bv/nobkp/delus/st-crisp-clean-fallish-air/scalactic/src/main/scala/org/scalactic/anyvals/NonEmptyArray.scala:1561: type mismatch;
[error]  found   : scala.collection.mutable.IndexedSeq[R]
[error]  required: Array[R]
[error]     (new NonEmptyArray(unzipped._1), new NonEmptyArray(unzipped._2), new NonEmptyArray(unzipped._3))
[error]                                                                                                 ^
[error] 5 errors found
[

Please see if you can get those working under 2.10, and if so, please submit a PR against the 
feature-cherry-pick-PR1214-commits-into-3.1.x  branch.

Thanks.

Bill

**Comment by cheeseng** [comment]
Hi @bvenners ,

I think it is not related to commits in 1214, the current 3.1.x is broken under scala 2.10 and the following pending PR is an attempt to fix it: 

https://github.com/scalatest/scalatest/pull/1216

Can you try to merge PR 1216 first before cherry-picking 1214 into 3.1.x?

Thanks.

**Comment by bvenners** [comment]
Hi Chee Seng,

I got past the NonEmptyArray errors, but under 2.10 get these now:

[info] *** 3 TESTS FAILED ***
[info] NegZIntSpec:
[info] A NegZInt
[info] - should offer 'to' and 'until' methods that are consistent with Int *** FAILED *** (247 milliseconds)
[info]   IllegalArgumentException was thrown during property evaluation.
[info]     Message: -736556433 to 2147483647 by 1: seqs cannot contain more than Int.MaxValue elements.
[info]     Occurred when passed generated values (
[info]       arg0 = NegZInt(-736556433),
[info]       arg1 = 2147483647,
[info]       arg2 = 0 // 31 shrinks
[info]     )
[info] NonZeroIntSpec:
[info] A NonZeroInt
[info] - should offer 'to' and 'until' methods that are consistent with Int *** FAILED *** (55 milliseconds)
[info]   IllegalArgumentException was thrown during property evaluation.
[info]     Message: 1035381157 to -2147483648 by -1: seqs cannot contain more than Int.MaxValue elements.
[info]     Occurred when passed generated values (
[info]       arg0 = NonZeroInt(1035381157),
[info]       arg1 = -2147483648,
[info]       arg2 = -1
[info]     )
[info] NegIntSpec:
[info] A NegInt 
[info] - should offer 'to' and 'until' methods that are consistent with Int *** FAILED *** (40 milliseconds)
[info]   IllegalArgumentException was thrown during property evaluation.
[info]     Message: -1046356934 to 1368923233 by 1: seqs cannot contain more than Int.MaxValue elements.
[info]     Occurred when passed generated values (
[info]       arg0 = NegInt(-1046356934),
[info]       arg1 = 1368923233,
[info]       arg2 = 0 // 32 shrinks
[info]     )

That looks very familiar, so I thought it was fixed somewhere already, but I can't find a PR with that in it. Please either point me to that PR or create a new one for this. I went ahead and pushed the cherry-picked commits to 3.1.x.

Thanks.

Bill

**Comment by cheeseng** [comment]
Hi @bvenners , I submitted the following PR to fix the failing tests under scala 2.10 in 3.1.x: 

https://github.com/scalatest/scalatest/pull/1222

The fix actually is better than the fix I did in 3.0.x for Pos anyvals, so I ported over the the fix to 3.0.x and submitted this PR: 

https://github.com/scalatest/scalatest/pull/1223

It should be cherry-picked into 3.1.x after it goes into 3.0.x.

Thanks.

**Comment by bvenners** [comment]
Both PRs are merged. Closing.
