### ISSUE TITLE
Make cherry pick PR for travis against 3.1.x

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest#1227]
Hi Chee Seng,

I merged this PR yesterday into 3.0.x:

https://github.com/scalatest/scalatest/pull/1219

Can you do a PR with cherry picks from those commits into 3.1.x?

Thanks.

Bill

**Comment by bvenners** [comment]
Hi Chee Seng,

I merged in this PR also into 3.0.x:

https://github.com/scalatest/scalatest/pull/1228

I started cherry picking that one to 3.1.x, and it occurred to me it would probably be best if we cherry pick these commits in the order they were made to 3.0.x. Can you also include the 3 commits of this PR, as appropriate, in the PR for cherry picking #1219?

Thanks.

Bill

**Comment by bvenners** [comment]
Hi Chee Seng,

One more. I merged this one into 3.0.x:

https://github.com/scalatest/scalatest/pull/1230

So when you make the cherry pick PR to 3.1.x, please include #1230's commit as well.

Thanks.

Bill

**Comment by bvenners** [comment]
Hi Chee Seng,

And one more:

Minor fix for travis:

https://github.com/scalatest/scalatest/pull/1233

Bill

**Comment by cheeseng** [comment]
Completed in the following PR: 

https://github.com/scalatest/scalatest/pull/1235
