### ISSUE TITLE
Please make a PR to pull 3.1.x into 3.2.x

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest#1240]
Hi Chee Seng,

I made a 3.2.x branch from feature-algebra-and-laws. When I go to pull from 3.1.x, I got a few conflicts in the build and generators. Can you make a branch to resolve those conflicts and submit a PR against 3.2.x?

Here's what I get when trying to pull 3.1.x into 3.2.x.

Mi-Novia-2015:st-built-for-3.2.x bv$ git pull origin 3.1.x
From github.com:scalatest/scalatest
 * branch            3.1.x      -> FETCH_HEAD
Auto-merging scalatest/src/main/scala/org/scalatest/CompileMacro.scala
CONFLICT (content): Merge conflict in scalatest/src/main/scala/org/scalatest/CompileMacro.scala
Auto-merging scalatest/src/main/resources/org/scalatest/ScalaTestBundle.properties
Auto-merging scalatest-test/src/test/scala/org/scalatest/ExpectationsSpec.scala
Auto-merging scalactic-test/src/test/scala/org/scalactic/anyvals/PosZIntSpec.scala
Auto-merging scalactic-test/src/test/scala/org/scalactic/anyvals/PosZFiniteFloatSpec.scala
Auto-merging scalactic-test/src/test/scala/org/scalactic/anyvals/PosIntSpec.scala
Auto-merging scalactic-test/src/test/scala/org/scalactic/anyvals/PosFiniteDoubleSpec.scala
Auto-merging scalactic-test/src/test/scala/org/scalactic/anyvals/PosDoubleSpec.scala
Auto-merging scalactic-test/src/test/scala/org/scalactic/anyvals/NonZeroLongSpec.scala
Auto-merging scalactic-test/src/test/scala/org/scalactic/anyvals/NonZeroIntSpec.scala
Auto-merging scalactic-test/src/test/scala/org/scalactic/anyvals/NonZeroFiniteFloatSpec.scala
Auto-merging scalactic-test/src/test/scala/org/scalactic/anyvals/NegZIntSpec.scala
Auto-merging scalactic-test/src/test/scala/org/scalactic/anyvals/NegZFiniteFloatSpec.scala
Auto-merging scalactic-test/src/test/scala/org/scalactic/anyvals/NegIntSpec.scala
Auto-merging scalactic-test/src/test/scala/org/scalactic/anyvals/NegFiniteDoubleSpec.scala
Auto-merging scalactic-test/src/test/scala/org/scalactic/anyvals/NegDoubleSpec.scala
Auto-merging project/scalatest.scala
CONFLICT (content): Merge conflict in project/scalatest.scala
Auto-merging project/GenTable.scala
CONFLICT (modify/delete): project/GenSafeStyles.scala deleted in HEAD and modified in d461f18d428fc35ddf6653a2ed83cc2db67d98f3. Version d461f18d428fc35ddf6653a2ed83cc2db67d98f3 of project/GenSafeStyles.scala left in tree.
Auto-merging project/GenMatchers.scala
CONFLICT (content): Merge conflict in project/GenMatchers.scala
Auto-merging project/GenInspectors.scala
CONFLICT (content): Merge conflict in project/GenInspectors.scala
Auto-merging project/GenGen.scala
CONFLICT (content): Merge conflict in project/GenGen.scala
Automatic merge failed; fix conflicts and then commit the result.

Thanks.

Bill

**Comment by cheeseng** [comment]
PR submitted here: 

https://github.com/scalatest/scalatest/pull/1242
