### ISSUE TITLE
Upgrade to sbt 1.0?

### ISSUE THREAD

**Issue by Duhemm** [scalatest/scalatest#1244]
Hey,

(I didn't find a better place to post this, sorry for polluting the issue tracker if this is not the right place)

I am working on upgrading Dotty to sbt 1.0, which means that I am also upgrading all the projects of our community build to sbt 1.0. In case you're interested, here's my attempt at porting scalatest's build to sbt 1.0.3: https://github.com/dotty-staging/scalatest/commit/b2772ea1a24d662dec2df54dee72451107773c11
My goal was to keep the overall diff as small as possible.

Everything seems to work on my side. I don't know how much our fork has diverged from the base, but I hope this will be a useful starting point in case you decide to migrate.

**Comment by cheeseng** [comment]
@Duhemm One blocker that I can see currently is that sbt 1.0 does not seems to work with JDK6, we're still building releases for Scala 2.10 and 2.11 using JDK6 as JDK6 is supported in Scala 2.10 and 2.11.

**Comment by SethTisue** [comment]
I would suggest dropping JDK 6 and 7 support. anyone who's stuck on a really old JDK can probably cope with remaining in ScalaTest 3.0.5 indefinitely.

**Comment by ekrich** [comment]
@cheeseng Any thoughts on upgrading sbt? This would be a big help to downstream projects so they could drop sbt 0.13.x support. 

I think @SethTisue 's suggestion is good. 

Most projects stuck on Java 6 or 7 are probably minimum maintenance support.

**Comment by dwijnand** [comment]
Also, you can run sbt 1 on JDK 8 and still build cross-build libraries in Scala 2.10 and 2.11 that only use JDK 6, you just need to make sure/check that you're not linking to any APIs in later versions of the java standard library.

**Comment by bvenners** [comment]
We decided to drop 2.10 in ScalaTest 3.1 and also support 2.11 only on JDK8. @dwijnand that's true, hard to get right in practice. Anyone still on JDK6 will be able to use the 3.0.x series. We can make another release there if we need to down the road.

**Comment by ekrich** [comment]
@bvenners So does that mean that you plan to upgrade to sbt `1.x` because Scala Test was one of the reasons given for not upgrading in Scala Native (see above).  Currently, we have experimental support but could we expect more support in the future? https://github.com/scalatest/scalatest/issues/1112
