### ISSUE TITLE
Please make a PR to merge 3.1.x into 3.2.x

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest#1248]
Hi Chee Seng,

After the dotty cherry pick PR and a few others that I merged into 3.1.x, I get quite a few conflicts in GenGen.scala when I pull 3.1.x into 3.2.x. Please submit a PR that resolves those conflicts.

Thanks.

Bill

**Comment by cheeseng** [comment]
Fixed in the following PR: 

https://github.com/scalatest/scalatest/pull/1250

**Comment by cheeseng** [comment]
After merging in the following PR:

https://github.com/scalatest/scalatest/pull/1250

It would be good to close and re-open this PR to trigger travis build for this PR.

**Comment by bvenners** [comment]
This is merged. I tested it locally, so no need to trigger travis again.
