### ISSUE TITLE
Please make a PR for MiMa against 3.1.x

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest#1266]
Hi Chee Seng,

I merged this into 3.0.x:

https://github.com/scalatest/scalatest/pull/1158

But when I try to pull to 3.1.x, again we get conflicts. Can you make a new PR for adding MiMa to 3.1.x? Once I merge that in I'll also pull it to 3.2.x.

Thanks.

Bill

**Comment by cheeseng** [comment]
Completed in the following PR: 

https://github.com/scalatest/scalatest/pull/1269

**Comment by bvenners** [comment]
Next step for this one: https://github.com/scalatest/scalatest/issues/1271

OK got it right this time. So closing this since it is done.
