### ISSUE TITLE
Please enhance Eventually to handle Future's specially

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest#1267]
Hi Chee Seng,

We added Ultimately earlier this year to 3.1.x and 3.2.x to provide an Eventually-like syntax but with Futures. Ultimately required a Future[T], and in a non-blocking manner retried until a timeout. If the timeout was reached, the Future would fail.

https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/concurrent/Eventually.scala

https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/concurrent/Ultimately.scala

Please enhance Eventually so that it uses a typeclass, perhaps org.scalatest.enablers.Retrying[T], where T is the result type of the block passed to eventually, to implement the behavior of the eventually methods. If the result type of the block passed to eventually is a Future[Assertion], it should have the behavior we put into Ultimately. Otherwise, it should have the behavior that eventually currently has.

This is a bit more strict than Ultimately's current implementation,. which allows any Future[T] not just Future[Assertion]. I'm thinking I'd rather start very specific and just change the eventually behavior for result type Future[Assertion] only, because we are changing this in a potentially breaking way. It is unlikely anyone actually would have written a block that ends in Future[Assertion], unless they thought that would work the way it will after this enhancement.

Also in this PR, please remove Ultimately. Please make the PR against 3.1.x (after merging, I'll pull that into 3.2.x.)

Thanks.

Bill

**Comment by cheeseng** [comment]
Completed in the following PR: 

https://github.com/scalatest/scalatest/pull/1279

**Comment by bvenners** [comment]
This has been merged into 3.1.x and pulled into 3.2.x.
