### ISSUE TITLE
Please make a PR to fix pulling from 3.1.x into 3.2.x

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest#1268]
Hi Chee Seng,

After merging this cherry-picked commit from 3.2.x into 3.1.x:

https://github.com/scalatest/scalatest/pull/1043

We are no longer able to cleanly pull from 3.1.x into 3.2.x. Please make a PR to fix that.

Thanks.

Bill

**Comment by cheeseng** [comment]
Fixed in the following PR: 

https://github.com/scalatest/scalatest/pull/1270
