### ISSUE TITLE
Please make a PR to pull 3.1.x MiMa changes to 3.2.x

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest#1271]
Hi Chee Seng,

After merging PR #1269 into 3.1.x, a pull from 3.1.x to 3.2.x gets a very small conflict in scalatest.scala. I can guess how to fix it, but I'd rather you take a look and be sure. Please make a PR to resolve that conflict pulling 3.1.x into 3.2.x.

Thanks.

Bill

**Comment by bvenners** [comment]
Next step for this one: https://github.com/scalatest/scalatest/issues/1271

But I'll close this since it is done.

**Comment by bvenners** [comment]
Duh, this is 1271! Reopening.

**Comment by cheeseng** [comment]
Fixed in the following PR: 

https://github.com/scalatest/scalatest/pull/1273
