### ISSUE TITLE
Scala SuperSafe not found for Scala 2.12.5

### ISSUE THREAD

**Issue by BalmungSan** [scalatest/scalatest#1344]
Trying to use the **Artima SuperSafe Scala Compiler _1.1.5_** with **Scala _2.12.5_** and **SBT _1.1.1_** results in an unresolved dependency `com.artima.supersafe#supersafe_2.12.5;1.1.5: not found`.

**Comment by bvenners** [comment]
Yes, we haven't deployed that yet. Will release it and post here once that's ready.

**Comment by BalmungSan** [comment]
Thanks

**Comment by bvenners** [comment]
@BalmungSan We have deployed SuperSafe for 2.12.5:

http://repo.artima.com/releases/com/artima/supersafe/supersafe_2.12.5/

Please let us know if you have any trouble with the release.

Thanks.

Bill
