### ISSUE TITLE
pending will always result in pending state even if there are assertions that fail.

### ISSUE THREAD

**Issue by dhinojosa** [scalatest/scalatest#1354]
I am using ScalaTest for Scala and Akka training.  It would be nice to have assertions in place and pending at the same time. That way it will also show pending even if the assertions/matchers fail.  At the moment, this test fails because of I have 4 assertions that fail eventhough I have marked this test as `pending`  Not even sure that is possible.

```
    it("""Lab 2: Recreate the above but be sure that it is done
        |in a tail-recursive manner""".stripMargin) {
      def replicate[A](count: Int, elem: A): List[A] = {
        ???
      }

      replicate(0, "Whoa") should be(List())
      replicate(1, "Whoa") should be(List("Whoa"))
      replicate(2, "Whoa") should be(List("Whoa", "Whoa"))
      replicate(5, "Whoa") should
        be(List("Whoa", "Whoa", "Whoa", "Whoa", "Whoa"))

      pending
    }
```

**Comment by bvenners** [comment]
Put pending first, above the assertions, and you'll get a pending test instead of a failed one.
