### ISSUE TITLE
should be (???) doesn't compile

### ISSUE THREAD

**Issue by dhinojosa** [scalatest/scalatest#1355]
Doing scala and Akka trainings, I would like to use `???` as a stand-in for the matcher and have it compile.

```
val result = ....
result should be (???)
```

 I don't necessarily need to run it, but if it does run it should still result in a `NotImplementedError`, it just seems like a perfect stand-in for any student to fill in the answer and remove `pending` to see if they're right. It also seems perfect as a stand-in for any testers.

**Comment by dhinojosa** [comment]
Didn't know, that putting `pending` up front made the whole thing pending.  Therefore, this should be closed too, unless you find value keeping it open

**Comment by bvenners** [comment]
OK. Sure. Closing.
