### ISSUE TITLE
Travis broken for Java 6

### ISSUE THREAD

**Issue by ashawley** [scalatest/scalatest#1380]
Looks like the Lightbend folks [reported it and found a solution](https://github.com/travis-ci/travis-ci/issues/9713#issuecomment-395934637).  For an example fix, see scala/scala-parser-combinators#156.

**Comment by fancywriter** [comment]
This is not the only issue with java 6.
Travis workaround works, however, maven central has changed TLS version and java 6 doesn't support it (at least version is used in travis, it is likely that latest jdk-6 supports is, but in travis it is not latest), java 7 and java 8 support it.

Details here https://central.sonatype.org/articles/2018/May/04/discontinued-support-for-tlsv11-and-below/

Possible workarounds
 - disable maven central (not sure if it's possible, can SBT do this, and does it have dependencies which can't be found on mirrors which support TLSv1 ?)
 - switch from maven central from https to http (not good also) - have no idea how to do it in SBT
 - forget about java-6, it's 2018 today! is it really needed to be supported??? java 8 is stable enough
 - make travis to use latest build of JDK-6 - should work (but couldn't test it) and this is probably the best option

**Comment by ashawley** [comment]
Indeed, openjdk6 doesn't support TLS 1.2, but Oracle JDK has shipped with TLS 1.2 since July-2016.

Option (2), switching to HTTP, seems like the only option for Travis for now.
