### ISSUE TITLE
Can't generate Scaladoc in SBT with SuperSafe 1.1.6 plugin

### ISSUE THREAD

**Issue by MichaelJAllen** [scalatest/scalatest#1381]
I've just started using the _SuperSafe_ SBT plugin (v1.1.6), and it's extremely useful! Thanks for yet another great tool!

Unfortunately, I've discovered that it breaks generation of _Scaladoc_ in _SBT_:

```
$ sbt doc
[info] Loading settings from PGP.sbt,Scoverage.sbt,Scalastyle.sbt,Release.sbt,SuperSafe.sbt ...
[info] Loading project definition from /my/app/project
[info] Loading settings from MyApp.sbt,Version.sbt ...
[info] Set current project to My App (in build file:/my/app/)
[info] Main Scala API documentation to /my/app/target/scala-2.12/api...
[error] dropping dependency on node with no phase object: refchecks
[info] No documentation generated with unsuccessful compiler run
[error] one error found
[error] (Compile / doc) Scaladoc generation failed
[error] Total time: 0 s, completed Jun 12, 2018 6:31:18 PM
```

It took me a while to figure out what was happening, but if I disable the _SuperSafe_ plugin, then I'm able to process my _Scaladoc_ without any problem.

Unfortunately, this affects a pretty large project. I'll try to create a smaller example that illustrates the problem. (I'm guessing it shouldn't be too hard, as - according to _Scaladoc_'s `-verbose` option - I don't seem to even get as far as processing source files.)

In case it's relevant, I'm also using _SBT_ v1.1.6 and _Scala_ v2.12.6.

**Comment by MichaelJAllen** [comment]
@cheeseng Why did you close this issue? Has it been fixed? Could you not reproduce the problem? Is it a waste of time reporting bugs?

**Comment by cheeseng** [comment]
@MichaelJAllen Sorry, somehow I clicked the closed button accidentally, I was just reading it and going back into the code looking for clue, I'll reopen it.

**Comment by cheeseng** [comment]
Indeed, I think I found the problem, supersafe plugin's phase is set to be after refchecks, but that's does not exists in doc task, I am working out the solution and shall release 1.1.7 to remedy it.

Sorry again for the accidentally close!

**Comment by MichaelJAllen** [comment]
I thought it might be something like that. ;-) Thanks for looking into it!

**Comment by MichaelJAllen** [comment]
Thanks! Great stuff! I'll look forward to using it! Thanks for your help!

**Comment by cheeseng** [comment]
@MichaelJAllen FYI SuperSafe 1.1.7 is already out, you may want to try to see if it fixes your issue.

Thanks.

**Comment by MichaelJAllen** [comment]
@cheeseng Sorry for the delay in getting back to you. I've just checked the 1.1.7 release, and this issue no longer occurs. Thanks for fixing this!
