### ISSUE TITLE
GeneratorDrivenPropertyChecks doesn't work with AsyncFlatSpec

### ISSUE THREAD

**Issue by Daenyth** [scalatest/scalatest#1387]
`forAll` wants the code to return `Unit` but in my async test it returns `Future[Assertion]`

What's the right way to test this? For now I'm using the workaround of blocking to sleep inside the test, which I don't love

**Comment by LeifW** [comment]
Duplicate of https://github.com/scalatest/scalatest/issues/1370 ?
