### ISSUE TITLE
Support Partial Unification for 3.1.x

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest#1402]
Hi Chee Seng,

I merged in PR https://github.com/scalatest/scalatest/issues/1165 into 3.0.x.

Please submit a PR to support this in 3.1.x.

Thanks.

Bill

**Comment by cheeseng** [comment]
PR submitted: 

https://github.com/scalatest/scalatest/pull/1403

**Comment by bvenners** [comment]
Merged into 3.1.x and pulled into 3.2.x.
