### ISSUE TITLE
Scala.js 1.0.0-M5 support

### ISSUE THREAD

**Issue by Starzu** [scalatest/scalatest#1411]
Unfortunately the new release  is not binary compatible with the previous 1.0.0-Mx releases. 

Release notes: http://www.scala-js.org/news/2018/08/13/announcing-scalajs-1.0.0-M5/

Probably you can close #1178 and #1299 - the version for Scala.js 1.0.0-M3 is already released.

**Comment by cheeseng** [comment]
@Starzu We have released for 1.0.0-M3 in 3.0.6-SNAP5, but unfortunately for 1.0.0-M5 we are blocked by scalacheck release.

**Comment by marcospereira** [comment]
This is probably not relevant anymore since scala.js 1.0.0 was released, and also, support for 1.0.0-RC2 was already published. See https://github.com/scalatest/scalatest/pull/1742.
