### ISSUE TITLE
SuiteAborted must not assume that message is non-null

### ISSUE THREAD

**Issue by danile42** [scalatest/scalatest#1445]
When a org.scalatest.events.SuiteAborted event is created due to an exception that is thrown during the test, it cannot be assumed that the message coming from this exception is not null, because null is a valid value as documented in the JDK docs: "the detail message string of this Throwable instance (which may be null)".

Currently, ScalaTest (3.0.5) fails in this case with a NullArgumentException, the original exception becomes invisible.

Maybe a synthetic message has to be created in this case instead.

**Comment by shawjef3** [comment]
I created #2236 to fix this. I verified it fixes the code that created the above stack trace.

**Comment by bvenners** [comment]
Fixed by https://github.com/scalatest/scalatest/pull/2236.
