### ISSUE TITLE
SuperSafe for Scala 2.12.8

### ISSUE THREAD

**Issue by mwz** [scalatest/scalatest#1461]
Hi, would it be possible to make a release of SuperSafe for Scala 2.12.8?

**Comment by cheeseng** [comment]
@mwz I'll be working on it today.

**Comment by bvenners** [comment]
Sorry for the delay getting it deployed. This is deployed live now, SuperSafe version 1.1.7.

http://repo.artima.com/releases/com/artima/supersafe/supersafe_2.12.8/
