### ISSUE TITLE
Is the 3.0.6 release tagged somewhere?

### ISSUE THREAD

**Issue by SethTisue** [scalatest/scalatest#1540]
I see the JARs on Maven Central. wondering what's changed

**Comment by bvenners** [comment]
I just merged a PR that the release included. So 3.0.x currently is what is in 3.0.6. Chee Seng will be making a tag as soon as he gets to it.

**Comment by cheeseng** [comment]
@SethTisue I just created the release here: 

https://github.com/scalatest/scalatest/releases/tag/release-3.0.6

with the release note, sorry for the delay.

**Comment by SethTisue** [comment]
no worries, thanks!
