### ISSUE TITLE
Move path traits to module packages; deprecate existing names

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest#1613]
Hi Chee Seng,

In 3.1.x, please move: 

org.scalatest.path.FunSpec to org.scalatest.funspec.PathAnyFunSpec
org.scalatest.path.FunSpecLike to org.scalatest.funspec.PathAnyFunSpecLike
org.scalatest.path.FreeSpec to org.scalatest.funspec.PathAnyFreeSpec
org.scalatest.path.FreeSpecLike to org.scalatest.funspec.PathAnyFreeSpecLike

And deprecate the old names. 

Thanks.

Bill

**Comment by cheeseng** [comment]
Hi @bvenners , 

I made the refactor and submitted the following PR: 

https://github.com/scalatest/scalatest/pull/1634

But unfortunately I just notice the class names that you requested includes the 'Any' word, which my current PR doesn't, I'll make the tweak tomorrow.

**Comment by bvenners** [comment]
Merged. Tnx.
