### ISSUE TITLE
Add deprecated versions of old anyvals Orderings

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest#1629]
Implicit `Ordering`s for numeric `anyvals` have all been renamed to `ordering`. Please put in a deprecated non-implicit method with the old name. For example, on `PosDouble` the implicit `Ordering` was previously called `posDoubleOrd`.

**Comment by cheeseng** [comment]
Hi @bvenners fyi I submitted the following PR for this: 

https://github.com/scalatest/scalatest/pull/1641

**Comment by bvenners** [comment]
This is complete.
