### ISSUE TITLE
v3.0.8 scalajs-1.0.0-M8 release was only published for Scala 2.13

### ISSUE THREAD

**Issue by fdietze** [scalatest/scalatest#1640]
versions for 2.11 or 2.12 were not published...

See: https://travis-ci.org/fdietze/colorado/builds/560235793

**Comment by cheeseng** [comment]
@fdietze Unfortunately we can't publish for scalajs 1.0.0-M8 without scalacheck publishing it: 

https://mvnrepository.com/artifact/org.scalacheck/scalacheck

**Comment by SethTisue** [comment]
ticket on that is https://github.com/typelevel/scalacheck/issues/496
