### ISSUE TITLE
PrivateMethodTester cannot find methods if they're declared like `def f: A => B = {...}`

### ISSUE THREAD

**Issue by tugh** [scalatest/scalatest#1649]
I have a method in an Object which is declared like this:
```scala
private def f: Int => Int = (a: Int) => a + 1
```

When I try to use invokePrivate my test will fail with this message: `Can't find a private method named: f`

The solution is simple though. If I declare the method like below everything works fine:
```scala
private def f(a: Int): Int = a + 1
```

I cannot think of the reason why the first declaration does not work for PrivateMethodTester. Does anyone have an idea?

**Comment by vincentdehaan** [comment]
This is actually quite logical if you consider how these two functions are represented by the JVM. Consider:

```scala
object Test {
  private def f: Int => Int = (a: Int) => a + 1
  private def g(a: Int): Int = a + 1
}
```

Now run `javap -p Test$` in the target directory:

```
javap -p Test$
Compiled from "Test.scala"
public final class Test$ {
  public static final Test$ MODULE$;
  public static {};
  private scala.Function1<java.lang.Object, java.lang.Object> f();
  private int g(int);
  public static final int $anonfun$f$1(int);
  private Test$();
  private static java.lang.Object $deserializeLambda$(java.lang.invoke.SerializedLambda);
}
```
You can see that while `g` is (as you would expect) a method taking one argument and returning an integer, `f` is a method taking zero arguments and returning a `Function1`.

We can test both `f` and `g` using `invokePrivate`, but for `f`, we need a bit more syntax:

```scala
assert(Test.invokePrivate(PrivateMethod[Int => Int]('f)())(7) == 8)
assert(Test.invokePrivate(PrivateMethod[Int]('g)(7)) == 8)
```

I would say this issue may be closed.
