### ISSUE TITLE
Report value of other side if a test using EitherValues is not the expected side

### ISSUE THREAD

**Issue by Mahoney** [scalatest/scalatest#1650]
At the moment if you mix in `EitherValues` and it is the wrong side:
```scala
test("either") {
  val either: Either[String, Int] = Left("Failed because 1 is not even")
  either.right.value mustBe 1
}
```
the message is:
`The Either on which right.value was invoked was not defined as a Right.`

It would be easier to understand a test failure if it were:
`The Either on which right.value was invoked was a Left with value "Failed because 1 is not even"`

**Comment by Mahoney** [comment]
Raised https://github.com/scalatest/scalatest/pull/1738

**Comment by jroper** [comment]
Agree, the only reason I wanted to use `EitherValues` was so that I didn't need to write the boilerplate to display what was on the left when treating it as a right, without this `EitherValues` seems to be next to useless.

**Comment by bvenners** [comment]
merged. Tnx for the PR!
