### ISSUE TITLE
Cannot use SuperSafe with Scala 2.12.9

### ISSUE THREAD

**Issue by MichaelJAllen** [scalatest/scalatest#1680]
There doesn't appear to be a _Scala_ 2.12.9-targeted artifact available for _SuperSafe_ 1.1.7, so it's not currently possible to use it with this new _Scala_ release (released on Aug 5th).

I'm seeing the following trying to perform a build:

```
[warn] ==== Artima Maven Repository: tried
[warn]   http://repo.artima.com/releases/com/artima/supersafe/supersafe_2.12.9/1.1.7/supersafe_2.12.9-1.1.7.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.artima.supersafe#supersafe_2.12.9;1.1.7: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.artima.supersafe:supersafe_2.12.9:1.1.7 (Defaults.scala#L3331)
```

Thanks for all your great work!

**Comment by cheeseng** [comment]
@MichaelJAllen I'll release for 2.12.9 today, sorry for the inconvenience caused.

**Comment by MichaelJAllen** [comment]
Hey, that was hardly any inconvenience at all! Thanks very much! I'll keep an eye out for it...

**Comment by cheeseng** [comment]
@MichaelJAllen fyi @bvenners has deployed SuperSafe 1.1.8 that includes support for Scala 2.13.0 and 2.12.9, can you try to see if it works for you?

Thank you.

**Comment by MichaelJAllen** [comment]
@cheeseng @bvenners Works great! Thanks for all your efforts!
