### ISSUE TITLE
Issue with SuperSafe and shouldBe empty matchers

### ISSUE THREAD

**Issue by mwz** [scalatest/scalatest#1732]
Hello, I'm upgrading scalatest to 3.1.0 and I've just experienced the following issue with SuperSafe (sbtplugin 1.1.8) and the `shouldBe empty` matchers:

>[Artima SuperSafe] Values of type List[Int] and org.scalatest.matchers.dsl.EmptyWord may not be compared for equality with ScalaTest's shouldBe matcher syntax.

and another one

>[Artima SuperSafe] Values of type Option[Int] and org.scalatest.matchers.dsl.DefinedWord may not be compared for equality with ScalaTest's shouldBe matcher syntax.

Example code resulting in this error:

```scala
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

class Test extends AnyFlatSpec with Matchers {
  it should "just work" in {
    List.empty shouldBe empty
    Option(1) shouldBe defined
  }
}
```

Am I missing something obvious here or is this a bug? I couldn't find anything in the docs and release notes that would mention anything related.

Any help would be much appreciated.

I've noticed there was a similar issue to this in #1328 last year, so perhaps this is a regression?

**Comment by cheeseng** [comment]
This is due to the refactoring of the code we did in 3.1.0 release, we're working hard on SuperSafe 1.2.0 that will be compatible with ScalaTest 3.1.0.

Sorry for the inconvenient caused.

**Comment by mwz** [comment]
The new supersafe `1.1.9` has fixed the problem for me, thanks for releasing a new version.
