### ISSUE TITLE
Support for "expected failure"

### ISSUE THREAD

**Issue by max-leuthaeuser** [scalatest/scalatest#1740]
A nice way of writing known-to-fail tests would be a new verb (in addition to the already existing `should` or `ignore`) that permits to write correct aspirations, and still alerts us whenever the observed behavior changes (and then we would just move the test from "known shortcoming" to "regression test" and be happy).

Unfortunately, scalatest does not provide such a verb, i.e. an analogue to https://docs.python.org/3/library/unittest.html#unittest.expectedFailure

"ignore" skips the test during evaluation and doesn't alert us when expected and actual behavior diverge.

Is there a workaround? Is adding such a new verb working the exact way as Python unittest expectedFailure annotation does doable?

**Comment by bvenners** [comment]
@max-leuthaeuser I think you're looking for pendingUntilFixed, which is in Assertions:

http://doc.scalatest.org/3.1.0/org/scalatest/Assertions.html

If that is indeed what you're after please go ahead and close the ticket. Tnx.

**Comment by max-leuthaeuser** [comment]
Great, thanks! I guess I overlooked that.
