### ISSUE TITLE
scalatest native not released for 3.1.0

### ISSUE THREAD

**Issue by regadas** [scalatest/scalatest#1741]
scalatest native is sill on `3.1.0-RC3` is that intended?

**Comment by bvenners** [comment]
@regadas Is this what you're looking for:

https://mvnrepository.com/artifact/org.scalatest/scalatest_native0.4.0-M2_2.11/3.1.0

If so, please close the ticket.

Thanks.

**Comment by regadas** [comment]
Hi @bvenners thanks for the quick reply! in fact it is; somehow I missed it! Thank you!
