### ISSUE TITLE
Mockito documentation out of date

### ISSUE THREAD

**Issue by kag0** [scalatest/scalatest#1789]
http://www.scalatest.org/user_guide/testing_with_mock_objects links to http://doc.scalatest.org/3.1.1/#org.scalatest.mock.MockitoSugar which hasn't existed for a while. 
It used to be at org.scalatestplus.mockito.MockitoSugar, but I see that that's not there anymore either. 

The documentation could do with an update to reflect the current version.

**Comment by heyestom** [comment]
Just an FYI for anyone like me who was looking for where MockitoSugar has been moved.  It is now part of scalatestplus: org.scalatestplus.mockito.MockitoSugar

https://mvnrepository.com/artifact/org.scalatestplus/scalatestplus-mockito

**Comment by darrenhaken** [comment]
@heyestom thanks for sharing I was stumped by this for quite some time until I spotted this. Are there plans to update the docs?

**Comment by solarmosaic-kflorence** [comment]
It links here now: https://www.scalatest.org/plus/mockito
I think this can be closed

**Comment by kag0** [comment]
Nice 👍
