### ISSUE TITLE
Scala 3.1.1 is missing trait AssertionsForJUnit?

### ISSUE THREAD

**Issue by sinwe** [scalatest/scalatest#1793]
Latest scalatest 3.1.1 seem to be missing trait `AssertionsForJUnit`?
Is it intentionally? If yes, what's the alternative? Is it moved? If yes, moved to which package?

Version 3.0.5 still contained the trait.

**Comment by tomnis** [comment]
hi @sinwe maybe you figured it out already, but looks like this was moved to `scalatestplus.junit`
https://mvnrepository.com/artifact/org.scalatestplus/junit-4-12_2.12

**Comment by sinwe** [comment]
Hi @tomnis,
Yes I figured it out already. Thanks for the info anyway.
It was not documented anywhere though.

I'll close this ticket.
