### ISSUE TITLE
Release for Dotty 0.23.0-RC1

### ISSUE THREAD

**Issue by adamw** [scalatest/scalatest#1802]
Currently 3.1.1 is released for 0.22.0-RC1.

Would be great to have the latest version supported. Thanks! :)

**Comment by adamw** [comment]
Although it seems we'll have to wait until 0.24 for mixins like `BeforeAndAfterAll` to work (https://github.com/lampepfl/dotty/issues/8582)

**Comment by adamw** [comment]
But, for anybody also looking for reasons for `java.lang.AbstractMethodError: 'org.scalatest.Status org.scalatest.SuiteMixin.run(scala.Option, org.scalatest.Args)'`, a work-around is here: https://github.com/ohze/akka/commit/5617228a2388368cbd2b9384e74a6eb7edbc8d69

Thanks @giabao :)

**Comment by cheeseng** [comment]
@adamw Unfortunately, it seems like we can't even build with Dotty 0.23.0-RC1, it fails with errors like this: 

```
[error] -- [E040] Syntax Error: /home/cheeseng/git/scalatest/scalactic.dotty/src/main/scala/org/scalactic/Requirements.scala:234:31 
[error] 234 |    import qctx.tasty.{_, given}
[error]     |                               ^
[error]     |                               an identifier expected, but '}' found
```

Not sure what's wrong, we probably need to update our source to build with dotty 0.23.0-RC1.

**Comment by adamw** [comment]
ah ... `given` is now a keyword, that's probably the problem. Thanks for checking! :)

**Comment by cheeseng** [comment]
@adamw By the way, I tried 0.22.0 also, and it worked, do you think it will be useful to release for 0.22.0 in addition to the current build for 0.22.0-RC1?

**Comment by adamw** [comment]
Oh, I didn't know there was a non-RC 0.22 :) I guess so, always a bit more recent version. Though if it's any trouble, I suppose I would instead wait for the fixes needed for 0.23 :)

**Comment by cheeseng** [comment]
@adamw It seems like the version I published with Dotty 0.22.0-RC1 has already taken the place: 

https://mvnrepository.com/artifact/org.scalactic/scalactic_0.22/3.1.1
https://mvnrepository.com/artifact/org.scalatest/scalatest_0.22/3.1.1

Unless we're ready to release 3.1.2, which I don't think we have any currently.  We probably shall wait for the fix in 0.23 or 0.24 then.  :)

**Comment by adamw** [comment]
Thanks! I'll use 0.22, somehow I missed that :)

**Comment by SethTisue** [comment]
this should probably be closed. (#1138 remains open)

**Comment by adamw** [comment]
@SethTisue yes, even better, there's a release for 0.23.0 and 0.24.0 (`3.1.2`)
