### ISSUE TITLE
SuperSafe support for Scala 2.13.2

### ISSUE THREAD

**Issue by Facsimiler** [scalatest/scalatest#1807]
There is currently no build of _SuperSafe_ available for the newly released _Scala_ 2.13.2. Can you publish a build for that?

Thanks!

**Comment by bvenners** [comment]
@Facsimiler Actually there is, 1.1.10. We are in the process of publishing an update to the site: https://github.com/scalatest/scalatest-website/pull/133

**Comment by Facsimiler** [comment]
@bvenners Wow! That's what I call a quick response! Thanks, Bill!

**Comment by Facsimiler** [comment]
@bvenners Actually, there is no _SuperSafe_ 1.1.10 build for _Scala_ 2.13.2 currently available, either in `https://repo.artima.com/releases/com/artima/supersafe/` or in _Maven Central_. Is it in the process of being published?
