### ISSUE TITLE
https://www.scalatest.org/ responds with 502 Bad Gateway

### ISSUE THREAD

**Issue by smrnv** [scalatest/scalatest#1814]

**Comment by adarro** [comment]
Eep! Just noticed the same thing.  https://www.isitdownrightnow.com/scalatest.org.html confirms.

**Comment by tOverney** [comment]
Seems back online, I can now access https://www.scalatest.org/

**Comment by adarro** [comment]
agreed.

**Comment by smrnv** [comment]
Yes, now it works, let's close this issue
