### ISSUE TITLE
Selenium DSL missing for 3.1.2

### ISSUE THREAD

**Issue by atooni** [scalatest/scalatest#1816]
Helllo,

we have just tried out scalatest 3.1.2 and it seems that the selenium DSL is missing. 
We have instaleld scalatest and selenium as dependencies. 
Are we missing something  ?

**Comment by cheeseng** [comment]
@atooni I believe you'll need to add the following module: 

```
libraryDependencies += "org.scalatestplus" %% "selenium-3-141" % "3.1.2.0" % "test"
```

ScalaTest+Selenium is now a separate module.

**Comment by atooni** [comment]
Hi. yes that has worked. It seems to be missing from scalatest's documentation though.

**Comment by atooni** [comment]
FYI: I have created https://github.com/scalatest/scalatest-website/pull/138 to amend the documentation.
