### ISSUE TITLE
Await.result blocks forever in before/after using AsyncFlatSpec

### ISSUE THREAD

**Issue by reugn** [scalatest/scalatest#1828]
scalatest version: 3.1.2
```scala
before {
  Await.result(Future{1}, Duration.Inf)
}
```
Will block forever using `AsyncFlatSpec`.

**Comment by johnduffell** [comment]
yes you shouldn't Await in your tests, as that blocks the (only) thread in the execution context and therefore hangs the test.

**Comment by reugn** [comment]
@johnduffell what if I need to run blocking operation before each async test?

**Comment by bvenners** [comment]
@reugn You could change the ExecutionContext. The default ExecutionContext is single-threaded. Info on that is here:

**Comment by reugn** [comment]
@bvenners thanks, that worked.
