### ISSUE TITLE
Is 3.2.0 missing GeneratorDrivenPropertyChecks?

### ISSUE THREAD

**Issue by danielyli** [scalatest/scalatest#1836]
I can’t find `GeneratorDrivenPropertyChecks` in the [ScalaTest 3.2.0 API documentation](https://www.scalatest.org/scaladoc/3.2.0/), and attempting to import `org.scalatest.prop.GeneratorDrivenPropertyChecks` given an import error.

Has it moved elsewhere?

**Comment by bvenners** [comment]
Sorry for the confusion. Its old name was deprecated in 3.0.8 and it was moved to a scalatestplus module in 3.1.0. Its new home is org.scalatestplus.scalacheck. I did not yet have a chance to complete my updating of the ST.org user guide. Will continue working on that this weekend. You can find more info here:

https://github.com/scalatest/scalatestplus-scalacheck

**Comment by danielyli** [comment]
Thanks!
