### ISSUE TITLE
genSortedTests fails with FileNotFoundException on 3.2.x-new branch

### ISSUE THREAD

**Issue by SethTisue** [scalatest/scalatest#1851]
reproduction steps:

```
hub clone scalatest/scalatest
cd scalatest
git checkout 3.2.x-new
sbt
genSortedTests/test
```

result:

```
[error] stack trace is suppressed; run last genSortedTests / Test / managedSources for the full output
[error] (genSortedTests / Test / managedSources) java.io.FileNotFoundException: scalatest-test/src/test/scala/org/scalatest/ShouldBeSortedSpec.scala (No such file or directory)
```

This originally came up in the Scala 2.13 community build, over at https://github.com/scala/community-build/pull/1172 . Log: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1625/artifact/logs/scalatest-tests-build.log

**Comment by SethTisue** [comment]
`genContainsTests1` is also affected, maybe others as well

it looks like I'm expected to run `genGenTests/test` first...? that was necessary on 3.0 or 3.1, I don't think

**Comment by cheeseng** [comment]
@SethTisue I submitted a PR to fix this: 

https://github.com/scalatest/scalatest/pull/1853

Thanks for notifying!

**Comment by SethTisue** [comment]
working: https://github.com/scala/community-build/pull/1191 👍
