### ISSUE TITLE
scalatest 3.2.1 fails to print failed test cases in some scenarios

### ISSUE THREAD

**Issue by anilkumarmyla** [scalatest/scalatest#1876]
I don't have a reproduction case yet, but will work on it. Does not happen with 3.2.0. This is just to let others chime in here as well with their reproduction case if any

**Comment by mcanlas** [comment]
I think I'm also running into this issue.

Previously, my team was using 3.2.0, where I believe things were fine. Then we recently upgraded to 3.2.1 and noticed missing test output (even though all the tests were successful).

Wondering, was this patch #1842 introduced in 3.2.1 ?

**Comment by mcanlas** [comment]
Following the above scalatest issue hints that https://github.com/sbt/sbt/issues/5245 may be the root cause.

**Comment by etspaceman** [comment]
I also ran into this issue in a project that used a parallel testing strategy.

**Comment by cheeseng** [comment]
@etspaceman I clone scalacheck-faker repo to try reproduce the case, but when I tried to launch sbt in the project dir it shows: 

```
Conflicting collector combinations in option list; please refer to the release notes for the combinations allowed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Is there any additional steps required to build the project?

Cheers.

**Comment by etspaceman** [comment]
There are no special steps to building the project. This looks like you might be using a different java version?

**Comment by etspaceman** [comment]
It's possible that the `.jvmopts` in the project conflicts with the java version that you have installed:

https://github.com/etspaceman/scalacheck-faker/blob/master/.jvmopts

**Comment by cheeseng** [comment]
@etspaceman I am running sbt with jdk8, shall I use a different version?

**Comment by etspaceman** [comment]
The CI job for the repository uses JDK8 so I'm not sure why your personal machine is unable to build this:

https://github.com/etspaceman/scalacheck-faker/blob/master/.github/workflows/scala.yml#L17

**Comment by cheeseng** [comment]
@etspaceman Hmm, I am running oraclejdk8, I wonder if that matters?

```
cheeseng@cheeseng-RAVEN:~/git/scalacheck-faker$ java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
```

Building scalatest with sbt seems to work fine all the while though.

**Comment by etspaceman** [comment]
I use oraclejdk myself 😅 , so yeah I'm not sure here.

**Comment by etspaceman** [comment]
My guess is that you have some settings on your personal machine that are also sending in JVM options to your SBT shell. 

Perhaps just remove .jvmopts for your local build?

**Comment by cheeseng** [comment]
@etspaceman You're right!  I have SBT_OPTS set in my ~/.bashrc and that's conflicting with .jvmopts, I commentted out my SBT_OPTS and now it seems to work, thanks!

**Comment by cheeseng** [comment]
@etspaceman When I ran sbt test all tests passed, any tip which part of code I can tweak to see/reproduce the problem?

By the way, it's getting a bit late over here, I'll probably continue tomorrow.  :)

Thanks!

**Comment by etspaceman** [comment]
@cheeseng the tests pass but not all of them appear.

For a clear example you can try a specific test suite:

`sbt testOnly *FakerSpec_nl`

You'll see 168 tests pass but not all of them appear in the console. 

If you then checkout the master branch and do the same, you'll see all of the tests appear in the console.

**Comment by cheeseng** [comment]
@etspaceman Noted, I'll try your way, thank you very much!

**Comment by lfjallstrom** [comment]
We are seeing the same issue in two different projects with ScalaTest 3.2.1 and SBT 1.3.13 that not all successful test cases appear to the console even though they are being run. If we forward the output to stderr (using -e argument), all cases will appear. In this case SBT keeps logging some random looking test cases to stdout as well so the output is messy.

I'm not sure what details would help resolving this issue but I'm happy to provide more information if someone gives me pointers.

**Comment by cheeseng** [comment]
Hi all, fyi I submitted the following PR in attempt to fix this: 

https://github.com/scalatest/scalatest/pull/1878

I'll release a 3.2.2-M1 so that it is easier for you to test the fix.

Cheers.

**Comment by cheeseng** [comment]
Hi all, fyi I have released 3.2.2-M1, you can try to use it to see if it fixes your issue, thanks.

**Comment by anilkumarmyla** [comment]
3.2.2-M1 solves our issue, thanks @cheeseng for the quick fix

**Comment by lfjallstrom** [comment]
Seems to fix our issues too. Thank you @cheeseng for fixing this so quickly!

**Comment by pomadchin** [comment]
@cheeseng thanks! `3.2.2-M1` fixes my issues as well. I wish I could notice this issue earlier :/ I even prepared the whole project that constantly reproduces the behavior :/

**Comment by anilkumarmyla** [comment]
@cheeseng Given the severity of this bug, can we push for 3.2.2 to be released as soon as possilbe? do you have a timeline for 3.2.2 already set?

**Comment by cheeseng** [comment]
@anilkumarmyla I wanted to but has to include fixes for other reported issues also, commits included in the upcoming 3.2.2 here: 

https://github.com/scalatest/scalatest/pull/1878/commits

@lfjallstrom @anilkumarmyla @pomadchin I have adjusted the fix slightly and released 3.2.2-M2 together with other fixes, do you mind to double-check if M2 still work for you problem?

Cheers.

**Comment by lfjallstrom** [comment]
@cheeseng still works for us 👍

**Comment by pomadchin** [comment]
@cheeseng works for me as well :+1: you can also probably use [this](https://github.com/pomadchin/scalatest-it-print-issue) project as an indicator.

**Comment by bjhartin** [comment]
I noticed this problem when using the `testcontainers` library.  A minimal reproduction needed only to start the generic container and that caused the output to go missing under 3.2.1.  Rolling back to 3.0.5 fixed it, as did removal of `container.start()`.

3.2.2-M1 fixes it for me too.  Only commenting in case it helps someone else who is googling. :smile:

**Comment by anilkumarmyla** [comment]
I believe this is fixed, closing it. Feel free to reopen if not
