### ISSUE TITLE
SuperSafe support for Scala 2.13.4

### ISSUE THREAD

**Issue by Facsimiler** [scalatest/scalatest#1924]
[Scala 2.13.4 has now been released.](https://github.com/scala/scala/releases/tag/v2.13.4) Can you create a _SuperSafe_ release for this version of the _Scala_ compiler? Thanks!

**Comment by cheeseng** [comment]
@Facsimiler Fyi we just releasee SuperSafe 1.1.12 which includes build for Scala 2.13.4, thanks for the ping!

**Comment by Facsimiler** [comment]
@cheeseng Thanks for the update. However, I'm getting build errors. It appears there isn't a 1.1.12 release for the corresponding sbt plugin:

```
[error]   not found: https://repo.artima.com/releases/com/artima/supersafe/sbtplugin_2.12_1.0/1.1.12/sbtplugin-1.1.12.pom
```

**Comment by cheeseng** [comment]
@Facsimiler Sorry I left that out accidentally, it should be up now, sorry for the inconvenient caused.

**Comment by Facsimiler** [comment]
@cheeseng No worries. It's all working fine now, thanks!
