### ISSUE TITLE
Supersafe support for Scala 2.12.13

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [scalatest/scalatest#1963]
https://www.scala-lang.org/news/2.12.13

```
[error] sbt.librarymanagement.ResolveException: Error downloading com.artima.supersafe:supersafe_2.12.13:1.1.12
```

**Comment by cheeseng** [comment]
I'll work on the release today, thanks for reporting it!

**Comment by cheeseng** [comment]
@solarmosaic-kflorence Fyi build for Scala 2.12.13 is up.

**Comment by solarmosaic-kflorence** [comment]
Confirmed: http://repo.artima.com/releases/com/artima/supersafe/supersafe_2.12.13/1.1.12/ -- thanks!
