### ISSUE TITLE
[Scala3] typeChecks Behavior Change in 3.0.0-RC1

### ISSUE THREAD

**Issue by cheeseng** [scalatest/scalatest#1967]
@liufengyun @smarter @nicolasstucki  ScalaTest for Scala 3 is currently using scala.compiletime.testing.typeChecks in macro to support the following syntax like this: 

```
"PosZ(-1)" shouldNot compile
```

PosZ(-1) itself is a macro expansion that will check if the passed in argument is >=0, when fail it will raise an compiler error.

Prior to 3.0.0-RC1, the PosZ(-1) macro expansion will happen as expected during the 'shouldNot compile' macro and the above assertion will work, but this is now break in 3.0.0-RC1.  The same behavior is working also under the old Scala 2 macro.

Is there anything we can do to make it working again?  This has caused many of our tests failing now under Scala 3 build in 3.2.x-new after upgrade to Scala 3.0.0-RC1.

**Comment by smarter** [comment]
Have a look at the version of scalatest in our community build, you need to make the inline def transparent to have it run during typechecking now: https://github.com/dotty-staging/scalatest/commits/use-transparent-for-typeChecks

**Comment by cheeseng** [comment]
@smarter Thanks for the quick response, I did in this commit actually: 

https://github.com/scalatest/scalatest/pull/1966/commits/ca0c165b4200d51f6986932ffebd7b88b25abce8

which make the 'shouldNot compile' macro to work, but this problem is after the transparent fix, the 'nested' macro expansion does not seems to happen anymore, oh, or do I need to add 'transparent' to the 'nested' macro (in this case the PosZ(-1) macro) also?  When PosZ(-1) is not nested (use outside the shouldNot compile) the macro does work though.

**Comment by smarter** [comment]
I don't know enough about the macros involved here to say, was this not caught by our community build because this changed recently in scalatest?

**Comment by liufengyun** [comment]
> the 'nested' macro expansion does not seems to happen anymore,

This might be a bug. Could you check with a simple example of nested macros? If it does not work, please report a bug.

**Comment by cheeseng** [comment]
> I don't know enough about the macros involved here to say, was this not caught by our community build because this changed recently in scalatest?

@smarter Hmm, I don't think change in scalatest cause this problem, it still works with 3.0.0-M3.

> > the 'nested' macro expansion does not seems to happen anymore,
> 
> This might be a bug. Could you check with a simple example of nested macros? If it does not work, please report a bug.

Yes sure, I'll try to work out a minimal example for debugging.

**Comment by cheeseng** [comment]
@smarter @liufengyun The problem is fixed now in 3.0.0-RC2, we shall close this.

Thank you!
