### ISSUE TITLE
Scala3 RC2 is out!

### ISSUE THREAD

**Issue by bblfish** [scalatest/scalatest#1987]
I am moving a project to scala3 which depends on scalaz which has just released a version for RC2. Looking forward to scaltest release!

**Comment by bvenners** [comment]
@SethTisue @bblfish Great. We'll work on that tonight and if all goes well get it out the door

**Comment by bvenners** [comment]
@bblfish @SethTisue Almost got it out last night. Sonatype is complaining about a signature mismatch one one of the artifacts and won't close it. So we'll rebuild that one first thing tonight.

**Comment by bvenners** [comment]
@bblfish @SethTisue All artifacts are released except dotty-js, which Chee Seng is working on now. Version is 3.2.7.

**Comment by bblfish** [comment]
95 compile errors ahead of me ! :-)
