### ISSUE TITLE
Publish for Scala 3.0.0-RC3, please?

### ISSUE THREAD

**Issue by SethTisue** [scalatest/scalatest#2006]
it just hit Maven Central

Lars is working on publishing ScalaCheck right now. I'm working on publishing the Scala modules.

**Comment by bvenners** [comment]
@SethTisue Sure. Thanks for saying please, but we'd do it even without a please. I'll ask Chee Seng to work on that first thing when he gets started his tomorrow morning (our tonight).

**Comment by cheeseng** [comment]
@bvenners Just notice this, I'll start to work on this today.

Cheers.

**Comment by bvenners** [comment]
@SethTisue ScalaTest and Scalactic 3.2.8 including support for 3.0.0-RC3 are published according to Sonatype, though I don't yet see them on Maven Central. They should appear soon. The other artifacts (including the ScalaTest+ modules) will follow tonight.

**Comment by bvenners** [comment]
All are released. Closing.
