### ISSUE TITLE
infix usage of matchers

### ISSUE THREAD

**Issue by Lasering** [scalatest/scalatest#2036]
Under Scala 3 the usage of Matchers is severely hindered (when using the compiler flag `-source future`),by the error:

```
Alphanumeric method shouldBe is not declared `infix`; it should not be used as infix operator.
The operation can be rewritten automatically to `shouldBe` under -deprecation -rewrite.
Or rewrite to method syntax .shouldBe(...) manually.
```

Probably all methods in [AnyShouldWrapper](https://www.scalatest.org/scaladoc/3.2.9/org/scalatest/matchers/should/Matchers$AnyShouldWrapper.html), and in `ResultOf` traits should be declared `infix`.

**Comment by bvenners** [comment]
@Lasering Do you have a compiler flag set perhaps that gets you that warning? Infix uses of methods not marked infix are not supposed to be deprecated until 3.1, not 3.0. 

```
scala> import org.scalatest.matchers.should.Matchers._

scala> 42 shouldBe > (8)
val res0: org.scalatest.Assertion = Succeeded

```

So for now you could perhaps turn off that flag, if you have one. If not let us know here. Meanwhile we will add those infix modifiers.

Bill

**Comment by Lasering** [comment]
For those who want to compile code with scalacOptions: `-Werror -source:future` please add this option until this issue is resolved:
```
Test / scalacOptions += "-Wconf:msg=is not declared `infix`:s"
```

**Comment by Lasering** [comment]
Scala 2.13.6 included a number of syntax changes were added to simplify cross-building between Scala 2 and 3. Especially (for this issue):

- Allow soft keywords open and infix under `-Xsource:3`
- Align leading infix operator with Scala 3 improvements

At least for Scala 2.13(.6) and Scala 3 the source can be the same, helping with the migration. Unfortunately Scalatest is still supporting:
 - Scala 2.10 - first released ~10 years ago
 - Scala 2.11 - first released ~8 years ago
 - Scala 2.12 - first released ~6 years ago
 So things can get a little more complicated.

**Comment by cheeseng** [comment]
@Lasering We have added the open class for Any*Spec, I am not sure about the 2nd one 'Align leading infix operator with Scala 3 improvements', do you mind to clarify what we can do to improve this?

**Comment by Lasering** [comment]
@cheeseng I quoted the wrong line from the 2.13.6 release notes. The right one is:
> Allow soft keywords open and infix under -Xsource:3 (https://github.com/scala/scala/pull/9580)

This allows you to declare most of the matchers methods as infix, and thus solve the problem described in the opening post.

**Comment by Lasering** [comment]
Using scalatest 3.2.15 fixes this problem.
