### ISSUE TITLE
org.scalactic.source.Position incompatible with Gradle build caching and Distributed Testing

### ISSUE THREAD

**Issue by DanielThomas** [scalatest/scalatest#2044]
The compiler macro embeds the fully qualified path to the source file for location at test runtime, however this causes the output to not be portable between machines, making it incompatible with Gradle build caching (or anything that wants to ship test artifacts outside the immediate build environment for that matter).

This also means that tests can't be distributed using the distributed test mechanism, as all resources need to be available via the classloader:

https://docs.gradle.com/enterprise/test-distribution-gradle-plugin/#tests_reading_files_from_src_test_resources

Attempting to locate source files as relative classloader resources before falling back to the file system would provide the flexibility necessary to implement support for both of these features downstream, and allow tests to be packaged with their sources in a standalone jar for running outside of the build tool.

**Comment by cheeseng** [comment]
@DanielThomas If I recall correctly the challenge is to identify the source root correctly for different types of build tools/project structure.  It was initially designed for IDE to open the offending line, but the distributed testing does sound like an interesting requirement.

I think as of current code you may make that field to display a fixed message by setting env var SCALACTIC_FILL_FILE_PATHNAMES=no , as what I can see from the source code here: 

https://github.com/scalatest/scalatest/blob/3.2.x-new/jvm/scalactic-macro/src/main/scala/org/scalactic/source/PositionMacro.scala#L65

it'll lose the path info but I wonder if it will be useful to let the user to define a fixed source root.

**Comment by DanielThomas** [comment]
Thanks @cheeseng - I'm not super familiar with Scalatest, I'm looking at build cache output stability for all of our projects and this came up, so appreciate the background.

Is there a serious impact to functionality at runtime if the source files aren't at the embedded location, or are they just a nice to have and it'll fall back just fine?

**Comment by cheeseng** [comment]
@DanielThomas Sorry to get back to this late, I don't think there's a serious impact to functionality at runtime (for scalatest) unless your tool needs it to report the source code location.

**Comment by bvenners** [comment]
@DanielThomas Originally we only included the source file name, the simple name, and we got a request from a user to embed the full path name instead. That was to support EMACs integration. We made that change, then got a complaint from a big bank that we'd broken their system of ensuring repeatable builds. So we then changed it so that the default is simple names, and only if an environment variable is set will it embed full path names. Are you seeing full path names without setting an environment variable?

**Comment by DanielThomas** [comment]
@bvenners yes, looks like they're on a version that has full paths without the environment variable. Because there's no runtime impact the full paths won't be a huge problem for caching or test distribution. It might affect incrementalism for test caching if different build jobs (and Jenkins workspace paths) make it into fingerprints for test tasks, but we can have folks upgrade ScalaTest in that case. Appreciate the help!
