### ISSUE TITLE
Test name doesn't resolve if 'ShouldVerb' is dynamically created in Intellij

### ISSUE THREAD

**Issue by Habitats** [scalatest/scalatest#2058]
Not sure if this is the right place for Intellij/plugin-related issues, so please guide me in the right direction if it's not!

Given the following test
```
package ai.mito.api.schema.internal

import org.scalatest.FlatSpec

class FooTest extends FlatSpec {

  // This doesn't resolve
  val dynamicThing: String = math.abs(1).toString

  dynamicThing should "test 123" in {
    ???
  }

  // However, this works
  val constantThing: String = "this doesn't change"

  constantThing should "test xyz" in {
    ???
  }
}
```
I am only able to run a single test at the time, if the `ShouldVerb` (`dynamicThing` / `constantThing`) is created as a clean `String`.

This is what happens when I right-click the test, to get the run configuration for it:
![image](https://user-images.githubusercontent.com/1082096/128844081-668f611f-aff6-424d-848d-44debac22d2e.png)

If I choose the `FooTest` option, it'll run _all_ the tests in the file (which works fine) but I'm not able to run a single one.

I would love to be able to generate the `ShouldVerb`s dynamically _and_ get the nice "run single test" in Intellij.

System:
- IntelliJ IDEA 2021.2
- Scala plugin 2021.2.15
- Scala version 2.12.13

**Comment by cheeseng** [comment]
@Habitats Fyi ScalaTest used to have a lib that helps IDE to find the selected test's info, it is here: 

https://github.com/scalatest/scalatest-finders

and I think intellij team has got them into their source tree here: 

https://github.com/JetBrains/intellij-scala/tree/idea212.x/scala/test-integration/scalatest-finders/src/main/java/org/scalatest/finders

So I believe it is still being used by Intellij.  Coming back to your example, I think it is tricky for the IDE/scalatest-finders to return the correct full test name, ScalaTest runner requires the full test name to run single test, so the IDE needs to work that out with the help of scalatest-finders.  In your example, I think it is still possible for IDE to figure out the value of 'constantThing' value, so it seems like it is working in your screenshot, but for the first example, it is simply impossible for the IDE to work out the full test name before actually running it, so I think it is not feasible.

**Comment by Habitats** [comment]
Thanks for the thorough explanation @cheeseng !

I figured it was impossible as well, and ended up skipping the whole "dynamic name" gig I had going.

I'll just close this for now :)
