### ISSUE TITLE
Eventually construct doesn't seem to work in async suites

### ISSUE THREAD

**Issue by alexklibisz** [scalatest/scalatest#2060]
I've run into issues where using `eventually` in an Async suite fails in various ways, sometimes differently depending on the version of Scalatest. 

Rather than enumerating them all here, I've pushed up a repo that reproduces the issues for versions 3.0.9, 3.1.4, and 3.2.9: https://github.com/alexklibisz/scalatest-eventually-async-bug

At the very least, it would be useful to know the following:
- How should calling `Await.result()` on a future inside an eventually block inside an async suite behave?
- How should mapping over a future inside an eventually block inside an async suite behave?

Here's a print out of the test results:

[Test for scalatest 3.0.9](https://github.com/alexklibisz/scalatest-eventually-async-bug/blob/main/scalatest-30x/src/test/scala/EventuallyAsync30xSpec.scala)

```
[info] EventuallyAsync30xSpec:
[info] - Await with default EC *** FAILED ***
[info]   The code passed to eventually never returned normally. Attempted 44 times over 5.032146472 seconds. Last failure message: Futures timed out after [100 milliseconds]. (EventuallyAsync30xSpec.scala:18)
[info] - map with default EC *** FAILED ***
[info]   1 was not equal to 3 (EventuallyAsync30xSpec.scala:28)
[info] - Await with global EC
[info] - map with global EC *** FAILED ***
[info]   1 was not equal to 3 (EventuallyAsync30xSpec.scala:45)
[info] Run completed in 5 seconds, 347 milliseconds.
[info] Total number of tests run: 4
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 3, canceled 0, ignored 0, pending 0
[info] *** 3 TESTS FAILED ***
[error] Failed tests:
[error]         EventuallyAsync30xSpec
[error] (scalatest30x / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 7 s, completed Aug 18, 2021, 1:15:48 PM
```

[Test for scalatest 3.1.4](https://github.com/alexklibisz/scalatest-eventually-async-bug/blob/main/scalatest-31x/src/test/scala/EventuallyAsync31xSpec.scala)

```
[info] EventuallyAsync31xSpec:
[info] - Await with default EC *** FAILED ***
[info]   java.util.concurrent.TimeoutException: Futures timed out after [100 milliseconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
[info]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[info]   at scala.concurrent.Await$.result(package.scala:146)
[info]   at EventuallyAsync31xSpec.$anonfun$new$3(EventuallyAsync31xSpec.scala:20)
[info]   at org.scalatest.enablers.Retrying$$anon$2.org$scalatest$enablers$Retrying$$nestedInanon$2$$tryTryAgain$1(Retrying.scala:84)
[info]   at org.scalatest.enablers.Retrying$$anon$2.retry(Retrying.scala:137)
[info]   at org.scalatest.enablers.Retrying$$anon$2.retry(Retrying.scala:76)
[info]   at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:402)
[info]   ...
[info] - map with default EC
[info] - Await with global EC *** FAILED ***
[info]   1 was not equal to 3 (EventuallyAsync31xSpec.scala:38)
[info] - map with global EC
[info] Run completed in 469 milliseconds.
[info] Total number of tests run: 4
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 2, failed 2, canceled 0, ignored 0, pending 0
[info] *** 2 TESTS FAILED ***
[error] Failed tests:
[error]         EventuallyAsync31xSpec
[error] (scalatest31x / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 1 s, completed Aug 18, 2021, 1:17:33 PM
```

[Test for scalatest 3.2.9](https://github.com/alexklibisz/scalatest-eventually-async-bug/blob/main/scalatest-32x/src/test/scala/EventuallyAsync32xSpec.scala)

```
[info] EventuallyAsync32xSpec:
[info] - Await with default EC *** FAILED ***
[info]   java.util.concurrent.TimeoutException: Futures timed out after [100 milliseconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
[info]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[info]   at scala.concurrent.Await$.result(package.scala:146)
[info]   at EventuallyAsync32xSpec.$anonfun$new$3(EventuallyAsync32xSpec.scala:20)
[info]   at org.scalatest.enablers.Retrying$$anon$2.org$scalatest$enablers$Retrying$$nestedInanon$2$$tryTryAgain$1(Retrying.scala:85)
[info]   at org.scalatest.enablers.Retrying$$anon$2.retry(Retrying.scala:141)
[info]   at org.scalatest.enablers.Retrying$$anon$2.retry(Retrying.scala:77)
[info]   at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:415)
[info]   ...
[info] - map with default EC
[info] - Await with global EC *** FAILED ***
[info]   1 was not equal to 3 (EventuallyAsync32xSpec.scala:38)
[info] - map with global EC
[info] Run completed in 639 milliseconds.
[info] Total number of tests run: 4
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 2, failed 2, canceled 0, ignored 0, pending 0
[info] *** 2 TESTS FAILED ***
[error] Failed tests:
[error]         EventuallyAsync32xSpec
[error] (scalatest32x / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3 s, completed Aug 18, 2021, 1:19:35 PM
```

**Comment by cheeseng** [comment]
@alexklibisz The Eventually in 3.0.9 does not support async, it just uses a blocking way to retry by doing a Thread.sleep to wait, 3.0.9 first failure I think is due to the Future is never ready as it is queued behind the async test future by SerialExecutionContext, the default execution context that is implemented using a queue running directly in the current thread.

Starting 3.1 Eventually delegates the retrying task to Retrying, which does support Retrying[Future[T]] and Retrying[T], Retrying[T] still uses the old blocking way if I remember correctly.  In your case the test that uses Future.map will get Retrying[Future[T]] because the return type of the Eventually block is a Future, but for the Await.result one it will get Retrying[T] because the return type is just Assertion, I am surprise the Retrying[T] is not working, I'll try to dig deeper to see why.

**Comment by cheeseng** [comment]
Ok I found the reason, it will resolve to Retrying[Future[T]] when there's an implicit execution context in scope: 

https://github.com/scalatest/scalatest/blob/3.2.x-new/jvm/core/src/main/scala/org/scalatest/enablers/Retrying.scala#L76

Perhaps the quickest answer to your case is that the Await.result tests shouldn't be in the async test suite, which is designed for tests that return Future, regular test suite is probably the better home for Await.result.

**Comment by cheeseng** [comment]
@alexklibisz Ok I think I did find a bug in Retrying[Future[T]] implementation, it failed pre-maturely without retry when the error is thrown from the function directly not from the Future.  The first test behavior should be the consistent with what 3.0.9 does, which it should keep retry until it timeout (because it is queue after the current async test).  I'll submit a PR for that.

Cheers.

**Comment by alexklibisz** [comment]
Thanks for the quick responses! I'm glad the examples helped.

> Perhaps the quickest answer to your case is that the Await.result tests shouldn't be in the async test suite, which is designed for tests that return Future, regular test suite is probably the better home for Await.result.

I agree -- using Await in an Async spec is an anti-pattern and it's fine if it doesn't work well in all cases.

When you say Retrying[Future[T]], are you referring to the pattern of mapping over a future inside an eventually/retrying block?

Also, no huge rush on this. We were able to work around it in the case we found it by switching to a non-Async suite.

**Comment by cheeseng** [comment]
@alexklibisz Er, I am sorry I am not sure if I understand your question correctyly, here's some description on how it works, the eventually will take a type class Retrying[T] here which will do the real job of retrying: 

https://github.com/scalatest/scalatest/blob/3.2.x-new/jvm/core/src/main/scala/org/scalatest/concurrent/Eventually.scala#L414

When there's an implicit execution context in scope, it will use Retrying[Future[T]] produced here: 

https://github.com/scalatest/scalatest/blob/3.2.x-new/jvm/core/src/main/scala/org/scalatest/enablers/Retrying.scala#L76

which will retry Future[T] when it fails, for other cases, you'll get a Retrying[T] here: 

https://github.com/scalatest/scalatest/blob/3.2.x-new/jvm/core/src/main/scala/org/scalatest/enablers/Retrying.scala#L148

which is non-async and will block with Thread.sleep.

Hope this helps.

**Comment by cheeseng** [comment]
@alexklibisz Fyi I submitted a minor fix here so when the exception is thrown in the code to produce Future itself fails with exception: 

https://github.com/scalatest/scalatest/pull/2061

This will make your test 1 has the consistent behavior as 3.0.9.

**Comment by alexklibisz** [comment]
Thanks @cheeseng . So with this fix, would the following pass?

```
"map with default EC" in {
    val it = (1 to 10).iterator
    def next(): Future[Int] = Future(it.next())
    eventually {
      next().map(_ shouldBe 3)
    }
  }
```

**Comment by cheeseng** [comment]
> Thanks @cheeseng . So with this fix, would the following pass?
> 
> ```
> "map with default EC" in {
>     val it = (1 to 10).iterator
>     def next(): Future[Int] = Future(it.next())
>     eventually {
>       next().map(_ shouldBe 3)
>     }
>   }
> ```

Yes I think it should.

**Comment by alexklibisz** [comment]
Yes, I'll re-run my original repo tests. Stand by...

**Comment by cheeseng** [comment]
@alexklibisz Thanks for verifying!
