### ISSUE TITLE
Way to prioritize long-tail tests early when issuing `sbt test`

### ISSUE THREAD

**Issue by zzvara** [scalatest/scalatest#2066]
I'm looking for a way to prioritize 3 tests out of 961 in an SBT project. Tests may run in parallel, thus, in any order. However, the aforementioned 3 tests each take 20 minutes to complete. Successful completion of the 961 tests takes about 45 minutes. What I can see from the logs is that the 3 "long-tail" tests are finishing up in the last 15 minutes of the 45-minute rundown, because those were started way too late. Better prioritization of "long-tail" tests would yield a much better deadline, probably a 30-minute deadline instead of a 45-minute one.

**Is there any way to prioritize very slow test suites early with the parallel execution fashion in order to avoid slow test suites lagging for a long time after all the other ones are finished?**

**Comment by bvenners** [comment]
I think sbt may be discovering those tests not ScalaTest. It is done through sbt's Framework API, which is here:

https://github.com/sbt/test-interface

So it may be more of an sbt question. One thought I have is you could make a separate sbt project for the long-running tests and run that in parallel.

If you don't mind not using discovery, and writing a Suite that just decids what tests to run when, you can do that in ScalaTest. You'd put DoNotDiscover on all the tests except the outermost Suite, then write that to run your 3 long running tests first in parallel, then maybe one more thread for the other tests.
