### ISSUE TITLE
Missing tag for 3.2.12?

### ISSUE THREAD

**Issue by francisdb** [scalatest/scalatest#2122]
Scalasteward pointed us to https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_2.13/3.2.12/ but there is no such tag here?

see also https://github.com/scalatest/scalatest/pull/2121

**Comment by cheeseng** [comment]
@francisdb I'll create the release tag after this @bvenners merged this PR: 

https://github.com/scalatest/scalatest/pull/2121

**Comment by cheeseng** [comment]
Closing as release tag created.
