### ISSUE TITLE
Outdated documentation on "Sharing Fixtures"

### ISSUE THREAD

**Issue by TheodorRene** [scalatest/scalatest#2124]
In the [Sharing Fixtures](https://www.scalatest.org/user_guide/sharing_fixtures#withFixtureNoArgTest) documentation under the header  "Overriding withFixture(OneArgTest)" a `fixtures.AnyFlatSpec` is referenced. I'm pretty sure this class does not exist anymore, so  I resorted to [flatspec.FixtureAnyFlatSpec](https://www.scalatest.org/scaladoc/3.1.2/org/scalatest/flatspec/FixtureAnyFlatSpec.html) which seems to be what I need. The documentation should probably be updated accordingly.

**Comment by cheeseng** [comment]
@TheodorRene Fyi I submitted a PR for this here: 

https://github.com/scalatest/scalatest-website/pull/194
