### ISSUE TITLE
Position with scala 3

### ISSUE THREAD

**Issue by hagay3** [scalatest/scalatest#2162]
Hi,
Im trying to migrate my code to scala 3, I see that `futureValue` uses `Position` implicit.
`Position.here` uses scala 2 macros which is disabled in scala 3.
What are the migration guidelines regarding that ?
Thanks :)

```
val results: Future[Any] = ???
results.futureValue(patienceConfig, Position.here)
```

```
[error] -- Error: /Users/hagai.ovadia/Hagai/mydev/skuber/client/src/it/scala/skuber/CustomResourceSpec.scala:64:40 
[error] 64 |    results.futureValue(patienceConfig, Position.here)
[error]    |                                        ^
[error]    |Scala 2 macro cannot be used in Dotty. See https://dotty.epfl.ch/docs/reference/dropped-features/macros.html
[error]    |To turn this error into a warning, pass -Xignore-scala2-macros to the compiler
```

```
object Position {

  import scala.language.experimental.macros

  /**
   * Implicit method, implemented with a macro, that returns the enclosing
   * source position where it is invoked.
   *
   * @return the enclosing source position
   */
  implicit def here: Position = macro PositionMacro.genPosition
}

```

**Comment by cheeseng** [comment]
@hagay3 Are you using Scala 3 build for ScalaTest?  If so it should use the Scala 3 version of macro.

**Comment by hagay3** [comment]
@cheeseng 
Thanks, I was using an older release of scalatest, it works now :)
But still Intellij IDEA refuses to identify scala 3 sources (even after sbt refresh)
![image](https://user-images.githubusercontent.com/13578121/187849629-2f9bc226-6a47-40be-b07e-3c1a5eb3dc99.png)

**Comment by cheeseng** [comment]
@hagay3 Hmm, I am not sure why intellij refuses to do so, is it possible to have a minimized project that can reproduce the problem?
