### ISSUE TITLE
Access Scenario name from inside a scenario?

### ISSUE THREAD

**Issue by dvardy** [scalatest/scalatest#2180]
We're using scalatest 3.2.14 and issuing Runner.run(args) from our Main class to invoke the scalatest advanced runner.

Is there a way we can access the scenario name within our test? Eg:

```
    Scenario("myscenarioA") {
      println("scenario name is: " + Scenario.name.toString()) //to give "myscenarioA"
      Given("given...")
//      println(myenv)
      When("when...")
      Then("then...")
      assert(1 == 1)
    }
```

We differentiate some of the configuration used in out test step methods based on the scenario name, so need to get the scenario name and pass it to our test step methods where appropriate. 

A work around might be to do:

```
var scenarioName="myscenarioA"
    Scenario(scenarioName) {
      println("scenario name is: " + Scenario.name.toString()) //to give "myscenarioA"
      Given("given...")
//      println(myenv)
      When("when...")
      Then("then...")
      assert(1 == 1)
    }
```

Thanks

**Comment by cheeseng** [comment]
@dvardy Sorry for responding late, I think fixtures can help with what you are trying to do: 

https://www.scalatest.org/user_guide/sharing_fixtures

**Comment by dvardy** [comment]
Thanks @cheeseng
