### ISSUE TITLE
Not Useful scala.MatchError given while failing Tests

### ISSUE THREAD

**Issue by chenyuan99** [scalatest/scalatest#2240]
[error] (someModule/test: loadedTestFrameWorks) scala.MatchError

**Comment by cheeseng** [comment]
@chenyuan99 Do you mind to provide more info to help reproducing the error you are seeing?

Thanks.

**Comment by chenyuan99** [comment]
I believe it is caused by outdated sbt jar file. I fixed it by replacing to updated sbt .  I think we can capture it by given more informative error message
