### ISSUE TITLE
Passing assert message by-name?

### ISSUE THREAD

**Issue by FJShen** [scalatest/scalatest#2289]
The error message is always passed by-value to `org.scalatest.Assertions.assert()`, here's the method's signature:  
`def assert(condition: Boolean, clue: Any)(implicit prettifier: Prettifier, pos: source.Position): Assertion `

Contrast this with the pass by-name approach used by `scala.Predef.assert()` (https://www.scala-lang.org/api/2.13.8/scala/Predef$.html#assert(assertion:Boolean,message:=%3EAny):Unit): 
`final def assert(assertion: Boolean, message: => Any): Unit`

My use case (chiseltest) calls `assert` frequently in a loop. Testing the assertion itself is cheap to perform, but generating the error message is costly and slow, hence I wish to avoid "materializing" the contents of the error_message string unless necessary, that is, only evaluate when the assertion fails.

```
for(i <- some_large_range){
  def error_message : String = dut.dump_internal_values_to_string()
  assert(dut.output == 0, error_message)
  dut.update_internal_states()
}
```
Is there a way to avoid the cost of evaluating the message string unless the assertion really fails?

**Comment by FJShen** [comment]
I did some research, based on my understanding of the documentation for `assert`:

> Assert that a boolean condition, described in String message, is true. If the condition is true, this method returns normally. Else, it throws TestFailedException with a helpful error message appended with the String obtained by invoking toString on the specified clue as the exception's detail message. 

I can pass in any class instance that implements the `toString` method as the second argument  (`clue`). So far the most succinct way I figured out is to create an ad-hoc anonymous class instance and pass it to `assert`:
```
// dut is my device-under-test
for(i <- some_large_range){
  val error_message_obj = new AnyRef{
    override def toString : String= {dut.dump_interal_values_to_string()}
  }
  assert(dut.output == 0, error_message_obj)
}
```

Honestly it works, but why couldn't `assert` just take a string by-name, just like `scala.Predef.assert` does?

**Comment by cheeseng** [comment]
@FJShen I think that makes sense, we'll not be able to do that in 3.2 as it is a breaking change, but perhaps in 3.3.  @bvenners do you think it is a good idea?

**Comment by bvenners** [comment]
I think we're going to stick with clue as a regular parameter. The workaround you have is a good one. Just compute the expensive string inside the toString method of a "clue" object that you pass in that position.
