### ISSUE TITLE
add back Mockito 4 support?

### ISSUE THREAD

**Issue by pjfanning** [scalatest/scalatest#2311]
Mockito 4 support was dropped in https://github.com/scalatest/scalatest/releases/tag/release-3.2.18

Unfortunately, Mockito 5 only support Java 11. Scalatest generally supports Java 8. Lots of lib maintainers need to support Java 8.

https://github.com/mockito/mockito/releases/tag/v5.0.0

I can raise a separate issue but the testng upgrade in scalatest 3.2.18 has the same issue - since [v7.6.0](https://github.com/testng-team/testng/releases/tag/7.6.0), testng only supports Java 11.

**Comment by cheeseng** [comment]
@pjfanning I think we can support Mockito 4.x if there's a request, I am currently on the move but I'll be happy to stage a jdk8 3.2.18.0 build for mockito 4.x when I am back.

Cheers.

**Comment by cheeseng** [comment]
@pjfanning fyi I have added a 3.2.18.0 build for Mockito 4.11, you may try if it works better for you.

Cheers.
