### ISSUE TITLE
Release 3.2.19 is not documented on this repo

### ISSUE THREAD

**Issue by TonioGela** [scalatest/scalatest#2330]
I noticed that the release 3.2.19 is available [on maven central](https://repo1.maven.org/maven2/org/scalatest/scalatest_3/3.2.19/) andscaladex but it's not advertised on this repo. Is it everything okay with this release?

**Comment by ForNeVeR** [comment]
Either there's a security issue they are trying to silently patch, or some unrelated party gained control over the Maven repository.

**Comment by cheeseng** [comment]
Sorry for the delay, release notes for 3.2.19 is here: https://github.com/scalatest/scalatest/releases/tag/release-3.2.19 .

We are working on updating https://www.scalatest.org and https://www.scalactic.org the website currently.
