### ISSUE TITLE
scalatest's scalacheck forAll wrappers lose nested goodness

### ISSUE THREAD

**Issue by copumpkin** [scalatest/scalatest#251]
In plain old scalacheck, I can nest `forAll` calls with impunity. I get the desired distribution of values and don't end up with exponentially more tests running. Scalatest wraps `forAll` and loses this property. For example, the following code will run 10000 tests in scalatest and 100 tests in scalacheck.

```
forAll[Int] { i =>
  forAll(Gen.choose(i, i +10)) { j =>
    // something with i and j
  }
}
```

Of course, it's always possible to rework any nested `forAll` calls into flat ones by bundling generators into tuples (essentially uncurrying) but that leads to much more verbosity in properties.

It seems hard to restore the property given the exception-based `Unit`-returning properties that scalatest promotes, but it also seems desirable.

**Comment by brandon-leapyear** [comment]
I'm seeing this behavior with scalatestplus and `ScalaCheckPropertyChecks`. Since `Checkers` is now deprecated, should this issue be reopened?
