### ISSUE TITLE
Run aborted issue with scalatest-maven-plugin and Jenkins

### ISSUE THREAD

**Issue by levinson** [scalatest/scalatest#297]
I've been looking into an issue where Jenkins reports a build as successful when a test suite fails with "RUN ABORTED" exception.

For example add the following test file to a Maven project:

<pre>
import org.scalatest.{MustMatchers, WordSpecLike}

class AbortedTest extends WordSpecLike with MustMatchers
{
  throw new Error("Exception during construction to demonstrate issue...")

  "A scalatest suite" must
    {
      "fail when run from Jenkins" in
        {
          true must equal (false)
        }
    }
}
</pre>

Then kickoff the build from Jenkins:
<pre>
Apr 18, 2014 11:04:06 AM org.apache.maven.cli.event.ExecutionEventLogger mojoStarted
INFO: --- scalatest-maven-plugin:1.0-RC2:test (scala-integration-test) @ cse-util-common ---
Discovery starting.
*** RUN ABORTED ***
  java.lang.Error: Exception during construction to demonstrate issue...
  at AbortedTest.<init>(AbortedTest.scala:10)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
  at java.lang.Class.newInstance(Class.java:374)
  at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:69)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:38)
  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:37)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
  ...
[JENKINS] Recording test results
  ...
[INFO] Deployment done in 0.47 sec
Finished: SUCCESS
</pre>

However, if I run the build manually on the command line (using the same build parameters passed by Jenkins) it fails as expected:

<pre>
*** RUN ABORTED ***
  java.lang.Error: Exception during construction to demonstrate issue...
  at AbortedTest.<init>(AbortedTest.scala:10)
 ...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.297s
[INFO] Finished at: Fri Apr 18 11:32:31 MDT 2014
[INFO] Final Memory: 22M/256M
[INFO] ------------------------------------------------------------------------
</pre>

So it seems this issue only arises when building a Maven project from Jenkins which uses the scalatest maven plugin.  It's hard to tell if this is an issue with Jenkins or the ScalatTest Maven plugin, but I'm guessing the problem could be at least worked around with a small change to the scalatest-maven-plugin.  In particular, it seems related to issue https://github.com/scalatest/scalatest/issues/273: "The bottom line is that the build succeeds because no result xml files were written."

I plan to also open an issue for Jenkins and cross-reference this ticket in hopes that we can see a fix or workaround in the near future.

**Comment by bkuder** [comment]
Any update on this one? It's also causing problems with our jenkins builds. It's a real headache to track these down since the build succeeds even though the unit tests are not passing.

**Comment by bvenners** [comment]
We'll take a look this week and post here what we find out. If we can fix it on our end we'll do so.

**Comment by bkuder** [comment]
Thanks Bill! Really appreciate you guys taking a look.

**Comment by bvenners** [comment]
We made a fix for this in this PR:

https://github.com/scalatest/scalatest/pull/516

I'll merge that in early this week. Probably it will just go out in 2.3.0, which will be before ScalaDays, so sometime in the next 4 weeks or so.

**Comment by bvenners** [comment]
Closing this issue as it is already in 2.3.x branch.

**Comment by alexeyts** [comment]
We're experiencing the same Jenkins issue.
We tried release 3.0.0-RC4, which should contain the fix, but unfortunately it doesn't solve the problem.

**Comment by thomg** [comment]
My Issue #1001 turned out to be user error, but we're still seeing this issue—exceptions thrown outside the unit tests cause RUN ABORTED which doesn't fail the Jenkins build.

**Comment by alexeyts** [comment]
We're currently using Text Finder Jenkins plugin to fail the build in this case, which is far from optimal.

**Comment by blast-hardcheese** [comment]
FWIW, I just found this as well
