### ISSUE TITLE
Accessing the ConfigMap within a Suite

### ISSUE THREAD

**Issue by swizzlr** [scalatest/scalatest#311]
I've written a trait that extends WebBrowser to support Appium. However, I need to inject two dependencies: the web driver server and the application path, which are required to instantiate the web driver. The best solution seems to be defining the vals in a class extending the trait. However, I can't get at those during instantiation. What do you think would be the best way to inject these dependencies into a subtrait of WebBrowser?

**Comment by hekaldama** [comment]
Hey @bvenners, did this get implemented at all? Thanks!
