### ISSUE TITLE
contains allOf -- exact elements from RHS

### ISSUE THREAD

**Issue by alexander-myltsev** [scalatest/scalatest#353]
Hi all,

I find http://doc.scalatest.org/2.2.0/#org.scalatest.Matchers@workingWithContainers very useful in projects testing.

It is not convenient to get error message if one big sequence on the left doesn't contain some of elements on the right.

Is there a way to get exact elements that are not on the left hand side?

**Comment by bvenners** [comment]
For now what you can do is just surround the expression with withClue and add a clue that shows the exact differences. You can read about withClue in the Scaladoc for assertions:

http://doc.scalatest.org/2.2.4/index.html#org.scalatest.Assertions

In the future we will be adding something called a Differ that will allow error messages diffs to be customized, and that will be the recommended way to deal with this kind of situation.
