### ISSUE TITLE
withClue wrapping eventually that times out is not serializable

### ISSUE THREAD

**Issue by fiadliel** [scalatest/scalatest#358]
withClue("a clue") { eventually { test that fails } }
cannot be serialized, e.g.
[info]   java.io.NotSerializableException: org.scalatest.Assertions$AssertionsHelper

See https://github.com/fiadliel/scalatest/commit/d140c1557639b1ede841fcb0cd7cf5dbd63f1ae9 for an example test that should fail.

I came across the issue when looking at some failing tests where arbitrary classes, e.g. Matchers$AWord also appeared as not serializable.

It appears that the problem does not appear if eventually and withClue are swapped (eventually wrapping withClue).

I am not familiar enough with the codebase to feel confident in my suggestion of the best solution here (the asInstanceOf calls in this part of the code may be hiding unexpected object types).

**Comment by cheeseng** [comment]
@fiadliel FYI I submitted a PR to fix this issue: 

https://github.com/scalatest/scalatest/pull/618

If it gets merged in it should be included in the upcoming 3.0.0 release.

**Comment by cheeseng** [comment]
@fiadliel I back ported the PR into 2.2 branch too: 

https://github.com/scalatest/scalatest/pull/683

Hopefully it will be included in the upcoming 2.2.6 soon.

**Comment by bvenners** [comment]
This was fixed months ago, but we never closed the ticket. Closing now.
