### ISSUE TITLE
Selenium DSL "capture" problem

### ISSUE THREAD

**Issue by circlespainter** [scalatest/scalatest#367]
Hi,

"capture.apply" seems to be reading and writing on the same file, in my case this results in 0-length screenshots (Windows 7 64-bit, JDK8, scala 2.11.2, selenium 2.2.1):

https://github.com/scalatest/scalatest/blob/release-2.2.1-for-scala-2.11-and-2.10/src/main/scala/org/scalatest/selenium/WebBrowser.scala#L4305

Plus I think common code with "capture.to" could be factored out (BTW, "capture.to" seems not to delete the temporary file if the copy fails for whatever reason, is it meant to work like this?); finally there's a typo in the exception message, I think it should read "Screen capture is not supported by ".

TIA

**Comment by bvenners** [comment]
Hi,

Can you clarify how you got a zero-length screenshot? What do you mean by "reading and writing on the same file"?

Thanks.

Bill

**Comment by bvenners** [comment]
@circlespainter I never heard back from you on my previous questions, so I'll close the ticket. If this is still an issue for you please post here and I'll reopen it.

**Comment by circlespainter** [comment]
Yes sorry, I didn't have anymore time to look into it. I think what was causing the 0-length file for me was `new FileOutputStream(outFile).getChannel.transferFrom(new FileInputStream(tmpFile).getChannel, 0, Long.MaxValue)` (`outFile` and `targetFile` ended up being the same).

Sure, I'll try again and in case I'll re-open the issue with more details.

**Comment by Phonesis** [comment]
This is an old issue but I've recently encountered it. It appears that any screenshot the DSL takes with Selenium is an empty file of 0 bytes. I have tried this using the latest Chrome and Firefox Webdrivers.
