### ISSUE TITLE
Why would the forked JVM rely on my local host instead of 127.0.0.1

### ISSUE THREAD

**Issue by betehess** [scalatest/scalatest#388]
Let me first point to the [StackOverflow question](http://stackoverflow.com/a/25853227/1057315) where I discuss the problem. You can jump directly to the answer.

I am reproducing the text here, just in case:

It turns out that under the right settings, sbt will fork the JVM to execute the tests, and will want to communicate with it. How this is done is up to the test framework. In the case of scalatest, the communication between the two processes will be done through a server. scalatest just communicates the server address and port that have to be used by sbt. And this is happening [there](https://github.com/scalatest/scalatest/blob/master/src/main/scala/org/scalatest/tools/Framework.scala#L1015).

```scala
val array = Array(InetAddress.getLocalHost.getHostAddress, skeleton.port.toString)
```

Now, go read what the javadoc says for [InetAddress#getLocalHost](http://docs.oracle.com/javase/8/docs/api/java/net/InetAddress.html#getLocalHost--):

> Returns the address of the local host. This is achieved by retrieving
> the **name of the host from the system**, then resolving that name into an
> InetAddress.

I am on Linux. My local host (which is **never** `localhost`) ends up being `dopey`. Now, for some reason (I was messing with my network at home), my `/etc/hosts` was assigning a bogus address to `dopey`. So instead of something like `127.0.0.1`, scalatest would try to open a socket on this fictional server. And because of [where this is happening](https://github.com/scalatest/scalatest/blob/master/src/main/scala/org/scalatest/tools/SocketReporter.scala#L26), you don't see anything helpful in the stacktrace.

My guess is that the intention was always to use `127.0.0.1`...

**Comment by myyk** [comment]
This issue has been causing me problems for some time that I've just been living with. The patched version 2.2.3-SNAP2 works wonderfully for me. I hope this change might get merged in sometime.

**Comment by bvenners** [comment]
Sorry, didn't have time to announce it, but it was released a while back as 2.2.3:

https://oss.sonatype.org/content/groups/public/org/scalatest/scalatest_2.11/2.2.3/

Please give that a shot and let me know if you have any further trouble.

Thanks.

Bill

**Comment by myyk** [comment]
The error was still present in 2.2.3 which prompted me to find this thread, though it is not there in 2.2.3-SNAP2.

**Comment by bvenners** [comment]
Ah, OK. Thanks for clarifying. I will get a 2.3 release out soon that will contain the fix.

**Comment by bvenners** [comment]
This was release as 2.2.4.
