### ISSUE TITLE
sbt configuration for scala 2.10 and scala 2.11

### ISSUE THREAD

**Issue by yanns** [scalatest/scalatest#393]
On http://www.scalatest.org/download, instead of
```
libraryDependencies += "org.scalatest" % "scalatest_2.11" % "2.2.1" % "test"
```
the documentation should be:
```
libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.1" % "test"
```

**Comment by bvenners** [comment]
Actually at one point the sbt powers that be told me to stop using the %%, but then later I think theybacktracked. I believe it was when Scala started ensuring binary compatibility of point releases. I think at first they may have thought they would need to deprecate %% but then figured out how to make it know whether to use 3 or 2 version numbers. I'll ask again and switch back to %% if that's recommended.
