### ISSUE TITLE
Run Configuration in Eclipse: cannot find Suite Class

### ISSUE THREAD

**Issue by HaraldKi** [scalatest/scalatest#395]
Despite using 

class RealTest extends FunSuite {...}

Eclipse menu "Run As" does not provide the option to run as suite. See also http://stackoverflow.com/questions/14298993/scalatest-run-configuration-in-eclipse-cannot-find-suite-class

This can be corrected by aligning the package declaration with the folder structure.
Since Scala allows for the folder structure to not match the package declaration (debatable), it would be great to maybe get a warning at least that this is the problem.

**Comment by bvenners** [comment]
This question was answered on StackOverflow, so closing. We will look at whether there is a way to at least provide a warning in the ScalaTest eclipse plugin.
