### ISSUE TITLE
Large queue on Travis CI

### ISSUE THREAD

**Issue by joshk** [scalatest/scalatest#402]
Hey Guys,

I didn't know who best to contact to discuss this issue.

I see from your build history on Travis CI that the majority of build are either erroring or failing. Plus I see your queue is around 900 jobs long.

Looking at the history, it seems as though you have a consistent offender. Have you investigated why it continues to fail or error out?

Also, if you would like to talk about dedicated infrastructure to make sure jobs run in a timely manner, please let us know and we can discuss options available.

Thanks,

Josh

**Comment by bvenners** [comment]
@joshk Sorry I only noticed this ticket now when you closed it. Can we chat about this at some point?
