### ISSUE TITLE
Could 'x should be < 250' be made to work when 'x' is Double?

### ISSUE THREAD

**Issue by akauppi** [scalatest/scalatest#415]
This is a small thing, but I'm reporting it for opinions since the compiler errors don't really help one much if facing this. 

My code (using ScalaTest 2.2.1, `FlatSpec` and `Matchers`):

    ...
    val avg: Double = (times_ms.sum : Double) / times_ms.size
    avg should be < 250.0     // ScalaTest note: needs '.0', otherwise does not find right matche
    ...

I first had just `250` which gives the following compiler errors:

[error] /Users/...: overloaded method value should with alternatives:
[error]   (endWithWord: org.scalatest.words.EndWithWord)(implicit ev: <:<[Double,String])RestAPITest.this.ResultOfEndWithWordForString <and>
[error]   (startWithWord: org.scalatest.words.StartWithWord)(implicit ev: <:<[Double,String])RestAPITest.this.ResultOfStartWithWordForString <and>
[error]   (includeWord: org.scalatest.words.IncludeWord)(implicit ev: <:<[Double,String])RestAPITest.this.ResultOfIncludeWordForString <and>
[error]   (notExist: org.scalatest.words.ResultOfNotExist)(implicit existence: org.scalatest.enablers.Existence[Double])Unit <and>
[error]   (existWord: org.scalatest.words.ExistWord)(implicit existence: org.scalatest.enablers.Existence[Double])Unit <and>
[error]   (containWord: org.scalatest.words.ContainWord)org.scalatest.words.ResultOfContainWord[Double] <and>
[error]   (haveWord: org.scalatest.words.HaveWord)RestAPITest.this.ResultOfHaveWordForExtent[Double] <and>
[error]   (beWord: org.scalatest.words.BeWord)RestAPITest.this.ResultOfBeWordForAny[Double] <and>
[error]   (inv: org.scalactic.TripleEqualsSupport.TripleEqualsInvocationOnSpread[Double])(implicit ev: Numeric[Double])Unit <and>
[error]   [U](inv: org.scalactic.TripleEqualsSupport.TripleEqualsInvocation[U])(implicit constraint: org.scalactic.Constraint[Double,U])Unit <and>
[error]   (notWord: org.scalatest.words.NotWord)org.scalatest.words.ResultOfNotWordForAny[Double] <and>
[error]   [TYPECLASS1[_], TYPECLASS2[_]](rightMatcherFactory2: org.scalatest.matchers.MatcherFactory2[Double,TYPECLASS1,TYPECLASS2])(implicit typeClass1: TYPECLASS1[Double], implicit typeClass2: TYPECLASS2[Double])Unit <and>
[error]   [TYPECLASS1[_]](rightMatcherFactory1: org.scalatest.matchers.MatcherFactory1[Double,TYPECLASS1])(implicit typeClass1: TYPECLASS1[Double])Unit <and>
[error]   (rightMatcherX1: org.scalatest.matchers.Matcher[Double])Unit
[error]  cannot be applied to (org.scalatest.matchers.Matcher[Int])
[error]       avg should be < 250
[error]           ^
[error] one error found

That's a pretty long error for essentially "hey, we cannot convert your integer to a double".

If you deem this use is fairly common (I think it is), and if you know a way to make it just work, it'd be delightful. :)

**Comment by bvenners** [comment]
I think this will be useful, and it is something we will look at in 3.0 once we have the cooperative equality classes in.

**Comment by akauppi** [comment]
Does closing this mean it's "in" in 3.0 SNAP versions? 

Also, where could I find a summary of 3.0 features? Google gave https://skillsmatter.com/skillscasts/6021-scalatest-and-scalactic-3-0 and https://gist.github.com/bvenners/f038d946adab18b9cb78

Would love to see how 3.0 compatible my test suites are.
