### ISSUE TITLE
Use call-by-name for the `orElse` parameter in `Or.from(Option, orElse)`

### ISSUE THREAD

**Issue by dotta** [scalatest/scalatest#454]
The signature of Or.from(Option, orElse) method should be changed to use call-by-name for the `orElse` parameter, i.e., 

`def from[G, B](option: Option[G], orElse: => B): G Or B = ...`

The reason being that the passed `orElse` expression should be evaluated only if `option` is equal to `None`.

See commit https://github.com/scalatest/scalatest/commit/461f2651dcdc3f1248c2515142d25d8e526b6465

**Comment by bvenners** [comment]
This will be released in 2.3.0.
