### ISSUE TITLE
Backport fix for multiple excludes to scalatest for 2.9

### ISSUE THREAD

**Issue by Daenyth** [scalatest/scalatest#462]
I'm currently running into a bug with scalatest 1.9.2 when running multiple exclude arguments as shown in your documentation: `java.lang.IllegalArgumentException: Runpath must be either zero or two args`

Backporting this commit to your scala 2.9 branch would fix it: https://github.com/dmakhno/scalatest/commit/d472842cd2b4e8b324ac4e79aa5a7197eca6a40c

Is this possible or should I compile scalatest with this myself? I'd rather avoid that since it greatly complicates my CI environment.

**Comment by bvenners** [comment]
@daenyth are you still having this issue on Scala 2.9?

**Comment by Daenyth** [comment]
The issue still exists AFAIK. I believe that project is now on 2.10 or 2.11. In either case I'm not working on it any more.

**Comment by bvenners** [comment]
OK. I'll make the executive decision not to fix it for Scala 2.9 then. It definitely still exists there, but there's no evidence anyone is affected by it anymore. We had to stop supporting 2.9 back before the 2.0 release, which was over two years ago. Onwards and upwards to newer Scala versions!
