### ISSUE TITLE
all scaladoc links are broken

### ISSUE THREAD

**Issue by SashaOv** [scalatest/scalatest#476]
All links on the page http://www.scalatest.org/scaladoc are broken

**Comment by bvenners** [comment]
That was quick. We are migrating the server. Started at noon eastern time today. Should be back up shortly, but I admit I forgot this was on that server.

**Comment by bvenners** [comment]
...and we're back! Sorry for the downtime, but we needed a more umphy server. The Time To Live is 5 mimutes so if it doesn't show up for you yet, try again in a couple minutes.
