### ISSUE TITLE
withScreenshot should accept fn: => T and return T not Unit

### ISSUE THREAD

**Issue by eallik** [scalatest/scalatest#481]
The signature of `withScreenshot` is:

    def withScreenshot(fun: => Unit)(implicit driver: WebDriver): Unit

whereas the signature of `eventually` is:

    def eventually[T](fun: => T)(implicit config: PatienceConfig): T

so I'm suggesting this change:

    - def withScreenshot(fun: => Unit)(implicit driver: WebDriver)
    + def withScreenshot[T](fun: => T)(implicit driver: WebDriver): T

Is that something worth considering?

**Comment by bvenners** [comment]
Hi,

Yes, that's a good idea. Several other constructs are going through a similar transition in 3.0. If you are willing, please submit a pull request. If not we'll add this to our list. It was below my radar for 3.0, so it is useful you pointed it out.

Thanks.

Bill

**Comment by bvenners** [comment]
This was fixed last May in the 3.0.x branch, but we never closed the issue. Closing now.
