### ISSUE TITLE
Matchers fail to understand Array equality for Arrays wrapped inside a container/collection

### ISSUE THREAD

**Issue by miguno** [scalatest/scalatest#491]
Because `Array` is a tricky beast [ScalaTest decided to special-case its equality](https://github.com/scalatest/scalatest/blob/master/src/main/scala/org/scalactic/DefaultEquality.scala) (which is nice!).

Unfortunately, the current implementation is not able to "properly" understand Array equality if arrays are within another container such as `Set[Array[Int]]`.  For example, I would have expected the following test to pass instead of throwing a `TestFailedException`:

``` scala
scala> val set1 = Set(Array(1))
set1: scala.collection.immutable.Set[Array[Int]] = Set(Array(1))

scala> val set2 = Set(Array(1))
set2: scala.collection.immutable.Set[Array[Int]] = Set(Array(1))

scala> set1 should be(set2)
org.scalatest.exceptions.TestFailedException: Set(Array(1)) was not equal to Set(Array(1))
```

What would be an idiomatic way in ScalaTest to make this work correctly?

**Comment by miguno** [comment]
Addendum: At the moment I use the following workaround, though I am not 100% convinced yet that it is sound.

```scala
import org.scalatest.matchers.{MatchResult, Matcher}

trait CustomMatchers {

  import scala.reflect._

  /**
   * This matcher compares sets correctly even if they contain [[Array]] elements.
   */
  class SetMatcher[S: ClassTag](expectedSet: Set[S]) extends Matcher[Set[S]] {

    def apply(actualSet: Set[S]): MatchResult = {
      val equal = actualSet match {
        case a: Set[S] if implicitly[ClassTag[S]].runtimeClass.isArray =>
          val sameSize = expectedSet.size == a.size
          val sameContent = {
            val expHashes: Set[Int] = expectedSet.map { _.asInstanceOf[Array[_]].toSeq.hashCode() }
            val actHashes: Set[Int] = a.map { _.asInstanceOf[Array[_]].toSeq.hashCode() }
            expHashes == actHashes
          }
          sameSize && sameContent
        case _ => expectedSet == actualSet
      }
      MatchResult(equal, s"$actualSet was not equal to $expectedSet", s"$actualSet was equal to $expectedSet")
    }

  }

  def beSetEqualTo[S: ClassTag](expectedSet: Set[S]) = new SetMatcher(expectedSet)

}

object CustomMatchers extends CustomMatchers
```

The reason I use a set of hashes is that a `Set` does not guarantee any ordering, so the naive approach of iterating through the sets and then, for each element (here: `Array`), comparing via `actual.sameElements(expected)` does not work in the general case unfortunately.

**Comment by bvenners** [comment]
Hi miguno,

In 3.0 that will actually work as you wish, because we're going to make collections, options, etc., do recursive equality by default. Also both equal and be will take an implicit Equality[T] for the left hand type T. For now what I'd recommend is to make a custom implicit Equality[Set[Array[S]] that has the behavior you want, then use the equal matcher not the be matcher.

implicit def customEq[S]: Equality[Set[Array[S]]  = new Equality[Set[Array[S]] {
  def areEqual(left: Set[Array[S]], right: Any): Boolean = ...
}

set1 should equal(set2)

Bill

**Comment by miguno** [comment]
Many thanks for the quick response, Bill!

Happy to hear that v3.x will support this functionality out of the box.  Do you already have an idea when 3.x will be released?

For other readers who might stumble upon this ticket in the meantime, here's the code I am currently using:

```scala
import org.scalactic.Equality

trait CustomEquality {

  import scala.reflect.ClassTag

  /**
   * A custom [[Equality]] definition for [[Set]] that understands how to compare [[Array]] elements in the set.
   *
   * To make use of this custom matcher for [[Set]] you must `import CustomEquality._` and
   * then use `set1 should equal(set2)` instead of `set1 should be(set2)`.
   *
   * Note: Once ScalaTest 3.x is released this custom [[Equality]] definition will no longer be needed.
   * See https://github.com/scalatest/scalatest/issues/491 for details.
   */
  implicit def customEq[S: ClassTag]: Equality[Set[S]] = new Equality[Set[S]] {

    override def areEqual(left: Set[S], right: Any): Boolean = {
      val equal = right match {
        case r: Set[_] if implicitly[ClassTag[S]].runtimeClass.isArray =>
          val sameSize = left.size == r.size
          val sameContent = {
            val leftHashes: Set[Int] = left.map {_.asInstanceOf[Array[_]].toSeq.hashCode()}
            val rightHashes: Set[Int] = r.map {_.asInstanceOf[Array[_]].toSeq.hashCode()}
            leftHashes == rightHashes
          }
          sameSize && sameContent
        case _ => left == right
      }
      equal
    }

  }
}

// Make the custom equality definitions easy to import with: `import CustomEquality._`
object CustomEquality extends CustomEquality
```

In the actual test spec:

```scala
import CustomEquality._
set1 should equal(set2)
```

As Bill pointed out it is important to use `should equal` (`should be` will not work because we have defined a custom `Equality` but not a custom matcher).

**Comment by ryan-williams** [comment]
I think I'm still seeing this in scalatest_2.10 3.0.0, is that possible? Was it fixed?

```scala
val a1 = Array(20 -> 1)
val a2 = Array(20 -> 1)

// Passes
a1 should be(a2)
a1 should ===(a2)

val m1 = Map("test" -> Array(20 -> 1))
val m2 = Map("test" -> Array(20 -> 1))

// Passes
m1("test") should be(m2("test"))
m1("test") should ===(m2("test"))

// Fails!
m1 should be(m2)
m1 should ===(m2)

val mv1 = Map("test" -> Vector(20 -> 1))
val mv2 = Map("test" -> Vector(20 -> 1))

// Passes
mv1 should be(mv2)
mv1 should ===(mv2)
```

**Comment by mxl** [comment]
I'm also seeing this issue in 3.0.1 while testing `Option[Array[Byte]]` with `mustEqual`.

**Comment by bvenners** [comment]
Yes, that's unfortunately a feature. The idea was that we just use == and you can make a custom equality if you want one, except Arrays at the top level we call .deep on. For example you could make a custom equality for Option[T] that grabs the Equality[T]. There are traits for recursive equality of collections, but I don't think we have one in there for Option.

It is surprising behavior, but I don't believe we can go recursive by default without changing behavior silently. That's probably OK in tests, but not in production code. What I'm thinking of doing is adding a DeepEquality trait you can select that would give deep equality for collections, Options, Either, Java Collections, etc. I'm still thinking about which way to go, but I am wanting to do some improvements in that space.

**Comment by mxl** [comment]
Could we at least reopen the issue or open the new one to mark that it was not solved?

**Comment by bvenners** [comment]
Yes, if you like. I did not get it into 3.0 as I was hoping, but I would like to do something about it. I was thinking a lot about it just last week. At the same time I'm thinking about having all === type-checked in one way or another.

**Comment by schlichtanders** [comment]
any progress on deep equality checks?

**Comment by jendakol** [comment]
I'm quite disappointed with this behavior. I use scalatest_2.12 3.0.7 and my test keeps failing when comparing case class instances with `Array[Byte]` field, both when using assertions and matchers - custom `Equality` instance is just not used :-1:

**Comment by jendakol** [comment]
@miguno Any comment on the closing? Is it working now or..?

**Comment by jendakol** [comment]
TBH I have no idea whether it works now :-) What does @bvenners think?

**Comment by benkio** [comment]
I think we can reopen this. I tried it at work and still the equality is not guaranteed. 
I created a Scatsie to prove this:
https://scastie.scala-lang.org/DDao3ToqS2eHO6jBUQPzNw

would be good to add such test in the unit tests of `scalatest` 😉
