### ISSUE TITLE
add -z to the sbt runner documentation

### ISSUE THREAD

**Issue by fommil** [scalatest/scalatest#501]
I know I asked about this at Scala eXchange in December, and you said it works, I wasn't able to find any documentation on how to actually run a single test via sbt: http://www.scalatest.org/user_guide/using_scalatest_with_sbt

Is running a single test inside a funspec supported from sbt?

For us to add support in ENSIME we'll also need to be able to infer the name of an enclosing test for a specific point in a file (by inspecting the compiler AST), or extract all the names from the class. Are there any convenience methods for doing the latter?

**Comment by bvenners** [comment]
Hi Sam,

Yes. You can use -t with the full test name or -z with any substring of the
testname. I usually use -z. Like:

test-only *SomeSpec -- -z "some substring"

Bill

On Sat, Jan 31, 2015 at 10:58 AM, Sam Halliday <notifications@github.com>
wrote:

> I know I asked about this at Scala eXchange in December, and you said it
> works, I wasn't able to find any documentation on how to actually run a
> single test via sbt:
> http://www.scalatest.org/user_guide/using_scalatest_with_sbt
>
> Is running a single test inside a funspec supported from sbt?
>
> For us to add support in ENSIME we'll also need to be able to infer the
> name of an enclosing test for a specific point in a file (by inspecting the
> compiler AST), or extract all the names from the class. Are there any
> convenience methods for doing the latter?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalatest/scalatest/issues/501>.
>



-- 
Bill Venners
Artima, Inc.
http://www.artima.com

**Comment by fommil** [comment]
Great! Please update the  docs because this is an incredibly useful feature :-)
