### ISSUE TITLE
auto disable color on dumb terminals

### ISSUE THREAD

**Issue by fommil** [scalatest/scalatest#511]
It would be incredibly useful if the colour output was automatically disabled (no need to pass a flag to the runner) if the terminal is detected to be a dumb terminal, e.g. output piped to an emacs buffer. Otherwise this is what one sees:

```
[info] 36mRun completed in 4 minutes, 58 seconds.0m
[info] 36mTotal number of tests run: 780m
[info] 36mSuites: completed 14, aborted 00m
[info] 36mTests: succeeded 78, failed 0, canceled 0, ignored 0, pending 00m
[info] 32mAll tests passed.0m
```

and setting the option for the whole build means that colours cannot be seen when run in a colour capable terminal.

**Comment by bvenners** [comment]
Is there a Unix filter for Ansi color characters? If not, it seems like it would be easy to write. Could that address your situation?

**Comment by fommil** [comment]
not for Windows I don't think. BTW, when run from inside emac the envvar `INSIDE_EMACS` is always set.

**Comment by fommil** [comment]
@bvenners while I'm poking around the source code, where would this be best implemented?

When run in emacs, the envvar `INSIDE_EMACS` is always set and that should imply disabling colour output. It's really awkward to disable colours for every project that I ever care to contribute to.

**Comment by bvenners** [comment]
Essentially what you'd like is to automatically set -oW, which means the standard out reporter (which when running via sbt means the events sent to sbt) gets set if the INSIDE_EMACS environment variable exists or is set to a certain value? the way I'd do that is once up front, in Runner and Framework.

If this is only something that involves sbt it could be a feature of the Framework implementation. 

On the other hand, I assume this means that inside sbt you get no color? Is there some other way besides ansi colors to get color there? I think the color helps a lot with the readability.

**Comment by fommil** [comment]
Emacs adds the colours :-) (and turns everything into clickable links)

**Comment by bvenners** [comment]
How does it know what colors to make things?

**Comment by fommil** [comment]
Regular expression matching. This is the Emacs compilation mode.

**Comment by bvenners** [comment]
I see, so you can set up regular expressions just for ScalaTest and set the colors of lines accordingly?

**Comment by fommil** [comment]
Yup! And define what the contextual parts of the regex represent so they can be autoscrolled or jump to source clickable links.
