### ISSUE TITLE
support `include allOf`

### ISSUE THREAD

**Issue by mauhiz** [scalatest/scalatest#513]
`contain allOf` works for collections; would be nice to have the same feature work on `include` for strings.

**Comment by bvenners** [comment]
Do you mean allOf contains a list of strings, and this would be looking for substrings? If you mean characters, you can just use string should contain allOf ('a' ,'b', 'c').

**Comment by mauhiz** [comment]
I meant substrings

**Comment by bvenners** [comment]
Sorry I think we won't add this enhancement, at least not for now. It would be non-obvious whether the substrings would be allowed to overlap, also if we had include allOf, what about include oneOf and the others. For now, I'd suggest writing an includeAllOf custom matcher that does what you want.
