### ISSUE TITLE
matcher for raw boolean

### ISSUE THREAD

**Issue by fommil** [scalatest/scalatest#519]
Sometimes I need have to call a method that doesn't match the rules for the parameter-less boolean Matcher syntax. It would be nice to be able to use a matcher with the symbol, instead of being forced to use `assert(.... === true)`

**Comment by bvenners** [comment]
I'm not sure what you mean by "matcher with the symbol." Can you clarify?

**Comment by fommil** [comment]
This sort of thing only works if `iter` has a no-param method on it returns Boolean

```scala
iter shouldBe 'traversableAgain
```

but often I find myself wanting to test that some method call returns true/false, e.g. `(file: java.io.File).exists()`

**Comment by fommil** [comment]
Doh! I just figured out how this works. The symbol is the name of the method being tested.

```scala
classfile shouldBe 'exists
```

Never mind me.

**Comment by bvenners** [comment]
Ah, that's what you meant by symbol. I was thinking symbolic operator!
