### ISSUE TITLE
RFE: repeat test until it fails

### ISSUE THREAD

**Issue by fommil** [scalatest/scalatest#533]
I have a test that is failing due to a rare race condition. There is about 1% chance of failure. I'd like to be able to automate the failure during fixing the bug. It would be good if there was an option to do a `test-only` and repeat running the test until it fails (with an upper bound).

**Comment by tsandall** [comment]
+1

**Comment by Grogs** [comment]
+1

**Comment by bvenners** [comment]
Hi All,

This sounds like a good job for overriding withFixture. withFixture gets the test body passed in as a function. The test has already started when withFixture is invoked (i.e., the TestStarting event has already been fired). withFixture's job is to invoke that test function, and by default, that's all it does. When the test function returns, the test has not yet completed, so you can change its outcome, including by rerunning it until it fails with an upper bound. This may make a nice addition to ScalaTest itself, but it is achievable with just a few lines of code yourself in the meantime. I'm teaching a class today, but when I'll try and whip up an example and post it yere.

**Comment by danbim** [comment]
+1
