### ISSUE TITLE
errors with build 2.3.x (scalatest.js)

### ISSUE THREAD

**Issue by yawnt** [scalatest/scalatest#569]
Not sure if I'm doing something wrong, but as I mentioned to @cheeseng on Twitter, when I try to 
```
> scalatestAllJS/compile
```
I get a bunch of errors.. `master` compiles fine, I'm running JDK8 and apart from disabling doc generation, it's a straightforward clone from GitHub

Output: https://gist.github.com/yawnt/060f8822348f543c7892

**Comment by cheeseng** [comment]
thanks for reporting, i just did a quick try, not getting exactly the same as yours with 65 errors found, seems like our recently works for xxxElements broke it, i'll try to fix it and submit a PR today.

**Comment by yawnt** [comment]
yep, no worries.. if there's anything you need just ask :) .. should `2.3.x` have 100% scala.js compatibility? when is it due? thanks!

**Comment by cheeseng** [comment]
@yawnt do you mind to try out my quick fix?  it is available in this branch in my fork: 

https://github.com/cheeseng/scalatest/tree/fix-for-scalatest.js

to try: 
git clone git://github.com/cheeseng/scalatest.git
cd scalatest
git checkout fix-for-scalatest.js
sbt scalatestAllJS/compile
sbt scalatestAllJS/test   // to run the tests on rhino

**Comment by cheeseng** [comment]
@yawnt it will include a big subset of scalatest that can be made working with scala.js, there's some features that cannot be done at the moment due to lack of some supports in scala.js, e.g. things like stack depth (depends on stack trace element but in js env it is not guaranteed behavior), threads (js is single-threaded) and things that depends on java classes (that are not supported in scala.js).

**Comment by cheeseng** [comment]
as far as i can tell, 2.3.x is due soon, and for scalatest.js support, we just want it to be tested first before we include it in 2.3.0 release, and the good news is the fix for the blocker or our tests in scala.js seems to be coming in: 

https://github.com/scala-js/scala-js/pull/1616

**Comment by yawnt** [comment]
of course, you can't port 1-1 from jvm to js, if it's a big subset it's good enough :) 
I will be testing it throughly in the coming days so I'll definitely post here if something breaks

as for your fix: compile works, test too (although i did see a "No tests runned" through the logs, before it started running the actual tests.. I suppose it's normal?)

```
[info] Run completed in 4 minutes, 1 second.
[info] Total number of tests run: 1642
[info] Suites: completed 52, aborted 0
[info] Tests: succeeded 1642, failed 0, canceled 0, ignored 0, pending 3
[info] All tests passed.
[success] Total time: 408 s, completed Apr 27, 2015 10:57:57 AM
```

oh and also there were some `hi` printed to stdout :P

last question, now that it's working, should I be using `2.3.x` or `master` (`3.0.0-SNAP4`) ?

**Comment by cheeseng** [comment]
@yawnt i would suggest you to stick with 2.3.x, though it is broken currently in scalatest/scalatest.  i'll submit my changes as PR to scalatest/scalatest's 2.3.x branch today, and hopefully it will be merged in soon after @bvenners is available to do so, while the other things that you saw are normal, as we separate scalactic/scalatest and their tests in separate project, sbt will try to run test on the scalactic/scalatest project and got 0 tests in them, and those tests running are in scalacticTestJS and scalatestTestJS actually.

**Comment by gzm0** [comment]
@cheeseng a quick note, that the upstream fix just got merged. So you are good to test with a snapshot.

**Comment by cheeseng** [comment]
@gzm0 thanks!  what a great news!  we'll definitely start testing it with the snapshot, it should be 0.6.3-snapshot, right?

**Comment by gzm0** [comment]
Yes. But of my last knowledge, we don't publish them :-/

**Comment by cheeseng** [comment]
@gzm0 i see, we'll have to build and publish locally then, shall we use the master branch?

**Comment by gzm0** [comment]
Yes. Instructions on how to publish locally are here: https://github.com/scala-js/scala-js/blob/master/DEVELOPING.md#publish-locally

**Comment by yawnt** [comment]
great, i'll go with 2.3.x then.. just a heads up, I'm still getting 
```
[error] (scalatestJS/compile:doc) java.io.FileNotFoundException: /home/yawnt/Code/scalatest-cheeseng/scalatest.js/src/main/html/addl.css (No such file or directory)
```
when compiling from scratch, disabling docs in build.sbt fixes the issue, but it's a workaround :)

**Comment by cheeseng** [comment]
yes i haven't not really try doc yet for scalatest.js project, probably just need to copy over the mentioned css file.  i'll try to fix it today since you mentioned it.  :)

**Comment by yawnt** [comment]
i think we can close this, i was able to successfully compile 2.3.x 

with regard to the `FileNotFoundException` the issue is that although `html/` exists in `scalatest/src`, it doesn't in `scalatest.js/src`

I get the error every time I run `publishLocal` so i just [disabled doc generation altogether](http://sprunge.us/OXDc)
