### ISSUE TITLE
BeforeAndAfterAll missing from scalatestjs

### ISSUE THREAD

**Issue by yawnt** [scalatest/scalatest#572]
As per title, this is vital for `akka-testkit`

I added `BeforeAndAfterAll.scala` to `project/GenScalatestJS.scala` and it still compiles, but I'm not familiar with scalatest's codebase. If that's the right way I'd be happy to submit a PR!

/cc @cheeseng

**Comment by cheeseng** [comment]
@yawnt after it compiles i normally will create a simple example spec that uses BeforeAndAfterAll and make sure it runs ok in js environment, anyway, scala-js team merged in the changes we required to run our tests, so tomorrow I could try it out with 0.6.3-snapshot (needs to build locally) and see if BeforeAndAfterAllSpec can be run without problem.  Not sure about your timezone, you might want to give it a shot while I am asleep.  :)

**Comment by yawnt** [comment]
I'm Italy based (CET)!

**Comment by yawnt** [comment]
I will compile 0.6.3 myself and give it a go if i see some code from you, repo/branch i should look out for?

**Comment by cheeseng** [comment]
sorry i fell asleep last night after my last post! (i am in Malaysia GMT+8)  currently we should always branch off from scalatest/scalatest's 2.3.x branch, which is the main development branch currently.  i am going to work on scalatest.js now.  :)

**Comment by yawnt** [comment]
no worries! will look out for changes then, thanks again!

**Comment by yawnt** [comment]
`BeforeAndAfterEach` is also missing, should I just keep reporting here or make another issue? Maybe it's best if I make a list

**Comment by cheeseng** [comment]
@yawnt I got BeforeAndAfterAllSpec passed, though the process is quite a pain, you might want to have a look at my branch here: 

https://github.com/cheeseng/scalatest/tree/scala-js-0.6.3-SNAPSHOT

The branch can't be built without building scala-js 0.6.3-SNAPSHOT locally, and unfortunately that's not all you need.  The troublesome part is really building nyaya (which we experimental use in tests to replace scalacheck) and its dependencies, it is quite a painful process.

I think one thing you can do is to build the branch using current 0.6.2, without running the tests (BeforeAndAfterSpec won't work without the new scala-js feature they added in 0.6.3), and do a publishLocal to use it.

Oh I just see your message about BeforeAndAfterEach, I'll try to run its tests and get it working tomorrow.  :)

**Comment by yawnt** [comment]
so will BeforeAndAfterAll/Each work with 0.6.2? scalatest's tests are not an issue right now

**Comment by cheeseng** [comment]
@yawnt yes it should work, unless you're are creating anonymous class like we did in our tests, something like this: 

val suite = new FunSuite {
  ...
}

scala-js will raise compiler error under 0.6.2, but will be fixed in 0.6.3.

**Comment by yawnt** [comment]
0.6.3 is out, I think we can close this?

**Comment by cheeseng** [comment]
@yawnt i am going to tried out 0.6.3 now, once it is working I'll close this issue.

**Comment by cheeseng** [comment]
Already working on 0.6.5 as of this writing.
