### ISSUE TITLE
tricky problem with `Empty test suite`

### ISSUE THREAD

**Issue by sangszhou** [scalatest/scalatest#573]
There are two unit tests listed below, one works well, the other reports 'empty test suite'.

The difference between this two test cases is that the second one contains a space at the end of test case name. It troubles for a quite long time before I located this problem. 

I'm using scalatest 2.2.1 with FunSuite only.

```
test("transfer to") {
    val transferTo = Dao.findTransferTo(alarmId).await
    println(transferTo)
  }
```

```
test("transfer to ") {
    val transferTo = Dao.findTransferTo(alarmId).await
    println(transferTo)
  }
```

**Comment by bvenners** [comment]
Can you elaborate on how you are running these tests? When I run them directly they both execute the test:

scala> class OneSuite extends FunSuite {
     |   test("transfer to") {
     |     fail("hmm")
     |   }
     | }
defined class OneSuite

scala> class TwoSuite extends FunSuite {
     |   test("transfer to ") {
     |     fail("hmm")
     |   }
     | }
defined class TwoSuite

scala> run(new OneSuite)
OneSuite:
- transfer to *** FAILED ***
  hmm (<console>:18)

scala> run(new TwoSuite)
TwoSuite:
- transfer to  *** FAILED ***
  hmm (<console>:18)

**Comment by sangszhou** [comment]
Yes, of course. Sorry for this not expressive question.

I ran this two test case in intellij idea 14.1. When run test case separately(it's a cool feature provided by intellij idea of running one single test case within a test class), the second case report empty test suite. If run this test cases together(run all test cases within a test class), everything is OK.

By putting mouse cursor in a test case and right click run test case, intellij idea run that single test.

**Comment by bvenners** [comment]
I see. This is actually an IntelliJ bug. Can you report it to IntelliJ?

Thanks.

Bill

**Comment by sangszhou** [comment]
Ok, thanks for answering :+1:
