### ISSUE TITLE
Just a question about a nice feature you have.

### ISSUE THREAD

**Issue by dvorobiov** [scalatest/scalatest#574]
Hi,
This is not an issue, I would like to ask to point me at some code that implements something in the scalatests. Sorry for your time!

Every test is running in an independent environment. If I for example update a field in an object, by design it should be visible in every test, but it looks like every test is executed in a isolated environment. Where do you do that? You are not running a separate JVM for every test, aren't you? I am looking through the code trying to understand where it happens.

**Comment by bvenners** [comment]
Sorry I thought I'd replied to this question already. Must have imagined replying. Anyway, the answer depends on how your tests are defined. By default tests in the same Suite class will share the same instance data. If you mix in OneInstancePerTest, it will run each test in its own instance. ParallelTestExecution extends OneInstancePerTest, so it also has this behavior. Does that sound like it could explain the behavior you see?
