### ISSUE TITLE
scalatest.js cannot export a local class

### ISSUE THREAD

**Issue by yawnt** [scalatest/scalatest#575]
I have an abstract class which is instantiated through `new` inside a test, and scala fails with 

```
You may not export a local class
```
I think it might be because scalatest is using @JSExportDescendentClasses upper in the chain and thus causing it to fail.. any idea? 
maybe the `ignore` flag upcoming in scala-js 0.6.3 might help
Thanks!

@cheeseng

**Comment by bvenners** [comment]
Most likely yes. We were able to move forward with a local build of 0.6.3 source. Not sure when 0.6.3 will be out.

**Comment by cheeseng** [comment]
@yawnt yes it is the main thing fixed in 0.6.3. :)

**Comment by yawnt** [comment]
oki, i'll build 0.6.3 then :D.. thanks!
