### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by xerial** [scalatest/scalatest#576]
Scala 2.12.0-M1 is released today:
http://www.scala-lang.org/news/2.12.0-M1

To test this version, we need a scalatest library built for Scala 2.12, because most of my projects use scalatest. Could you provide a library for Scala 2.12.0-M1?

Thanks in advance.

**Comment by bvenners** [comment]
Just got off a plane. Will do a build now.

**Comment by bvenners** [comment]
Voila:

https://oss.sonatype.org/content/groups/public/org/scalatest/scalatest_2.12.0-M1/2.2.5-M1/

Let me know if there are any problems with it.

**Comment by xerial** [comment]
Thanks for the quick work! 

It worked without any problem :)

**Comment by bvenners** [comment]
You're welcome. Glad to hear it works on 2.12.0-M1!
