### ISSUE TITLE
BeWord scaladoc uses invalid links to (deprecated) ShouldMatchers

### ISSUE THREAD

**Issue by jaceklaskowski** [scalatest/scalatest#578]
[The scaladoc of BeWord](http://doc.scalatest.org/2.2.4/#org.scalatest.words.BeWord) links to `Should-` and `MustMatchers`, but they don't exist (they were moved to `matchers` package).

**Comment by bvenners** [comment]
Thanks for pointing that out. I fixed it in 2.3.x as well and a also a couple other mentions of ShouldMatchers.

https://github.com/scalatest/scalatest/commit/e227e5e981cd473aebe24f0745506e9291ca3fe3
