### ISSUE TITLE
scalatest-js: prop.Checkers missing

### ISSUE THREAD

**Issue by yawnt** [scalatest/scalatest#581]
as per title, scalacheck has experimental scala-js support, so it should be possible to port it, I think?
@cheeseng

**Comment by yawnt** [comment]
I tried to uncomment `Checkers.scala` and I've added `scalacheck` to the deps, but it isn't picking it up (`scalacheck isn't a member of package org` etc..). Any other place I should copy that in?

**Comment by cheeseng** [comment]
@yawnt we have some tests written using scalacheck but had problem running them with scalacheck.js, as far as I remember it is still due to java class usage in scalacheck, perhaps scalacheck needs further work to support scala-js correctly, and that was the reason we tried nyaya.  Anyway, I'll try to see if Checkers can be supported correclty.

**Comment by yawnt** [comment]
I got it to compile by merging https://github.com/rickynils/scalacheck/pull/163 and removing `Commands.scala` (it was giving me linking errors, which is weird because since `Commands.scala` doesn't appear to be used in scalatest, scala-js should just remove the code, maybe I did something wrong)

After that I hand compiled your 0.6.3-SNAPSHOT branch and it *seems* to be working, but so far I've only ported akka tests that **extend** Checkers, not use any of scalacheck's API

**Comment by cheeseng** [comment]
That's sounds like a good sign, hopefully CheckersSpec (under org.scalatest.prop) would pass, (CheckersSpec probably need to be rewritten to FunSpec, as reflection-based Spec won't work).

**Comment by cheeseng** [comment]
@yawnt as for the dependency problem, did you try to use %%%  ?

**Comment by yawnt** [comment]
yeah, you can't use the triple `%` because you're in a .scala file, not in a build.sbt (iirc)

**Comment by cheeseng** [comment]
@yawnt that's weird, if i remember correctly i used triple % in .scala file when trying to run our tests written with scalacheck, just curious what error did you get if you use triple % ?  :)

**Comment by InTheNow** [comment]
just found this issue. We've used scalacheck on sjs extensively with no problems, perhaps it's just the master version that you are using that was refactored. But the sjs support should be 100% on scalacheck.

**Comment by InTheNow** [comment]
By "we", i refer to [banana-rdf](https://github.com/w3c/banana-rdf) that uses a mix of [zcheck](https://github.com/InTheNow/zcheck) and scalatest (for the jvm only parts). zCheck is/was only a temporary solution so b-rdf might be a good candidate to try out scalatest-js by porting the zchecks back to scalatest.

see last line in https://github.com/w3c/banana-rdf/pull/248#issuecomment-103134256 for reference.

Other projects that I'm also working on for sjs support that may be of interest for RC testing are typelevel [discipline](https://github.com/typelevel/discipline) and more interestingly, [spire](https://github.com/non/spire) and then [cats](https://github.com/non/cats). I seem to recall @bvenners chatting on the cats gitter about scalatest on sjs, although I can't recall the details.

**Comment by cheeseng** [comment]
@InTheNow interesting, sorry the only thing I can recall is that I was not using 0.6.3, it was probably 0.6.2 or 0.6.1, perhaps I shall give it a try again with the latest 0.6.3.  :)

Thanks a lot for your details explanation!

**Comment by InTheNow** [comment]
also see https://github.com/rickynils/scalacheck/issues/157#issuecomment-103988407 - new version imminent :)

Thanks for sjs port work, btw :+1:

**Comment by yawnt** [comment]
`ShouldCheckers` is missing too

**Comment by cheeseng** [comment]
@yawnt I can't seems to find any ShouldCheckers in 3.0.0 source, but prop.Checkers should be in 3.0.0-SNAP5 already.

**Comment by yawnt** [comment]
yeah, i switched to Checkers, must be old code I was porting, we can close this since Checkers is available, I suppose?
Thanks again for your awesome work
