### ISSUE TITLE
publish a 2.3.0-SNAPSHOT version

### ISSUE THREAD

**Issue by yawnt** [scalatest/scalatest#585]
As in my experience not many people are aware of the effort to port scalatest over to Scala-js, I think it would be beneficial to publish a `2.3.0-SNAPSHOT` version.
This would also allow people to start playing with it and identify potential issues.

If possible, can we include the new version of scalacheck + enable `Matchers` in it, given that [unicredit/akka.js](https://github.com/unicredit/akka.js) depends on it? Thank you!

@cheeseng

**Comment by InTheNow** [comment]
:+1:  I'm helping [spire](https://github.com/non/spire) cross-compile with sjs so I would need the full scalacheck support (that I currently have local). Additionally, I'm doing the same for [typelevel discipline](https://github.com/typelevel/discipline).

More interestingly for me though, as I'm an official maintainer, would be for [banana-rdf](https://github.com/w3c/banana-rdf), These projects, including akka,js, would, IMHO, give you guys a nice set of projects - _pre release_

**Comment by ngbinh** [comment]
:100:

**Comment by rhz** [comment]
That would be great

**Comment by InTheNow** [comment]
I'm also adding sjs support [to cats](https://github.com/non/cats/pull/325) that currently uses scalatest.

@bvenners Any rough time scales on this, please?

**Comment by bvenners** [comment]
We are ready to do that actually today but need to figure out how to release it. We've never actually released it before for Scala.js. Not sure how long that will take, but we'll get a SNAP out as soon as we figure that out.

**Comment by sjrd** [comment]
Normally there's nothing to do. Just `publish` or `publishSigned` as usual, on Maven or whatever else as usual. The `ScalaJSPlugin` takes care of the details for you ;)

**Comment by cheeseng** [comment]
@sjrd would ScalaJSPlugin append the sjs automatically to the artifact name?  we saw that in the artifact published on maven and wonder if we should add that in to support %%%?

**Comment by sjrd** [comment]
Yes, it is automatically added, with the correct binary version number. So `_sjs0.6` at the moment.

**Comment by cheeseng** [comment]
@sjrd that's will be great, thanks!  :+1:

**Comment by bvenners** [comment]
So @srjd is it the case that the artifacts will be deployed as "org.scalatest" % "scalatest_sjs0.6" % "VERSION" and "org.scalactic" % "scalactic_sjs0.6" % "VERSION"? Is that the way you want people to deploy such things?

**Comment by sjrd** [comment]
Actually it will be `"org.scalatest" % "scalatest_sjs0.6_2.11" % "VERSION"`, which is equivalent to `"org.scalatest" %% "scalatest_sjs0.6" % "VERSION"`, which is equivalent to `"org.scalatest" %%% "scalatest" % "VERSION"`, which is exactly the way we want people to deploy such things, indeed.

**Comment by bvenners** [comment]
Wow, three percent signs! Anyway, that sounds good. I am going to try that.

**Comment by bvenners** [comment]
@srjd I tried publishSigned like usual and it worked like usual for the JVM artifacts, but I got no JS artifacts. We have the plugin:

https://github.com/scalatest/scalatest/blob/2.3.x/project/plugins.sbt#L5

Anything else we need to do to our build to get this to kick in? We're publishing from the 2.3.x branch:

https://github.com/scalatest/scalatest/blob/2.3.x/project/scalatest.scala

Thanks.

**Comment by sjrd** [comment]
Hum I can't even load sbt in the project. It tells me this:
```
[info] Compiling 26 Scala sources to C:\Users\Sepi\Documents\Projets\scalatest\project\target\scala-2.10\sbt-0.13\classes...
[error] C:\Users\Sepi\Documents\Projets\scalatest\project\scalatest.scala:124: not found: value pgpSecretRing
[error]     pgpSecretRing := file(getGPGFilePath),
[error]     ^
[error] C:\Users\Sepi\Documents\Projets\scalatest\project\scalatest.scala:125: not found: value pgpPassphrase
[error]     pgpPassphrase := getGPGPassphase
[error]     ^
[error] two errors found
[error] (compile:compile) Compilation failed
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```
Hard to debug this way. :-(

So if you run

    > scalacticJS/publishLocal

for example, that doesn't work?

That said, the way you have named your Projects, you'll get the wrong artifact name. For scalacticJS, for example, it implicitly has the name `scalacticJS` and hence the module name `scalacticjs`, which would produce an artifact `scalacticjs_sjs0.6_2.11`. If you don't want to the change the name but still want the correct artifact name, use this sbt setting:

    moduleName := "scalactic"

in the scalacticJS project.

**Comment by sjrd** [comment]
> Hum I can't even load sbt in the project.

OK that was a weird local config of mine. I fixed that.

So for me `scalacticJS/publishLocal` definitely publishes correctly the artifact (although, as I said, with the name `scalacticjs_sjs0.6_2.11` instead of `scalactic_sjs0.6_2.11`).

**Comment by bvenners** [comment]
Cool thanks. I was going to try that next.

**Comment by bvenners** [comment]
I think moduleName did the trick: Here's ScalaTest's first release for Scalajs:

https://oss.sonatype.org/content/groups/public/org/scalatest/scalatest_sjs0.6_2.11/3.0.0-SNAP5/

And Scalactic's first release for Scala.js:

https://oss.sonatype.org/content/groups/public/org/scalactic/scalactic_sjs0.6_2.11/3.0.0-SNAP5/

Thanks for all your help. Let me now if you have trouble with these. Hopefully we'll have beginners luck.

**Comment by sjrd** [comment]
Seems to work fine :-D
https://github.com/sjrd/scala-js-example-app/commit/e05309ac61e51cb397d15b6d408e1d77e8207b5f

Rhino blows up with it, though. But in FastOpt and FullOpt mode it works fine.

**Comment by ngbinh** [comment]
Awesome! Thanks for this.

**Comment by yawnt** [comment]
I think I can close this then :) .
Just a quick note, `ShouldMatcher` seems to be missing, maybe it hasn't been enabled yet?

**Comment by cheeseng** [comment]
@yawnt i believe ShouldMatcher will be removed in 3.0.0, and org.scalatest.Matchers should be used instead.

**Comment by InTheNow** [comment]
@bvenners, @cheeseng This is _excellent_ news!! Will hold back the flood of hyperboles :)

**Comment by bvenners** [comment]
By the way, we are expiring all deprecations that were added by the time of the ScalaTest 2.0.0 release (Oct, 2013), so you should eliminate deprecation warnings prior to upgrading to 3.0.0. One of those is the ShouldMatchers name, which was changed to Matchers in 2.0.0. Other than deprecation expirations, there are very few potential breakages for either ScalaTest or Scalactic user code in 3.0.0. But much that runs on the JVM of course will be missing on JS: anything that uses reflection, threads, etc. Our next task is to figure out how to document the differences between the libraries on JVM and JS.
