### ISSUE TITLE
Wrong docs/samples on property-based testing with `forAll` 

### ISSUE THREAD

**Issue by pniederw** [scalatest/scalatest#612]
http://www.scalatest.org/user_guide/table_driven_property_checks says:

> The second parameter list is a function whose argument types and number matches that of the tuples in the table.

However, the function takes a single argument, namely a row tuple. Code samples are wrong too, missing a `case`.

**Comment by pniederw** [comment]
Turns out I was mistakenly using `Inspectors#forAll`.

**Comment by bvenners** [comment]
Sorry, perhaps a bit too much overloading going on here. By the way, your diagrams continue to make users happy:

https://twitter.com/aspyker/status/591015187949355008
