### ISSUE TITLE
gitter channel ?

### ISSUE THREAD

**Issue by chandu0101** [scalatest/scalatest#626]
Many projects using it already ( scala/scala.js/sbt/scala-ser/....)  , i almost forgot irc! . it will be cool if we have a gitter channel for scalatest too :)

**Comment by bvenners** [comment]
Good idea. Not sure how to create one yet but I think that would be nice to do. We'll try and figure it out then post here once it is working.

Bill

**Comment by chandu0101** [comment]
it super simple login to  u r gitter account 
-> create Room
-> choose Repository
-> done (gitter will send a automated PR )

![screen shot 2015-06-25 at 8 12 12 am](https://cloud.githubusercontent.com/assets/2179670/8345854/626ae520-1b12-11e5-839d-ff13e1f24221.png)

**Comment by bvenners** [comment]
We created a gitter channel several months back , but never closed this issue. Closing now.
