### ISSUE TITLE
Scala 2.12.0-M2

### ISSUE THREAD

**Issue by kxbmap** [scalatest/scalatest#646]
Scala 2.12.0-M2 released last week:
http://www.scala-lang.org/news/2.12.0-M2

Could you publish the library for 2.12.0-M2?

**Comment by holograph** [comment]
Seconded, I'm working on getting some upstream dependencies (namely [Accord](http://www.github.com/wix/accord)) geared up for 2.12 and would like to avoid building this on my own :-)

**Comment by bvenners** [comment]
Sure. Started yesterday but ran out of time. Will try to get it out today.

**Comment by bvenners** [comment]
I have deployed a release. Sorry it took so long this time. Just don't have any spare time right now. And, this one has many failing tests. I figured people would prefer mostly working bits to waiting longer. 2.12.0-M2 broke the Spec trait and some stack depths. If you're using Spec, you won't be able to use this unless you port to a different style. If a test fails, the stack depth may occasionally be wrong, but you can still look at the stack trace and figure out where the failing assertion is.

**Comment by bvenners** [comment]
Oh, the release number is 2.12.0-M2.

**Comment by kxbmap** [comment]
Thanks a lot!
It works fine for me.

**Comment by holograph** [comment]
Well it resolves fine ("org.scalatest" %% "scalatest" % "2.2.5-M2", though I had to conditionally depend on different versions for 2.10 and 2.11), but I can't test it because of other considerations. I'll post back when I've had any luck/lack thereof.

**Comment by holograph** [comment]
OK, managed to work around my other issues (good ole sbt and resetAllAttrs... *sigh*). Anyway the good news are that everything, including tests, works fine with 2.12. Well done, and thanks for the extremely fast turnaround!

**Comment by holograph** [comment]
Followup: there appear to be no Scala.js binaries for 2.12; don't know if this is intentional or not...?

**Comment by bvenners** [comment]
Hi Tomer,

Is there a scala.js build for 2.12.0-M2?

Bill

**Comment by holograph** [comment]
As far as I can tell, yes: http://search.maven.org/#search%7Cga%7C1%7Cg%3Aorg.scala-js

**Comment by bvenners** [comment]
Hi Tomer,

OK. Thank. We'll do a 3.0.x release for 2.12.0-M2, which will also include
the Scala.js artifacts.

Bill

On Wed, Jul 29, 2015 at 9:55 PM, Tomer Gabel <notifications@github.com>
wrote:

> As far as I can tell, yes:
> http://search.maven.org/#search%7Cga%7C1%7Cg%3Aorg.scala-js
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalatest/scalatest/issues/646#issuecomment-126183057>
> .
>



-- 
Bill Venners
Artima, Inc.
http://www.artima.com

**Comment by holograph** [comment]
Looking forward to it. Thanks for the quick turnaround!

**Comment by 2m** [comment]
I was wondering why the additional `M2` suffix in the version name? This makes every build that uses scalatest to have additional logic that chooses version string based on the scala version, when trying out Scala 2.12-MX instead of just adding a new scala version to `crossScalaVersions`.

**Comment by holograph** [comment]
Also, ping?

**Comment by bvenners** [comment]
Unfortunately although the ScalaTest 2.2.5 codebase compiled under Scala 2.12.0-M2, it did not pass all its tests. Two things didn't work: Spec, the style with test methods, and some stack depths. I didn't have time to investigate yet, and since it is 99% usable I released it, but as 2.2.5-M2. 

The reason I didn't have time to investigate the 2.12.0-M2 problem yet is the same reason I didn't have time to do release a 3.0.x release for 2.12.0-M2 yet: I had guests visiting at the same time I'm very busy with a contract, and that left little time for ScalaTest. I did just drop half of my guests off at the airport this morning, so there's light at the end of the tunnel. I'll get these builds out as quickly as I can.

**Comment by holograph** [comment]
That's fine, and I don't mind prerelease versions (given that it's in order to support prerelease versions of Scala...). Any news re the 2.12.0-M2/Scala.js artifacts?

**Comment by bvenners** [comment]
We did try that last week but got stuck because there's no ScalaCheck compiled for Scala.js for Scala 2.12.0-M2. We are very busy right now with a client contract, so I haven't had time to follow up since. I'll request such a build from Rickard?

**Comment by holograph** [comment]
Cool, thanks for the update!

**Comment by holograph** [comment]
Ping...

**Comment by holograph** [comment]
While we're at it, I recommend switching to 2.12-M3...

**Comment by bvenners** [comment]
We deployed ScalaTest/Scalactic 2.2.5 build here for 2.12.0-M3:

https://oss.sonatype.org/content/groups/public/org/scalatest/scalatest_2.12.0-M3/2.2.5-M3/

**Comment by holograph** [comment]
Thanks! I'll try it out. I think this ticket can be closed?
