### ISSUE TITLE
pendingUntilFixed is supporting Exception and AssertionError how about also supporting NotImplementedError

### ISSUE THREAD

**Issue by talgendler** [scalatest/scalatest#651]
_org.scalatest.Suite: 1657_

``` scala
catch {
        case _: Exception => true
        case _: AssertionError | NotImplementedError => true
      }
```

I can pull request if needed. Or this is by design ? In that case please update the documentation

**Comment by ezoerner** [comment]
+1

This allows the use of `???` in the product code with `pendingUntilFixed`

**Comment by talgendler** [comment]
Not sure if this still relevant after 4.5 years....
