### ISSUE TITLE
option to disable parallelExecution for scalatests when running in eclipse scala-ide

### ISSUE THREAD

**Issue by moglideveloper** [scalatest/scalatest#652]
I am not able to find an option to disable parallelExecution for scalatests when running tests in scala-ide for eclipse (Eclipse option to run scala test => Run as Scala Test)

**Comment by bvenners** [comment]
In general in ScalaTest, tests run sequentially unless you ask them to run in parallel . sbt will cause suites to be run in parallel by default, but not tests in a single suite. For that you'd need to mix in ParallelTestExecution, which I doubt you have. In Eclipse I would expect everything is sequential. Why do you think they are running in parallel?

**Comment by bvenners** [comment]
Since I didn't hear back from you on this issue, I'm going to close it. If it is still a problem for you please post a comment here and I'll reopen it.
