### ISSUE TITLE
xml streamlining not working in `shouldEqual`?

### ISSUE THREAD

**Issue by fommil** [scalatest/scalatest#653]
I have a test that does this...

```scala
      import StreamlinedXml._

      responseAs[NodeSeq] shouldEqual
        <html>
          <head/>
          <body>
            <h1>ENSIME: Your Project's Documention</h1>
            <ul><li><a href="docs/bar-javadoc.jar/index.html">bar-javadoc.jar</a> </li><li><a href="docs/foo-javadoc.jar/index.html">foo-javadoc.jar</a> </li></ul>
          </body>
        </html>
```

but it fails if any of the formatting of the XML literal is changed :cry:

context here:

https://github.com/fommil/ensime-server/commit/7de82245e4b54a12e5d39c15ee1b1618ad71c99b#commitcomment-12601544

**Comment by bvenners** [comment]
Looks like correct usage. I'll give the code a try.

**Comment by fommil** [comment]
to make it easy

```
git clone git@github.com:fommil/ensime-server.git
cd ensime-server
git checkout docserver
sbt server/test
```

**Comment by cheeseng** [comment]
hi @fommil I just tried the following: 

git clone https://github.com/fommil/ensime-server.git
cd ensime-server
git checkout docserver

but got branch not found error, did you push the branch?  Or I am cloning a wrong repo perhaps?

**Comment by cheeseng** [comment]
@fommil @bvenners actually I wonder if you should use the following instead?

```
import StreamlinedXmlEquality._
```

since shouldEqual is taking a an implicit Equality, as provided by StreamlinedXmlEquality not StreamlinedXml.

**Comment by fommil** [comment]
It was all merged to upstream master

**Comment by cheeseng** [comment]
@fommil @bvenners I did a quick test, seems like StreamlinedXmlEquality should do the job, can you try to use StreamlinedXmlEquality (not StreamlinedXml as you did previously) and see if it fixes your problem?

**Comment by fommil** [comment]
yup, that fixes it, thanks! I wonder if I did a typo or if I read a doc with a typo.
