### ISSUE TITLE
ThreadStop Interruptor

### ISSUE THREAD

**Issue by scalasolist** [scalatest/scalatest#657]
There are bunch of suggested Interruptors acording to scaladoc:
* ThreadInterruptor
* DoNotInterrupt
* SelectorInterruptor
* SocketInterruptor

But them all require cooperative behaviour from interrupted thread. It should process interrupt exception correspondingly. Moreover it should receive it first, which is hardly possible in an infinite loop. I know, infinite loops are programming errors, but tests is for searching and handling those errors, so the test suit should be capable of stopping threads going wild.

So there is need for ThreadStop Interruptor that uses Thread.stop to kill threads. I know Oracle discouraged this functionality. They say: "No one need killing thread, you should write your programs gracefully and your threads should cooperate via well-defined and guarded by exceptions IPC". But this advice have zero benefit when your run thread with untrusted code: either plugin system or testing system.

In such case to cope with thread that declines cooperating the only option left is Thread.stop. I'm aware that it considered dangerous because thread may be killed in the middle of accessing and modifying shared resources. But that danger may be overcome with neat usage of monitors. Every time thread access data shared with another thread it should raise synchronized flag that killer thread takes in consideration.

Talking about test suits, the only time it interacts with calling thread is when checking result. So if result is not already calculated the thread may be killed safely. And than thread raises flag: "I'm working on answer" and because checking is done by well tested code of the scalatest itself it would not fall in infinite loop, so the main thread may just wait for it instead of killing.

**Comment by levinson** [comment]
In short there is no guaranteed way to kill a thread in Java, even Thread.stop requires that your thread cooperate (e.g. that it does not catch the ThreadDeath exception and ignore it).

Oracle has a good explanation as to why its unsafe and unreliable: https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#stop--

If you absolutely must call Thread.stop it should be done in your test code and not part of scalatest.

**Comment by scalasolist** [comment]
And how ScalaTest is supposed to handle infinite loop? Just hang up and wait for kill signal?

**Comment by bvenners** [comment]
Hi scalasolist,

Did you try creating an implementation of Interruptor that calls stop()?

http://doc.scalatest.org/2.2.4/index.html#org.scalatest.concurrent.Interruptor

That's perfectly fine, and if that solves your problem it would be nice to know. Is that what you did? If not, could you try that and confirm it addresses your need?

Thanks.

Bill

**Comment by scalasolist** [comment]
I've written simple custom threadpool that can cancel activities with Thread.stop. It uses Thread.stop together with some mutexes to prevent data corruption. Just calling Thread.stop() is insufficient.

**Comment by bvenners** [comment]
OK. Just to clarify, you're not using a custom Interruptor that uses thread.stop?

**Comment by scalasolist** [comment]
Not for now. If I would have no other choice I will start using it.

**Comment by bvenners** [comment]
@scaladolist I don't think it is a good idea to add a StopInterruptor to ScalaTest, because there is no good way to stop its propagation except by catching it in failAfter and cancelAfter, and that seems very problematic. As @levinson said, there is no sure fire way to stop a thread on the jvm, because even thread death exception can be caught. So interrupters can't always interrupt. That means that sometimes a test will hang, and ScalaTest has other features for debugging that. One is dlowpoke detectors, which print out info including suite and test name of long running tests.Another is that when you do a thread dump you'll see that ScalaTest has given threads names that include the suite and rest name. So I'm going to close this issue.
