### ISSUE TITLE
Running Future-returning tests sequentially

### ISSUE THREAD

**Issue by ramnivas** [scalatest/scalatest#712]
This is from the https://groups.google.com/forum/#!topic/scalatest-users/dZWxEzJkyVM forum thread (that contains more details, especially @bvenners comments on how this might be implemented), but adding here as an issue for better tracking.

---
I have tests of the following form (ran from both Scala JVM and Scala.js):

```scala
class MyTest extends AsyncFunSuite {
  def setup() : Future[Unit] = {
    // reset the remote test database to a known state
  }
  
  test("test1") {
    setup().map { _ =>
      // test code that returns a future
    }
  }
  
  test("test2") {
    setup().map { _ =>
      // test code that returns a future
    }
  }
}
```

I will like scalatest to execute tests serially i.e. *logical* equivalent of:

```scala
test("test1").andThen {
  // record success/failure of test1 and ...
  test("test2").andThen {
    // record success/failure of test2 and ...
    ...
  }
}
```
This way while test1 is running, test2 doesn't end up resetting the database.

**Comment by bvenners** [comment]
Hi Ramnivas,

At long last I have a release for you to try. Thanks for your patience. It was quite a lot of work to get to this point, but in 3.0.0-SNAP6 we by default don't start an async test until the previous async test has completed. If you want async tests to run in parallel, you'll need to mix in ParallelTestExecution. I'll post a bit more detail about the latest changes on scalatest-users. Please give 3.0.0-SNAP6 a try and let us know if it works for your use case.

Thanks.

Bill

**Comment by ramnivas** [comment]
Hi @bvenners,

Thanks.

I could try `AsyncFunSuite` in a JVM project. It is working fine, except IntelliJ seems to not like tests that complete their `Future` in a delayed manner. Tests pass or fail randomly during each run (for me a delay of < 50ms makes it randomly fail, whereas anything above that makes it always fail). For example in the snippet below, while the testsuite passes fine from SBT, IntelliJ gives up while attempting to run the "this fails" test (no report, no failure or success). Probably an IntelliJ issue, but just wanted to let you know in case something has changed between what IntelliJ expects and Scalatest provides. Note that the second test ("this succeeds") always succeeds in IntelliJ (i.e. even though the test takes time, the future returned by the test has been already completed).

```scala
import org.scalatest._
import scala.concurrent.{ExecutionContext, Future}

class AsyncTest extends AsyncFunSuite {
  override implicit val executionContext: ExecutionContext = ExecutionContext.Implicits.global

  def setup(): Future[Unit] = {
    Thread.sleep(1000)
    Future.successful(())
  }

  test("this fails") {
    for {
      _ <- setup()
    } yield assert(true)
  }

  test("this succeeds") {
    Thread.sleep(1000)
    Future(assert(true))
  }

}
```

**Comment by bvenners** [comment]
Hi Ramnivas,

Thanks for trying it. I'll experiment with IntelliJ and let you know what I
find.

Bill

On Tue, Oct 13, 2015 at 2:07 PM, Ramnivas Laddad <notifications@github.com>
wrote:

> Hi @bvenners <https://github.com/bvenners>,
>
> Thanks.
>
> I could try AsyncFunSuite in a JVM project. It is working fine, except
> IntelliJ seems to not like tests that complete their Future in a delayed
> manner. Tests pass or fail randomly during each run (for me a delay of <
> 50ms makes it randomly fail, whereas anything above that makes it always
> fail). For example in the snippet below, while the testsuite passes fine
> from SBT, IntelliJ gives up while attempting to run the "this fails" test
> (no report, no failure or success). Probably an IntelliJ issue, but just
> wanted to let you know in case something has changed between what IntelliJ
> expects and Scalatest provides. Note that the second test ("this succeeds")
> always succeeds in IntelliJ (i.e. even though the test takes time, the
> future returned by the test has been already completed).
>
> import org.scalatest._import scala.concurrent.{ExecutionContext, Future}
> class AsyncTest extends AsyncFunSuite {
>   override implicit val executionContext: ExecutionContext = ExecutionContext.Implicits.global
>
>   def setup(): Future[Unit] = {
>     Thread.sleep(1000)
>     Future.successful(())
>   }
>
>   test("this fails") {
>     for {
>       _ <- setup()
>     } yield assert(true)
>   }
>
>   test("this succeeds") {
>     Thread.sleep(1000)
>     Future(assert(true))
>   }
>
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalatest/scalatest/issues/712#issuecomment-147854277>
> .
>



-- 
Bill Venners
Artima, Inc.
http://www.artima.com

**Comment by cheeseng** [comment]
PR submitted to fix this: 

https://github.com/scalatest/scalatest/pull/740

**Comment by bvenners** [comment]
Hi Ramnivas,

I merged in this PR and released a 3.0.0-SNAP7. I tried both M10 and SNAP7
with your test class with IntelliJ. SNAP7 always works for me. M10 never
works for me. So I think it should be fixed in SNAP7. Please give that a
try if you get a chance.

We are going to do an M11 that goes back to Unit for traditional styles and
gets rid of Safety and Compatibility. So that's coming, and it will have
this fix in it.

Thanks for trying it out.

Bill

On Tue, Oct 20, 2015 at 4:35 AM, Chua Chee Seng <notifications@github.com>
wrote:

> PR submitted to fix this:
>
> #740 <https://github.com/scalatest/scalatest/pull/740>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalatest/scalatest/issues/712#issuecomment-149420727>
> .
>



-- 
Bill Venners
Artima, Inc.
http://www.artima.com

**Comment by ramnivas** [comment]
Hi Bill and @cheeseng,

Cool! I just tried SNAP7 and it works for me.

Thanks for fixing this issue so quickly.

-Ramnivas

**Comment by bvenners** [comment]
Hi Ramnivas,

No problem. I want to get 3.0 out the door. But I must take back my
previous note about what M11 will look like. Something didn't work out so
back to the drawing board. Been quite a battle with a bloat monster that
wants to move in.

Bill

On Tue, Oct 20, 2015 at 6:43 PM, Ramnivas Laddad <notifications@github.com>
wrote:

> Hi Bill and @cheeseng <https://github.com/cheeseng>,
>
> Cool! I just tried SNAP7 and it works for me.
>
> Thanks for fixing this issue so quickly.
>
> -Ramnivas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalatest/scalatest/issues/712#issuecomment-149644019>
> .
>



-- 
Bill Venners
Artima, Inc.
http://www.artima.com
