### ISSUE TITLE
TripleEqualsSupport broken?

### ISSUE THREAD

**Issue by Sciss** [scalatest/scalatest#725]
I just ran into an error that boils down to this:

    Some(1) === 1   // compiles!

The `TripleEqualsSupports` comes in from a `Suite`.

I suppose this _should not_ compile, right, being the point about having `===` instead of `==`?

**Comment by bvenners** [comment]
Hi Sciss,

Just mix in or import TypeCheckedTripleEquals.

    scala> Some(1) === 1
    res0: Boolean = false

    scala> import TypeCheckedTripleEquals._
    import TypeCheckedTripleEquals._

    scala> Some(1) === 1
    <console>:23: error: types Some[Int] and Int do not adhere to the type constraint selected for the === and !== operators; the missing implicit parameter is of type org.scalactic.CanEqual[Some[Int],Int]
           Some(1) === 1
                   ^

The === by default does no type checking. That was for compatibility with old ScalaTest 1.0 code. I didn't want upgrading to 2.0 to break a bunch of code, some of which wasn't a bug. For example, 1L === 1 doesn't compile under TypeCheckedTripleEquals:

scala> 1L === 1
<console>:23: error: types Long and Int do not adhere to the type constraint selected for the === and !== operators; the missing implicit parameter is of type org.scalactic.CanEqual[Long,Int]
       1L === 1
          ^

But when allowed to compile it says true:

    scala> import TripleEquals._
    import TripleEquals._

    scala> 1L === 1
    res3: Boolean = true

The point of === without a type check is it allows for custom equalities, such as comparing arrays structurally:

    scala> Array(1, 2, 3) === Array(1, 2, 3)
    res4: Boolean = true

**Comment by Sciss** [comment]
Oh, alright, thanks for clarifying! I was totally unaware that I need that additional import.
