### ISSUE TITLE
Scala.js build for 2.12.0-M3

### ISSUE THREAD

**Issue by holograph** [scalatest/scalatest#749]
Now that Scala.js is out for 2.12.0-M3 (see scala-js/scala-js#1937), is it possible to release 2.2.5 and/or 3.0.0-M10 for it?

Sorry for being a pest about this, I'm trying to get Accord as close to ready for 2.12 as possible, and ScalaTest is one of our major dependencies (wix/accord#46).

**Comment by cheeseng** [comment]
@holograph I released a version for 2.12.0-M3 last week: 

https://oss.sonatype.org/content/groups/public/org/scalatest/scalatest_2.12.0-M3/

Sorry that we didn't announce it publicly yet.

**Comment by holograph** [comment]
Thanks, but I was specifically referring to a corresponding Scala.js build :-)



—

**Comment by cheeseng** [comment]
@holograph i see, that's has to be 3.0.x series then, fyi we're about to finish a refactoring that we can release 3.0.0-M11 (hopefully in a day or two), then perhaps we can release together a scala-js version for it.

**Comment by cheeseng** [comment]
@holograph I tried to release 3.0.x for 2.12.0-M3, but unfortunately scalacheck 1.12.5 is not published for scala-js 0.6 and scala 2.12.0-M3 yet.  I'll try to request it on scalacheck github issue.

**Comment by cheeseng** [comment]
Requested on ScalaCheck here: 

https://github.com/rickynils/scalacheck/issues/204

**Comment by holograph** [comment]
It's out for either, but not both (i.e. no build for scala-js 0.6 on Scala 2.12.0-M3). This cross-build thing is getting out of hand :-/

**Comment by cheeseng** [comment]
@holograph I just deployed 3.0.x-M12, do you mind giving it a try?  sorry again for the delay.

**Comment by matanster** [comment]
Collapsing here from [my duplicate](https://github.com/scalatest/scalatest/issues/777),  Would it be very hard to publish 2.2.5 also for M2? rational for requesting one version backward at https://github.com/scalatest/scalatest/issues/777.

Additionally, for cross-built projects using 2.2.5, as much as you want to support that, is it not the case that the artifact name needs to exclude the string "M3" in it? in a naive cross build setup, the current artifact [scalatest_2.12.0-M3-2.2.5-M3-javadoc.jar](https://oss.sonatype.org/content/groups/public/org/scalatest/scalatest_2.12.0-M3/2.2.5-M3/) will not be looked up by ivy/sbt for:

```
  "org.scalatest" %% "scalatest" % "2.2.5" % "test",
```

**Comment by holograph** [comment]
Tested with 3.0.0-M12 and seems to be working fine. +1 for 2.2.5 backporting (if it's reasonable), so I can support both ScalaTest 2.x and 3.x -- assuming that's even desirable...

**Comment by bvenners** [comment]
Hi Tomer,

Sorry, can you clarify what you'd like with 2.2.5? Backporting what, and what version number?

Thanks.

Bill

**Comment by holograph** [comment]
By "backporting" I mean releasing 2.2.5 for 2.12.0-M3, with and without Scala.js.

I don't know how binary-compatible matcher libraries can be between 2.x and 3.x; with Specs2 I ended have having to release separate modules (ironically built on the exact same source). I suspect I'll have to do something similar with ScalaTest.

**Comment by bvenners** [comment]
I just read through this issue and I'm not sure what might still be needed.  Can the interested parties please refresh their requests?

**Comment by holograph** [comment]
With the M4 releases for both 2.2.6 and 3.x already out, nothing is necessary as far as I'm concerned :-)
Thanks!
