### ISSUE TITLE
Set spanScaleFactor when running tests using sbt

### ISSUE THREAD

**Issue by chipsenkbeil** [scalatest/scalatest#761]
Is there a way to specify the spanScaleFactor when running the tests using sbt via `sbt test` or `sbt it:test`? From the code I've seen, it looks like it can only be set via `-F <some factor>` when using the scalatest runner.

https://github.com/scalatest/scalatest/blob/62f2b411ab3ee4d99768f94a64ad087c7c05b3df/scalatest/src/main/scala/org/scalatest/concurrent/ScaledTimeSpans.scala#L198

Is there a way to pass that option via sbt through the command line or an environment variable? I need to be able to scale my test timeouts when running on Travis CI. If not, I guess I'll need to write my own version of the `scaled` function that checks for an environment variable.

I'm using the latest tentative release of 3.0.0, by the way, which is `3.0.0-M11`. Need it to get around some parallel test issues.

**Comment by cheeseng** [comment]
@chipsenkbeil SBT should read -F and set Runner.spanScaleFactor accordingly: 

https://github.com/scalatest/scalatest/blob/master/scalatest/src/main/scala/org/scalatest/tools/Framework.scala#L1125

If it is not working for you, do you mind sharing with us a sample project that reproduce your problem?

**Comment by chipsenkbeil** [comment]
Awesome! How exactly do I pass this value in via the command line with sbt? `sbt -F 10 it:test`, `sbt "it:test -F 10"`, `sbt "-F 10 it:test", `sbt it:test -F 10`, `sbt it:test -- -F 10`, and `sbt "it:test -- -F 10"` all give me errors regarding invalid input.

So, what is unclear to me is how I pass the -F option when starting an sbt test task.

**Comment by cheeseng** [comment]
@chipsenkbeil -- only works for test-only, I don't think you can pass arguments to sbt's test task directly, it has to be set through testOptions (perhaps you can set the testOptions from env var):

testOptions in Test += Tests.Argument(TestFrameworks.ScalaTest, "-F", "10")

here's the related sbt documentations: 

http://www.scala-sbt.org/0.13/docs/Testing.html

Hope they help.  :)

**Comment by chipsenkbeil** [comment]
@cheeseng great! Got it working thanks to your suggestion. I was trying to use standard Test.Argument instead of specifying the ScalaTest test framework. For reference, I added the following to my own Common.scala whose settings are included in each project to read in an environment variable for the span scale factor:

```scala
object Common {
  lazy val scalaTestSpanScaleFactor = settingKey[Double](
    "Sets scaling factor of running tests that are wrapped in scale(...)"
  )

  def settings = Seq(
    ...
    scalaTestSpanScaleFactor := {
      Try(System.getenv("SCALATEST_SPAN_SCALE_FACTOR").toDouble).getOrElse(1.0)
    },

    testOptions in Test += Tests.Argument(TestFrameworks.ScalaTest,
      "-F", scalaTestSpanScaleFactor.value.toString
    ),

    testOptions in IntegrationTest += Tests.Argument(TestFrameworks.ScalaTest,
      "-F", scalaTestSpanScaleFactor.value.toString
    ),
    ...
  )
}
```
