### ISSUE TITLE
old version of sbt-pgp

### ISSUE THREAD

**Issue by fommil** [scalatest/scalatest#818]
I'm unable to build scalatest due to this error, which I presume is because you're using an old version of sbt-pgp (I have it installed in my system-wide config).

```
[error] /home/fommil/Projects/scalatest/project/scalatest.scala:131: not found: value pgpSecretRing
[error]     pgpSecretRing := file(getGPGFilePath),
[error]     ^
[error] /home/fommil/Projects/scalatest/project/scalatest.scala:132: not found: value pgpPassphrase
[error]     pgpPassphrase := getGPGPassphase
[error]     ^
[error] two errors found
[error] (compile:compileIncremental) Compilation failed
```

**Comment by fommil** [comment]
interesting, and now

```
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
```

you know if you need specific heap requirements, you can specify them in a `.jvmopts` file (only picked up by `sbt-extras`), e.g. https://github.com/ensime/ensime-server/blob/master/.jvmopts

**Comment by bvenners** [comment]
Yes, extra heap is needed to build. We described it on the readme:

https://github.com/scalatest/scalatest/tree/3.0.x

**Comment by bvenners** [comment]
Did you get past the pgpSecretRing problem?

**Comment by fommil** [comment]
yup, got past it by disabling my system-wide version. I'll have to remember to turn it back on again.

**Comment by bvenners** [comment]
OK. We'll try and update that this week.

**Comment by bvenners** [comment]
OK. We'll update the version of that.

**Comment by fommil** [comment]
cool, thanks. I recommend adding a `.jvmopts` file too containing the flags you need. For ENSIME, I tend to use `.sbtopts` locally (not commited to git) which contains my `-java-home` setting to ensure that I use Java 6.
