### ISSUE TITLE
matcher for collection containing a partial function

### ISSUE THREAD

**Issue by fommil** [scalatest/scalatest#829]
I often find myself wanting to write a test along the lines of "this collection should contain a {... partial function ... }". I think this would be a great addition to the containers matchers http://www.scalatest.org/user_guide/using_matchers#workingWithContainers

**Comment by fommil** [comment]
(the important thing here is that the error would contain the list received... most workarounds to the above involve just saying "it failed" and not giving the failure case)

**Comment by bvenners** [comment]
Hi Sam,

That's done with inspector shorthands in ScalaTest Matchers.

http://doc.scalatest.org/2.2.6/index.html#org.scalatest.Matchers@inspectorShorthands

    atLeast (1, xs) should be > 0

The reason I never added a contain <partial function> syntax is that the error message can only say the partial function wasn't satisfied. By doing shorthands you can get a more descriptive error message, and it does usually do a pretty good job at showing its reasoning. Here's an example:

    scala> val xs = List(1, 2, 3, 4, 5)
    xs: List[Int] = List(1, 2, 3, 4, 5)

    scala> atLeast (1, xs) should be > 0
    res1: org.scalatest.Assertion = Succeeded

    scala> atLeast (1, xs) should be < 0
    org.scalatest.exceptions.TestFailedException: 'atLeast(1)' inspection failed, because no element satisfied the assertion block:
      at index 0, 1 was not less than 0 (<console>:21),
      at index 1, 2 was not less than 0 (<console>:21),
      at index 2, 3 was not less than 0 (<console>:21),
      at index 3, 4 was not less than 0 (<console>:21),
      at index 4, 5 was not less than 0 (<console>:21)
    in List(1, 2, 3, 4, 5)
      at org.scalatest.enablers.InspectorAsserting$$anon$3.indicateFailure(InspectorAsserting.scala:294)
      at org.scalatest.enablers.InspectorAsserting$$anon$3.indicateFailure(InspectorAsserting.scala:290)
      at org.scalatest.enablers.UnitInspectorAsserting$InspectorAssertingImpl.forAtLeast(InspectorAsserting.scala:93)
      at org.scalatest.Matchers$class.doCollected(Matchers.scala:3146)
      at org.scalatest.Matchers$.doCollected(Matchers.scala:7761)
      at org.scalatest.Matchers$ResultOfCollectedAny.should(Matchers.scala:5272)
      ... 43 elided

**Comment by fommil** [comment]
awesome! :grinning: 

```scala
              atLeast(1, expectMsgType[SymbolSearchResults].syms) should matchPattern {
                case TypeSearchResult("baz.Foo$", "Foo$", DeclaredAs.Class, Some(_)) =>
              }
```

while I have you do you have the equivalent of `testkit`'s `awaitCond`? I need the above to return a boolean for that to integrate well.

**Comment by bvenners** [comment]
Hi Sam,

By the way can you give inspector shorthands a try and let me know if it meets your need? It is called inspector shorthands because 1) it sounds like the name of a private detective and 2) it is a shorthand, matcher-specific variant of the more general Inspectors:

http://doc.scalatest.org/2.2.6/index.html#org.scalatest.Inspectors

Bill

**Comment by bvenners** [comment]
That was quick!

**Comment by fommil** [comment]
@rorygraves ^^^ you will like

**Comment by bvenners** [comment]
Ah, is awaitCond like eventually? Eventually is here:

http://doc.scalatest.org/2.2.6/index.html#org.scalatest.concurrent.Eventually

**Comment by fommil** [comment]
perfect! Wow, four new features about scalatest I'm using today.

**Comment by fommil** [comment]
(I'll probably want to align the patience config with my existing akka testkit machine-scaled values)

**Comment by bvenners** [comment]
yes there should be a trait for that. Probably we should have an ScalaTest+Akka lib for things like that. Anyway what you would do is define Patience in terms of the TestKit values.

ScalaTest also has its own time dialation feature, by the way, but I make you say "scaled" in the code. The reason I did that is I didn't like the idea that when someone says failAfter(3 seconds) it doesn't necessarily mean 3 seconds. So if you want it to be dialatable you need to write failAfter(scaled(3 seconds)). Then it looks like what it is. But it is easy to forget to write scaled, so not sure it was the best choice in retrospect.

**Comment by fommil** [comment]
FYI I think it looks something like

```scala
  private val akkaTimeout: Timeout = ConfigFactory.load().getDuration("akka.test.default-timeout", TimeUnit.MILLISECONDS) milliseconds

  implicit override val patienceConfig = PatienceConfig(timeout = akkaTimeout.duration)
```

I've not done automatic scaling here, which would be achieved with something like

```
  private val akkaTimeFactor: Int = ConfigFactory.load().getInt("akka.test.timefactor")
```

**Comment by fommil** [comment]
more complete

```scala
  private val akkaTimeout: Timeout = ConfigFactory.load().getDuration("akka.test.default-timeout", TimeUnit.MILLISECONDS) milliseconds
  override val spanScaleFactor: Double = ConfigFactory.load().getDouble("akka.test.timefactor")
  implicit override val patienceConfig = PatienceConfig(
    timeout = scaled(akkaTimeout.duration),
    interval = scaled(5 milliseconds)
  )
```
