### ISSUE TITLE
anInstanceOf matcher

### ISSUE THREAD

**Issue by pathikrit** [scalatest/scalatest#835]
```scala
"hello" should be anInstanceOf[String]
```

**Comment by pathikrit** [comment]
@bvenners wrote here that it will be added - https://groups.google.com/forum/#!topic/scalatest-users/UrdRM6XHB4Y - not sure if that happened.

**Comment by bvenners** [comment]
Yes, we added it but dropped the nInstanceOf. Try:

    "Hello" shouldBe a [String]
