### ISSUE TITLE
Async before and after

### ISSUE THREAD

**Issue by LMnet** [scalatest/scalatest#953]
It is more feature request, than issue.
ATM all `before` and `after` stuff is fully synchronous: all methods returns `Unit`. It would be good to have a possibility to have an asynchronous versions of this methods. Typical use case for this async methods: operations with DB. For now i'm forced to use `Await.ready` to block my async operations.
I can suggest two options for the implementation:

1. Add extra methods into existent traits.
2. Add new traits, like `BeforeAndAfterAllAsync`.

Personally, I prefer the first way.

**Comment by cheeseng** [comment]
Hi @LMnet , in 3.0 we have made BeforeAndAfter and BeforeAndAfterAll to work with async style trait, I wonder if they fit your use case?

**Comment by LMnet** [comment]
I'm using 3.0 version with `AsyncFreeSpec`. But in `BeforeAndAfterAll` `beforeAll` and `afterAll` methods are synchronuous. I checked run method in `BeforeAndAfterAll` and I didn't find any async stuff there. If my action inside `beforeAll` or `afterAll` returns `Future`, I want to wait until it finished.

**Comment by bvenners** [comment]
@LMnet That's done here:

https://github.com/scalatest/scalatest/blob/3.0.x/scalatest/src/main/scala/org/scalatest/BeforeAndAfterAll.scala#L223

The withAfterEffect method registers the afterAll code to run as an effect after the Status returned by super.run completes. The Status is kind of like a Future[Boolean].

**Comment by LMnet** [comment]
@bvenners But what about `before`? `withAfterEffect` could replace only `after` method. And using this method looks like hack for me.

**Comment by jhegedus42** [comment]
Is this issue solved already ? 

I put up a related SOF question:
https://stackoverflow.com/questions/46584633/async-before-in-scalatest-for-scalajs

**Comment by harmeetsingh0013** [comment]
What exactly the solution for this ticket? I have requirements, where we need to call multiple future calls in the beforeAll method.

**Comment by bvenners** [comment]
We haven't done anything with beforeAll. Let me think about if that is possible, and if so how best to go about it.

**Comment by bilal-fazlani** [comment]
What's the status of this issue?

**Comment by ThijsBroersen** [comment]
I am also in need of an async beforeAll. Have not found any solution which does not include blocking (which is not possible in Scala.js).

**Comment by espetro** [comment]
Hi there! Is this issue already solved? I am also interested in it for Scala in JVM

**Comment by harpocrates** [comment]
How is this issue closed? Even if there's a workaround for an asynchronous `afterAll`, there's still no way to have asynchronous `beforeAll`.

Should I open a new issue?

**Comment by mirelon** [comment]
Please reopen this issue as there is no possibility to execute asynchronous code in `beforeAll()`
