### ISSUE TITLE
LeftProjection and RightProjection deprecated in 2.12.0-RC1

### ISSUE THREAD

**Issue by Lasering** [scalatest/scalatest#972]
The following test:

``` scala
class T1 extends FunSuite with Matchers with EitherValues {
  test("EitherValues should work without deprecation warnings") {
      val r: Either[String, Int] = Right(5)
      val l: Either[String, Int] = Left("Teste")
      r.right.value shouldBe 5
      l.left.value shouldBe "Teste"
  }
}
```

With the following build.sbt:

``` sbt
name := "Test"

version := "1.0"

scalaVersion := "2.12.0-RC1"

libraryDependencies ++= Seq(
  "org.scalatest" %% "scalatest" % "3.0.0" % Test
)

scalacOptions ++= Seq(
  "-deprecation",                   //Emit warning and location for usages of deprecated APIs.
  "-Xfatal-warnings",               //Fail the compilation if there are any warnings.
  "-Xlint"                         //Enable recommended additional warnings.
)
```

Will fail:

```
Error:(7, 9) method right in class Either is deprecated (since 2.12.0): Either is now right-biased
      r.right.value shouldBe 5
Error:(8, 9) method left in class Either is deprecated (since 2.12.0): use swap instead
      l.left.value shouldBe "Teste"
```

**Comment by bvenners** [comment]
I think this is correct behavior, given these have been deprecated in the standard library. This seems like a big and frankly unnecessary change to users, but it is what's in store for us. If this is removed in say 2.13, then we'll need to somehow conditionally compile this out of ScalaTest when building for that version. What people will need to do is change all uses of Either they've ever used to get rid of the deprecation warning, so I think having the deprecation warnings is a good thing. Do you agree?

**Comment by Lasering** [comment]
Yes, the deprecation warnings are a good thing. But that wasn't really what I was aiming for.

My idea is that EitherValues has now became a lot less useful (especially for people like me that compile with "-deprecation" and "-Xfatal-warnings"). Let me try to explain why: to overcome the deprecation I've started using OptionValues instead of EitherValues, like this:

```scala
class T1 extends FunSuite with Matchers with OptionValues {
  test("EitherValues should work without deprecation warnings") {
      val r: Either[String, Int] = Right(5)
      val l: Either[String, Int] = Left("Teste")
      r.toOption.value shouldBe 5
      l.swap.toOption.value shouldBe "Teste"
  }
}
```

This solution completely solves the problem, however my intention, to a future reader of my code, is not as easily transmitted as it has with the usage of EitherValues. EitherValues presented the reader with a more semantic and direct meaning, where as using OptionValues makes it more clunky.

A possible solution could be:
```scala
trait EitherValues {
  implicit def convertEitherToValuableEither[L, R](either: Either[L, R])(implicit pos: source.Position): ValuableEither[L, R] = new ValuableEither(leftProj, pos)

class ValuableEither[L, R](either: Either[L, R], pos: source.Position) {
    def rightValue: R = {
      try {
        either.toOption.get
      }
      catch {
        case cause: NoSuchElementException => 
          throw new TestFailedException((_: StackDepthException) => Some(Resources.eitherRightValueNotDefined), Some(cause), pos)
      }
    }

    def leftValue: R = {
      try {
        either.swap.toOption.get
      }
      catch {
        case cause: NoSuchElementException => 
          throw new TestFailedException((_: StackDepthException) => Some(Resources.eitherLeftValueNotDefined), Some(cause), pos)
      }
    }
  }
}
```
Plus deprecating the current LeftValuable and RightValuable.

**Comment by bvenners** [comment]
That's a good idea. I actually thought about rightValue and leftValue way back when I first did EitherValues. But it seemed nicer to say right.value. Now it is too bad I didn't do rightValue and leftValue to begin with, but we can do that now.

**Comment by Lasering** [comment]
To which branch should I make the pull request against? 3.1.x? 3.0.x-for-scala-2.12.x?

**Comment by bvenners** [comment]
3.1.x

**Comment by SethTisue** [comment]
the deprecation will be reversed in 2.12.0-RC2 due to negative community feedback

**Comment by xavierguihot** [comment]
Deprecation is still there in `2.13`: https://www.scala-lang.org/api/current/scala/util/Either.html

**Comment by SethTisue** [comment]
`.right` remains deprecated; `.left` does not

**Comment by Lasering** [comment]
I think it does not make sense to keep `.left.value` "working" and having to implement `.rightValue`. So it still makes sense to implement both `.rightValue` and `.leftValue`.

**Comment by greg-wb-ap** [comment]
Probably makes the most sense to keep `.left.value` and just add `.value` directly for Either (to match the right bias of Either elsewhere).

**Comment by ant8e** [comment]
As a workaround one can use https://github.com/ironcorelabs/cats-scalatest which has a working impl. of `EitherValues` for scala 2.13

**Comment by rtyley** [comment]
Fixed with https://github.com/scalatest/scalatest/pull/1895.

**Comment by aleksandr-vin** [comment]
This issue can be closed, IMHO.

It'd save time for newcomers to let them scroll down immediately in search for the solution instead of following an open issue's discussion from top to bottom. :)
