### ISSUE TITLE
===, shouldBe, shouldEquals inconsistent behavior with +-  and Options

### ISSUE THREAD

**Issue by jhn** [scalatest/scalatest#988]
[The documentation](http://www.scalatest.org/user_guide/using_matchers#workingWithOptions) says 

> If you wish to check an option is defined, and holds a specific value, you can write any of:

```scala
option shouldEqual Some("hi")
option shouldBe Some("hi")
option should === (Some("hi"))
```

However, `+-` seems to break it:

```scala
1.1 === 1.0 +- 0.1 // true
1.1 shouldBe 1.0 +- 0.1 // true
1.1 shouldEqual 1.0 +- 0.1 // true

Some(1.1) === Some(1.0 +- 0.1) // true
Some(1.1) shouldBe Some(1.0 +- 0.1) // false
Some(1.1) shouldEqual Some(1.0 +- 0.1) //false
```

This was tested on 3.0 as well as 2.2.6.

**Comment by bvenners** [comment]
This is actually as designed. I'd suggest you import OptionValues._ and then say:

Some(1.1).value shouldEqual 1.0 +- 0.1

**Comment by jhn** [comment]
Great, thanks. Maybe we should amend the documentation then? Because:

> If you wish to check an option is defined, and holds a specific value, you can write any of:

sounds misleading.

**Comment by bvenners** [comment]
In the future my plan is that it simply won't compile. If you want that compiler error now you can mix in or import TypeCheckedTripleEquals.

**Comment by bvenners** [comment]
By the way, you can also get the compiler error now if you use the SuperSafe community edition compiler plugin. It is free and would have saved you time in this case. Info on how to install it is here:

http://www.scalatest.org/install

Also, the "Some(1.1) === Some(1.0 +- 0.1)" expression results in false like shouldBe and shouldEqual.
