### ISSUE TITLE
Publish for Scala 2.12.0-RC2

### ISSUE THREAD

**Issue by milessabin** [scalatest/scalatest#989]
Would be very much appreciated :-)

**Comment by xeno-by** [comment]
I'm ready to publish paradise right after scalatest for RC2 is released.

**Comment by cheeseng** [comment]
Blocked by ScalaCheck, we'll ping Ricky to release for ScalaCheck.  :)

**Comment by dwijnand** [comment]
This is like dbuild, but _really_ slow.

Follow the bread crumbs: https://github.com/rickynils/scalacheck/pull/275

**Comment by mosesn** [comment]
If you could publish for scalatest 2.x too, it would be really great too.  We'd rather not tie supporting scala 2.12 to switching to scalatest 3.x.

**Comment by milessabin** [comment]
Scalacheck now published for 2.12.0-RC2: https://github.com/rickynils/scalacheck/pull/275#issuecomment-254441760.

**Comment by cheeseng** [comment]
@milessabin @xeno-by 3.0.0 for Scala 2.12.0-RC2 is published.

**Comment by milessabin** [comment]
Thanks!

**Comment by xeno-by** [comment]
Thank you!

**Comment by schmitch** [comment]
Well I guess it's already there: http://search.maven.org/#artifactdetails%7Corg.scalatest%7Cscalatest_2.12.0-RC2%7C3.0.0%7Cbundle

**Comment by schmitch** [comment]
now it's time for 2.12.0 : https://github.com/scala/scala/tree/v2.12.0

**Comment by mslinn** [comment]
Yes, don't forget scalautils for Scala 2.12.0 :)

**Comment by xeno-by** [comment]
I'd appreciate a 2.12.0 build of scalatest in order to publish paradise :)

**Comment by bvenners** [comment]
I think I'm going to ask Lightbend to please stop making releases on Friday nights. It seems to happen a lot!  I don't like asking people to work on the weekends, so we'll do this on Monday at the latest.

**Comment by schmitch** [comment]
well for me it's not an issue if you don't publish it immediatly. 
I guess most people prefer the weekend to toy around, so I guess releases for scala on thursday and for the testing frameworks on friday would be cool, so that some people who use scala in their free time or helping out open source in their free time can actually toy with it ;)

**Comment by bvenners** [comment]
Yes, I do make the request to publish on the weekend, because it is important to the community. But I don't like doing that. Regardless, we couldn't publish today because ScalaCheck wasn't out yet.

**Comment by etorreborre** [comment]
Scalacheck is [out](https://oss.sonatype.org/content/repositories/releases/org/scalacheck/scalacheck_2.12) for Scala 2.12!

**Comment by cheeseng** [comment]
FYI: I just released Scalactic and ScalaTest 3.0.0 built for 2.12.0.

**Comment by xeno-by** [comment]
@cheeseng Thank you very much! I've just released macro paradise 2.1.0 for 2.12.0.

**Comment by cheeseng** [comment]
@xeno-by You're most welcome!

**Comment by SethTisue** [comment]
(close this ticket now?)

**Comment by bvenners** [comment]
yes.
