### ISSUE TITLE
sourceManaged is not pointing to where Scala sources are

### ISSUE THREAD

**Issue by dragos** [scalatest/scalatest#997]
The build generates a number of files and places them in `target/src_managed/main/scala`. However, the Sbt setting `sourceManaged` is pointing to `target/src_managed/main` only. This is the case of every project.

Many tools that interface with the Scala compiler (Ensime, Scala IDE) rely on the value of `sourceManaged` to point to where sources can be found. In this case, pointing to `target/src_managed/main` will effectively consider that files in there are in an additional package `scala`, like `scala.org.scalatest.Resources`, instead of `org.scalatest.Resources`.

A cursory glance at the build shows that `sourceManaged` is used to place other files in there, such as html or java, and at each generation, an additional directory is manually specified.

**Comment by cheeseng** [comment]
Submitted a PR to fix this: 

https://github.com/scalatest/scalatest/issues/997

**Comment by bvenners** [comment]
This was merged a while back, so closing now.: https://github.com/scalatest/scalatest/pull/1234
